[2-C]방은혁 'JPA 게시판 구현 미션' 코드 리뷰 요청합니다!
prgrms-be-devcourse/SpringBoot-Board pull request #101
Opened 2022-05-20 12:45 UTC by hyuk0309

안녕하세요! 😄

JPA 게시판 구현 미션입니다. 코드 리뷰 부탁드립니다!

부담 갖지 마시고 부족한 부분 보이면 알려주세요! 🙋‍♂️

<br/>

## 📌 과제 설명 

JPA 강의에서 주신 요구 사항을 바탕으로 게시판 API를 만들었습니다. 

[요구 사항 링크](https://ancient-citron-06b.notion.site/SpringBoot-Part4-7-632dd10678164daca96a5ea185a02b60)

<br/>

## 👩‍💻 요구 사항과 구현 내용 

- [x] 엔티티 설계

  - VO와 일급 컬렉션을 적용해 봤습니다.

- [x] API

  - 게시글 조회
    - 페이징 조회 (GET "/posts")
    - 단건 조회 (GET "/posts/{id}")

  - 게시글 작성 (POST "/posts")

  - 게시글 수정 (PATCH "/posts/{id}")

- [x] REST-DOCS 이용해 문서화

<br/>

- 엔티티 설계도

![entity-model](https://user-images.githubusercontent.com/29492667/169530281-9a1d85a2-ce58-437e-ae58-a2f39c1287d3.png)

<br/>

- REST-DOCS 문서화
  - /src/docs/asciidocs/index.adoc

2022-05-21 12:43 UTC, sdardew reviewed
부족하지만! 코멘트 달았습니다 ~ : )

2022-05-21 12:43 UTC, sdardew commented on src/main/java/com/prgrms/hyuk/domain/user/User.java
> +        super("");
빈문자열을 주는 걸로 봐선 사용하지 않는 것 같은데, BaseEntity를 상속을 안 받아도 되지 않을까요?

2022-05-21 12:43 UTC, sdardew commented on src/test/java/com/prgrms/hyuk/repository/PostRepositoryTest.java
> +        posts.forEach(post -> log.info(post.getUser().getName().getName()));
단순히 출력만 하는 것 같은데, 왜 출력하셔서 확인하시는 것인지 궁금합니다!

2022-05-21 12:43 UTC, sdardew commented on src/test/java/com/prgrms/hyuk/service/PostServiceIntegrationTest.java
> +        user = new User(new Name("pang"), new Age(26), Hobby.SOCCER);
CUTE 👍

2022-05-21 12:43 UTC, sdardew commented on src/test/java/com/prgrms/hyuk/repository/PostRepositoryTest.java
> +    }
해당 부분은 `@BeforeEach`로 매번 실행하는 것 보다는 `@BeforeAll`로 한번만 실행하는 것이 어떤가요!

2022-05-21 12:43 UTC, sdardew commented on src/test/java/com/prgrms/hyuk/domain/user/NameTest.java
> +    @ValueSource(ints = {1, 15, 30})
처음 봤어요! 배우고 갑니다 ~ : )

2022-05-21 12:59 UTC, ksy90101 requested changes
은혁님 :) 미션하시느라 너무 고생 많으셨습니다 💯 
간단한 피드백을 좀 남겼으니 확인해주세요~
언제든지 질문은 슬랙으로 연락주세요~

2022-05-21 12:59 UTC, ksy90101 commented on pom.xml
> +		</plugins>
여기 인덴트가 이상하네요.
위에도 그런거같은데,,,

2022-05-21 12:59 UTC, ksy90101 commented on src/main/java/com/prgrms/hyuk/controller/PostController.java
> +    }
ExceptionHandler는 따로 빼는게 좋습니다~

2022-05-21 12:59 UTC, ksy90101 commented on src/main/java/com/prgrms/hyuk/controller/PostController.java
> +        return ApiResponse.ok(postService.create(postCreateRequest));
created가 맞는거 같아요.
status를 created로 바꿔볼까요?

2022-05-21 12:59 UTC, ksy90101 commented on src/main/java/com/prgrms/hyuk/controller/PostController.java
> +    @PatchMapping("/posts/{id}")
지금 케이스에서는 Patch가 맞을까요? Put이 맞을까요?

2022-05-21 12:59 UTC, ksy90101 commented on src/main/java/com/prgrms/hyuk/domain/BaseEntity.java
> +@MappedSuperclass
👍

2022-05-21 12:59 UTC, ksy90101 commented on src/main/java/com/prgrms/hyuk/domain/post/Post.java
> +    }
차라리 title과 content가 같이 바뀌게 하면 어떄요?

2022-05-21 12:59 UTC, ksy90101 commented on src/main/java/com/prgrms/hyuk/domain/user/Age.java
> +    private static final int MAX = 100;
100세 이상이 있으면,,,,
죄송합돠,,,

2022-05-21 12:59 UTC, ksy90101 commented on src/main/java/com/prgrms/hyuk/domain/user/Posts.java
> +public class Posts {
👍

2022-05-21 12:59 UTC, ksy90101 commented on src/main/java/com/prgrms/hyuk/domain/user/Posts.java
> +            .collect(toList());
일급컬렉션을 만드는 이유는 더욱더 도메인 로직으로 이동시키기 위함인데요.
그래서 밖에서는 불변컬렉션을 내려주긴 합니다.

2022-05-21 12:59 UTC, ksy90101 commented on src/main/java/com/prgrms/hyuk/dto/ApiResponse.java
> +        return new ApiResponse<>(200, data);
200보단, HTTP 기본적으로 제공해주는 status 상수를 찾아서 적용해보실래요?
ResponseEntity가 어떻게 구현되어 있는지 보셔도 좋을거 같아요.

2022-05-21 12:59 UTC, ksy90101 commented on src/main/java/com/prgrms/hyuk/repository/PostCustomRepositoryImpl.java
> +                    " join fetch p.user u", Post.class)
굳이,,? 이렇게 작성할 필요가 있나요?ㅋㅋㅋㅋ

2022-05-21 17:39 UTC, wisehero reviewed
다른분들께서 많이 남겨주셔서 간단하게만 남겨봤습니다.
테스트 코드부분에서 또 배워갑니다 은혁님! 수고하셨습니다!

2022-05-21 17:39 UTC, wisehero commented on src/main/java/com/prgrms/hyuk/controller/PostController.java
> +@RestController
여기에 @RequestMapping 애노테이션을 써보시는 건 어떨까요?

2022-05-21 17:39 UTC, wisehero commented on src/main/java/com/prgrms/hyuk/domain/post/Post.java
> +        super("");
비어있는 문자열을 넣은 것은 어떤 의미일까요 ??

2022-05-21 17:39 UTC, wisehero commented on src/main/java/com/prgrms/hyuk/domain/user/Age.java
> +    }
나이 검증은 굳이 범위를 잡을거면 기존의 서비스들처럼 만 14세 이상, 미만으로 나누는 것이 의미있을 것 같습니다!

2022-05-21 17:39 UTC, wisehero commented on src/main/java/com/prgrms/hyuk/dto/ApiResponse.java
> +        return new ApiResponse<>(200, data);
HttpStatus enum 클래스를 사용해보세요!

2022-05-24 07:00 UTC, hyuk0309 commented on src/test/java/com/prgrms/hyuk/repository/PostRepositoryTest.java
> +        posts.forEach(post -> log.info(post.getUser().getName().getName()));
제가 작성한 JPQL이 의도한 SQL을 만드는지 눈으로 확인하고 싶어 작성했습니다!
SQL이 의도한 대로 생성되는지 테스트하는 걸 자동화할 방법이 없는 것 같더라고요.🥲

2022-05-24 07:19 UTC, hyuk0309 commented on src/test/java/com/prgrms/hyuk/repository/PostRepositoryTest.java
> +    }
피드백 감사합니다! 

하지만 테스트마다 Post 엔티티의 생명주기가 달라 @BeforeEach를 이용했습니다. 😃

2022-05-24 07:27 UTC, hyuk0309 commented on pom.xml
> +		</plugins>
꼼꼼한 피드백 감사합니다! 🙇‍♂️

2022-05-24 09:05 UTC, hyuk0309 commented on src/main/java/com/prgrms/hyuk/controller/PostController.java
> +        return ApiResponse.ok(postService.create(postCreateRequest));
피드백 감사합니다! 
똑같은 실수를 반복했네요. 🥲

2022-05-24 09:19 UTC, hyuk0309 commented on src/main/java/com/prgrms/hyuk/controller/PostController.java
> +    @PatchMapping("/posts/{id}")
저는 Patch가 맞다고 생각합니다! 
Patch는 리소스 부분을 변경하는 의미고, Put은 리소스를 대체하는 의미로 알 고 있습니다. [참조](https://tecoble.techcourse.co.kr/post/2020-08-17-put-vs-patch/)

멘토님은 어떻게 생각하시나요? 🤔

2022-05-25 08:08 UTC, hyuk0309 commented on src/main/java/com/prgrms/hyuk/domain/post/Post.java
> +    }
피드백 감사합니다! 🙇‍♂️

2022-05-25 09:22 UTC, hyuk0309 commented on src/main/java/com/prgrms/hyuk/domain/user/Posts.java
> +            .collect(toList());
피드백 감사합니다! 🙇‍♂️

저도 고민하다 stream을 이용해 내려주면, 일급 컬렉션 안에 있는 컬렉션과 분리된 리스트가 반환돼 괜찮을 것이라고 생각했습니다.
하지만 멘토님의 피드백을 받고 보니, 제가 한 방식은 클라이언트에게 혼동을 줄 수 있을 것 같습니다. 멘토님 의견 반영했습니다! 👨‍💻

2022-05-25 09:26 UTC, hyuk0309 commented on src/main/java/com/prgrms/hyuk/dto/ApiResponse.java
> +        return new ApiResponse<>(200, data);
꼼꼼한 피드백 감사합니다! 🙇‍♂️

2022-05-25 09:28 UTC, hyuk0309 commented on src/main/java/com/prgrms/hyuk/repository/PostCustomRepositoryImpl.java
> +                    " join fetch p.user u", Post.class)
Jpa에서 제공하는 API를 사용하면, N + 1 문제가 발생해 fetch join을 이용했습니다! 🥲

2022-05-25 09:30 UTC, hyuk0309 commented on src/main/java/com/prgrms/hyuk/controller/PostController.java
> +@RestController
꼼꼼한 피드백 감사합니다! 🙇‍♂️

2022-05-25 09:33 UTC, hyuk0309 commented on src/main/java/com/prgrms/hyuk/domain/post/Post.java
> +        super("");
요구 사항에는 있지만, 어떻게 활용할지 몰라 애매하게 구현했습니다. 🥲
고민 끝에 제거하는 게 맞다고 생각돼 제거했습니다!

2022-05-25 09:39 UTC, hyuk0309 commented on src/main/java/com/prgrms/hyuk/domain/user/Age.java
> +    }
좋은 피드백 감사합니다! 🙇‍♂️

저 검증 로직을 만든 이유는 사용자가 서비스에 예상하고 있지 않은 범위의 나이를 입력하는 것을 예방하기 위해서 작성했습니다! 😄

추가적으로 지웅님이 말씀하신 14세 이상의 검증 로직도 작성하면 재밌을 것 같아요!

2022-05-25 14:37 UTC, ksy90101 commented on src/main/java/com/prgrms/hyuk/controller/PostController.java
> +    @PatchMapping("/posts/{id}")
전 put이요 ㅋㅋㅋㅋ 이건 너무 많이 설명해서,,,

2022-05-26 08:48 UTC, hyuk0309 commented on src/main/java/com/prgrms/hyuk/controller/PostController.java
> +    @PatchMapping("/posts/{id}")
멘토님의 Put에 대한 생각 알려주셔서 감사합니다! 
하지만 저는 Patch가 더 맞다고 생각돼 유지하고 싶습니다! 🥲

2022-12-20 13:01 UTC, merged