[2기-C] 정다현 게시판 구현 제출합니다.
prgrms-be-devcourse/SpringBoot-Board pull request #113
Opened 2022-05-21 09:23 UTC by sdardew

## 📌 과제 설명
SpringDataJPA를 사용하 게시판 api를 구현한다.

## 👩‍💻 요구 사항과 구현 내용
- [X] SpringDataJpa를 설정한다
- [X] 엔티티를 구성한다
- [X] REST-DOCS를 이용해서 문서화한다

## ✅ PR 포인트 & 궁금한 점
User Post 관계를 연관관계를 잘 설정했는지 궁금합니다

2022-05-21 12:21 UTC, ksy90101 commented on src/main/java/com/sdardew/board/controller/api/PostController.java
> +  PostService postService;
```suggestion
  private final PostService postService;
```

2022-05-21 12:27 UTC, ksy90101 requested changes
다현님 안녕하세요!
이번 미션도 하시느라 고생 많으셨습니다 💯 
간단한 리뷰를 남겨봤어요 :)
확인해주시고, 질문이 있다면 언제든지 슬랙으로 연락주세요!

2022-05-21 12:27 UTC, ksy90101 commented on src/main/java/com/sdardew/board/controller/api/PostController.java
> +  public PostDto getPost(@PathVariable("id") Long id) {
위에서 이름이 동일하면 @PathVariable의 인자는 생력해도 되는거 아시나요!?

2022-05-21 12:27 UTC, ksy90101 commented on src/main/java/com/sdardew/board/controller/api/PostController.java
> +  public PostDto createPost(@RequestBody CreatePostDto createPostDto) {
사실 응답할때도 DTO, 요청받을떄도 DTO잖아요.
저는 그래서 Request, Response로 적긴 합니다.

2022-05-21 12:27 UTC, ksy90101 commented on src/main/java/com/sdardew/board/controller/api/PostController.java
> +  @PostMapping("/{id}")
update는 어떤 HTTP Method를 쓰는게 REST API의 규칙일까요?

2022-05-21 12:27 UTC, ksy90101 commented on src/main/java/com/sdardew/board/domain/post/CreatePostDto.java
> +  }
DTO는 어떻게 json으로 Serializer되는지 한번 알아볼까요!?

2022-05-21 12:27 UTC, ksy90101 commented on src/main/java/com/sdardew/board/domain/post/Post.java
> +  @Id
```suggestion
  @Id
  @GeneratedValue(strategy = GenerationType.AUTO)
```

이렇게 쓰는게 전 더 의미가 있더라구요.
아울러 각각의 strategy를 아실까요? 한번 알아보면 어떨까요!?

2022-05-21 12:27 UTC, ksy90101 commented on src/main/java/com/sdardew/board/domain/post/Post.java
> +  }
setter는 없애주세요 ㅠㅠ

2022-05-21 12:27 UTC, ksy90101 commented on src/main/java/com/sdardew/board/domain/post/Post.java
> +  }
도메인에서 DTO를 만들면 어떤 문제점이 있을까요?

2022-05-21 12:27 UTC, ksy90101 commented on src/main/java/com/sdardew/board/domain/post/PostDto.java
> +  private Long userId; // user 테이블과 연관
프론트는 id가 아니라 User의 정보를 알고 싶을텐데요.
이런 경우에는 어떻게 내려줄수 잇을까요?

2022-05-21 12:27 UTC, ksy90101 commented on src/main/java/com/sdardew/board/domain/post/converter/UserIdConverter.java
> +    if(userRepository.existsById(userId)) return userRepository.findById(userId).get();
젭알,,, 한줄코딩은 그만,,,

2022-05-21 12:27 UTC, ksy90101 commented on src/test/java/com/sdardew/board/service/PostServiceTest.java
> +  @Transactional
그냥 class 맨위에 Transactional을 적으면 됩니다 :) 
그러나 혹시 SpringBootTest이 테스트를 할떄 @Transactional의 롤백이 어떨때 안될수도 잇는데요.
한번 알아보실까요?

2022-05-21 12:56 UTC, sdardew commented on src/main/java/com/sdardew/board/domain/post/Post.java
> +  }
저는 getter를 사용하지 않고 도메인 내에서 바로 정보를 읽을 수 있고, 연관된 것을 묶어주기 때문에 도메인 내에서 생성해도 된다고 생각했습니다.
단순히 정보를 읽어서 DTO를 생성하는 것이기 때문에 정보 변경 문제에서는 안전하다고 생각하는데, 다른 문제는 잘 모르겠습니다!

2022-05-21 13:03 UTC, ksy90101 commented on src/main/java/com/sdardew/board/domain/post/Post.java
> +  }
일단, Dto와 Entity의 의존성이 강하게 결합될거 같아요.
아울러 과연 저 로직이 도메인 로직일까? 라는 생각도 해보세요~

2022-05-21 13:06 UTC, sdardew commented on src/test/java/com/sdardew/board/service/PostServiceTest.java
> +  @Transactional
https://stackoverflow.com/questions/46729849/transactions-in-spring-boot-testing-not-rolled-back
해당 글을 보면 웹 계층에서 직접 사용하면 적용되지 않는다고 되어 있습니다. `RANDOM_PORT` 혹은 `DEFINED_PORT`범위를 사용하면 서블릿 환경이 제공되어 롤백되지 않는다고 되어 있습니다!

2022-05-21 13:07 UTC, sdardew commented on src/main/java/com/sdardew/board/domain/post/converter/UserIdConverter.java
> +    if(userRepository.existsById(userId)) return userRepository.findById(userId).get();
Sorry... I love 한줄코딩....
한줄코딩이 버릇이라... 다 찾아내서 고치겠슴니다...

2022-05-21 13:10 UTC, sdardew commented on src/main/java/com/sdardew/board/domain/post/PostDto.java
> +  private Long userId; // user 테이블과 연관
User 정보까지 모두 내려주면 너무 많은 정보가 제공되는 것 같아 PostDto를 일부러 따로 사용했습니다.
만약 User의 모든 정보를 알려주고 싶다면 그냥 Long 대신 User 객체를 넣어서 {"user": {"key": "value"}, "title": "title" ... } 형식으로 내려주면 될 것 같습니다.

2022-05-21 13:13 UTC, sdardew commented on src/main/java/com/sdardew/board/domain/post/Post.java
> +  @Id
저는 해당 필드가 id인  정보가 더 중요하다고 생각했기 때문에 일부러 필드와 더 가까운 곳에 위치시켰습니다.
혹시 마르코님께서는 왜 해당 방법이 더 의미가 있다고 생각하시는지 여쭤봐도 될까요?
그리고 strategy는 몇개만 기억나는데, 다시 정리를 해보겠습니다!

2022-05-21 13:15 UTC, sdardew commented on src/main/java/com/sdardew/board/controller/api/PostController.java
> +  @PostMapping("/{id}")
PUT이 맞다고 생각합니다. 요구사항이 POST로 되어 있어 사용했는데, PUT으로 수정하겠습니다.

2022-05-21 13:16 UTC, sdardew commented on src/main/java/com/sdardew/board/controller/api/PostController.java
> +  public PostDto getPost(@PathVariable("id") Long id) {
명확한게 좋아서 일부러 최대한 상세하게 기입하려고 합니다!

2022-05-21 13:18 UTC, sdardew commented on src/main/java/com/sdardew/board/controller/api/PostController.java
> +  PostService postService;
🙀

2022-05-21 13:30 UTC, ksy90101 commented on src/main/java/com/sdardew/board/domain/post/PostDto.java
> +  private Long userId; // user 테이블과 연관
너무 많은 정보를 내려주는게 어떤 의미인거죠?
프론트에선 그렇다면 해당 user정보를 알고 싶다면 어떻게 해야 하는걸까요?

2022-05-21 13:30 UTC, ksy90101 commented on src/main/java/com/sdardew/board/domain/post/Post.java
> +  @Id
저는 위에서 아래로 읽힌다는 생각으로 제안드렸어요 :)

2022-05-22 13:28 UTC, Pawer0223 reviewed
고생하셨습니다. 정답이 아닌 제고민과 의견을 남겨보았습니다 !

2022-05-22 13:28 UTC, Pawer0223 commented on src/main/java/com/sdardew/board/domain/post/CreatePostDto.java
> +package com.sdardew.board.domain.post;
저는 dto와 Entity를 다른 Layer라 구분해서 별도 패키지로 관리했습니다. 어떤 방식이 좋은지 저도 잘은 모르지만 아래내용은 읽어보시면 좋을것 같습니다.
- [참조](https://medium.com/swlh/designing-a-multi-layered-architecture-for-building-restful-web-services-with-spring-boot-and-a12ef85b77c9)

2022-05-22 13:28 UTC, Pawer0223 commented on src/main/java/com/sdardew/board/domain/user/User.java
> +  private Integer age;
음수와 같은 값이 저장될 수 있을것 같아요. 유효성 검사가 있으면 좋을것 같습니다.

2022-05-22 13:28 UTC, Pawer0223 commented on src/main/java/com/sdardew/board/service/PostService.java
> +    if(found.isPresent()) return found.get().toPostDto();
저는 orElseThrow 구문을 사용해서 로직을 작성했습니다. 아래 내용 참고해보시면 좋을것 같아요
- [참조](https://homoefficio.github.io/2019/10/03/Java-Optional-%EB%B0%94%EB%A5%B4%EA%B2%8C-%EC%93%B0%EA%B8%B0/)

2022-05-22 13:28 UTC, Pawer0223 commented on src/main/java/com/sdardew/board/service/PostService.java
> +    postRepository.deleteAll();
모든 데이터를 삭제하는 로직이 Service에서 제공되니 뭔가 불안한 느낌이 드네요..
역시 정답은 모르지만 Service계층에서 해당 로직은 제거하는것을 고려해봐도 좋을것 같습니다.

2022-05-22 13:28 UTC, Pawer0223 commented on src/main/java/com/sdardew/board/service/PostService.java
> +    if(found.isEmpty()) throw new NoSuchElementException("존재하지 않는 post 입니다");
컨트롤러 호출시 NoSuchElementException 예외가 발생했을 때 응답도 처리되면 좋을것 같습니다.
강의에서 @ExceptionHandler를 통해 처리했는데, 그 방식도 좋을것 같아요 !

2022-05-22 13:28 UTC, Pawer0223 commented on src/test/java/com/sdardew/board/controller/api/PostControllerTest.java
> +      .andDo(document("find-all"));
Rest-Docs는 작성이 다 안된건가요 ?!

2022-05-22 13:28 UTC, Pawer0223 commented on src/test/java/com/sdardew/board/repository/UserRepositoryTest.java
> +    assertThat(all.size()).isEqualTo(0);
저는 delete 테스트 코드를 작성할 때 삭제된 아이디로 findById를 조회해서 결과가 isEmpty인지 확인하는 테스트 케이스를 작성했습니다. 지금 테스트 케이스도 좋지만, 추가되면 더 안정적이지 않을까 생각됩니다.

2022-05-22 13:28 UTC, Pawer0223 commented on src/test/java/com/sdardew/board/repository/UserRepositoryTest.java
> +@ExtendWith(SpringExtension.class)
ExtendWith 어노테이션이 없어도 수행되지 않나요 ?!

2022-05-22 13:28 UTC, Pawer0223 commented on src/test/java/com/sdardew/board/service/PostServiceTest.java
> +    assertThat(created.getTitle()).isEqualTo("title1");
created된 객체를 확인할 때 pk나 unique 필드로 확인하는게 더 좋지않을까 하는 의견입니다.

2022-05-22 13:28 UTC, Pawer0223 commented on src/test/java/com/sdardew/board/service/PostServiceTest.java
> +    assertThat(post.getTitle()).isEqualTo(updatePost.getTitle());
개인적으로 변경된 데이터 모두에 대해 테스트 케이스를 작성하면 더 좋을것 같습니다.

2022-05-23 05:29 UTC, yanJuicy reviewed
앞서 두분이 많이 해주셨네용.. 테스트 케이스를 더 추가해주면 좋을 것 같습니다!

2022-05-23 05:29 UTC, yanJuicy commented on src/test/java/com/sdardew/board/service/PostServiceTest.java
> +class PostServiceTest {
예외 상황에 대해서도 테스트가 있으면 좋을 것 같습니당!

2022-05-23 05:29 UTC, yanJuicy commented on src/test/java/com/sdardew/board/controller/api/PostControllerTest.java
> +class PostControllerTest {
다른 메소드 테스트도 있으면 좋을것 같습니당!

2022-05-23 05:32 UTC, sdardew commented on src/main/java/com/sdardew/board/domain/post/PostDto.java
> +  private Long userId; // user 테이블과 연관
저는 user 정보를 따로 요청하면 user id통해서 내려주려고 했습니다!
PostDto에 UserDto를 추가해서 User 정보도 같이 내려주게 변경하겠습니다!!

2022-05-23 05:36 UTC, sdardew commented on src/main/java/com/sdardew/board/domain/post/Post.java
> +  }
다른 분들은 Service 계층에서 변환하시던데 이 부분은 조금만 더 고민해보겠습니다.

2022-05-23 05:37 UTC, sdardew commented on src/main/java/com/sdardew/board/domain/post/CreatePostDto.java
> +package com.sdardew.board.domain.post;
어디 위치시킬지 많이 고민이 되었는데! 감사합니당 ~ : )

2022-05-23 05:39 UTC, sdardew commented on src/main/java/com/sdardew/board/service/PostService.java
> +    postRepository.deleteAll();
테스트를 위해서 생성한 것이긴 한데, 태산님 말씀을 듣고 보니까 그러네요! 제거하겠습니다!

2022-05-23 05:40 UTC, sdardew commented on src/test/java/com/sdardew/board/controller/api/PostControllerTest.java
> +      .andDo(document("find-all"));
부분만 작성했숨니당...

2022-05-23 05:42 UTC, sdardew commented on src/test/java/com/sdardew/board/controller/api/PostControllerTest.java
> +class PostControllerTest {
넹!

2022-05-23 05:43 UTC, sdardew commented on src/test/java/com/sdardew/board/service/PostServiceTest.java
> +    assertThat(created.getTitle()).isEqualTo("title1");
다른 정보도 잘 반영되었는지 확인하려고 했습니다!
우선 해당 부분은 조금만 더 고민해보겠습니다!

2022-05-26 10:31 UTC, sdardew commented on src/test/java/com/sdardew/board/service/PostServiceTest.java
> +    assertThat(created.getTitle()).isEqualTo("title1");
해당 부분은 save 할 때 저장되는 과정에서 ID가 새로 생성되고 생성된 객체의 ID와 데이터를 리턴 받습니다.
따라서 pk 필드로 확인하면 안 되고, 리턴 받은 id 값으로 객체를 불러와서 데이터 값을 확인한 것입니다.

2022-05-26 10:39 UTC, sdardew commented on src/main/java/com/sdardew/board/domain/post/PostDto.java
> +  private Long userId; // user 테이블과 연관
해당 PostDto는 페이징 조회할 때만 사용할 거라서 그대로 남겨두었습니다.
그리고 단건 조회할 때 UserDto를 사용해서 상세조회가 간단하도록 변경했습니다.

2022-12-20 13:02 UTC, merged