[2기-C] 스프링부트 JPA 게시판 과제 제출
prgrms-be-devcourse/SpringBoot-Board pull request #127
Opened 2022-05-21 17:25 UTC by wisehero

## 📌 과제 설명 

Spring Boot JPA - Rest API를 강의를 듣고, 게시판 구현 미션을 수행해봅시다.

## 👩‍💻 요구 사항과 구현 내용 

- 게시글 조회
    - 페이징 조회 (GET "/posts")
    - 단건 조회 (GET "/posts/{id}")
- 게시글 작성 (POST "/posts")
- 게시글 수정 (POST "/posts/{id}")
- REST-DOCS를 이용해서 문서화한다.

## ✅ PR 포인트 & 궁금한 점 

- 페이징
- API 테스트 코드
- API 문서화 적용

은 아직 못한 상태인데 계속 업데이트 하겠스빈다!

2022-05-22 01:18 UTC, ksy90101 requested changes
지웅님 안녕하세요 :)
아직 미션을 모두 완료하지 못햇지만 간단한 피드백을 남겨봣어요.
다음 리뷰 요청 때까지 미션을 모두 완료해주시면 그에 맞춰서 또 리뷰 남길게요~
질문이 있다면 언제든지 슬랙으로 연락주세요~

2022-05-22 01:18 UTC, ksy90101 commented on src/main/java/org/programmers/board/controller/BoardApiController.java
> +                        board.getUser().getName().getName()))).collect(Collectors.toList());
Jpa를 사용할땐 Eneity를 리턴하기 보단, DTO를 리턴하면 좋은데요.
그 이유를 한번 찾아보실까요!?

2022-05-22 01:18 UTC, ksy90101 commented on src/main/java/org/programmers/board/controller/BoardApiController.java
> +        return ResponseEntity.created(new URI("/posts/" + createdBoardId)).build();
URI는 정적팩토리메서드로 만드는 편입니다 :)

2022-05-22 01:18 UTC, ksy90101 commented on src/main/java/org/programmers/board/controller/BoardApiController.java
> +    @PatchMapping("/{id}")
과연 이런경우에 PAtch가 맞을까요? Put vs Patch를 한번 알아보세요~

2022-05-22 01:18 UTC, ksy90101 commented on src/main/java/org/programmers/board/controller/UserApiController.java
> +    public ResponseEntity<?> createNewMember(@RequestBody UserDTO userDTO) {
1. ?가 아닌 더 의미있는 타입으로 정의내려보실래요?
2. DTO라는 단어보단 전 Request, Response를 사용해 좀 더 명시적으로 하는거 같아요.
3. createMember가 더 어울릴거 같은데요?

2022-05-22 01:18 UTC, ksy90101 commented on src/main/java/org/programmers/board/controller/UserApiController.java
> +        return ResponseEntity.ok(response);
생성되면, created가 아닐까요?

2022-05-22 01:18 UTC, ksy90101 commented on src/main/java/org/programmers/board/dto/BoardCreateRequest.java
> +    private UserDTO userDTO;
👍

2022-05-22 01:18 UTC, ksy90101 commented on src/main/java/org/programmers/board/dto/BoardResponse.java
> +    private String userName;
좀더 객체에 맞게 
user: {
   name:
}
이렇게 내려주긴 합니다.

2022-05-22 01:18 UTC, ksy90101 commented on src/main/java/org/programmers/board/entity/BaseEntity.java
> +
updatedAt도 추가해볼까요?

2022-05-22 01:18 UTC, ksy90101 commented on src/main/java/org/programmers/board/entity/Board.java
> +    }
두개는 어차피 같이 업데이트가 되지 않을까요?
굳이 두개의 메서드일필요가 잇을까요?

2022-05-22 01:18 UTC, ksy90101 commented on src/main/java/org/programmers/board/dto/BoardCreateRequest.java
> +    private String title;
DTO에도 valdiate를 해볼까요?

2022-05-23 03:38 UTC, yanJuicy reviewed
간단히 리뷰를 남겼습니다. 멘토님이 먼저 해주셨네용..

2022-05-23 03:38 UTC, yanJuicy commented on src/main/java/org/programmers/board/entity/User.java
> +    protected User() {
protected로 해주신 이유가 뭔가용? 궁금해서 적어봅니당

2022-05-23 03:38 UTC, yanJuicy commented on src/main/java/org/programmers/board/entity/vo/Name.java
> +        System.out.println(name);
log로 바꾸는것도 좋아보입니당

2022-05-23 03:38 UTC, yanJuicy commented on src/test/java/org/programmers/board/service/BoardServiceTest.java
> +class BoardServiceTest {
예외가 발생하는 경우도 테스트 추가하면 좋아보입니다!

2022-05-23 07:42 UTC, hyuk0309 reviewed
안녕하세요! 

지웅님이 작성한 코드 재밌게 보고 가요! User API까지 만드신 것 보고 놀랐습니다! 👍
부족하지만 개인적인 의견 남겨봤어요! 

고생하셨어요! 😀

2022-05-23 07:42 UTC, hyuk0309 commented on src/main/java/org/programmers/board/controller/BoardApiController.java
> +        return ResponseEntity.created(new URI("/posts/" + createdBoardId)).build();
>This method is provided for use in situations where it is known that
>the given string is a legal URI, for example for URI constants declared
>within in a program, and so it would be considered a programming error
>for the string not to parse as such. The constructors, which throw
>{@link URISyntaxException} directly, should be used situations where a
>URI is being constructed from user input or from some other source that
>may be prone to errors.


<br/>
저도 피드백 받은 부분인데, 정적 팩토리 메서드 공식문서 읽고 도움 됐어요. 참고하시면 도움될 것 같아 남깁니다! 😀

2022-05-23 07:42 UTC, hyuk0309 commented on src/main/java/org/programmers/board/controller/BoardApiController.java
> +        Board updatedBoard = boardService.getBoard(updatedBoardId);
수정과 조회를 나누신 이유가 있으신가요? 🤔
제가 지웅님의 의도처럼 작성한다면, 개인적으로 boardService.updateBoard의 반환 값으로 Board를 넘겨줄 것 같아요!

2022-05-23 07:42 UTC, hyuk0309 commented on src/main/java/org/programmers/board/controller/UserApiController.java
> +public class UserApiController {
User API도 만드셨군요! 👍

2022-05-23 07:42 UTC, hyuk0309 commented on src/main/java/org/programmers/board/entity/Board.java
> +    @JoinColumn(name = "created_by", referencedColumnName = "user_id")
외래 키는 이름을 맞춰주는 게 관리 측면에서 더 좋지 않을까요? 🤔

2022-05-23 07:42 UTC, hyuk0309 commented on src/main/java/org/programmers/board/entity/User.java
> +    private List<Board> boards = new ArrayList<>();
이 친구를 일급 컬렉션으로 바꾸는 것도 좋을 것 같아요! 🙋‍♂️

2022-05-23 07:42 UTC, hyuk0309 commented on src/main/java/org/programmers/board/entity/Board.java
> +    public void setUser(User user) {
setter 대신 좀 더 비지니스 의미를 드러내는 네이밍은 어떠신가요? 🤔

2022-05-23 07:42 UTC, hyuk0309 commented on src/main/java/org/programmers/board/service/BoardService.java
> +@Transactional(readOnly = true)
👍

오늘 스크럼 시간에 태산님이 공유해 주신 글 읽어보면 더 좋을 것 같아요! (이미 아실 수도 있지만요. 🥲)
https://willseungh0.tistory.com/75

2022-05-23 07:42 UTC, hyuk0309 commented on src/main/java/org/programmers/board/service/UserService.java
> +    public Optional<User> getUser(Long userId) {
요기는 예외 처리를 잊으신 것 같아요! 🤔

2022-05-23 07:42 UTC, hyuk0309 commented on src/test/java/org/programmers/board/repository/BoardRepositoryTest.java
> +    User user;
private 접근 제어자를 사용하면 좋을 것 같아요! 🙋‍♂️

2022-05-23 07:42 UTC, hyuk0309 commented on src/test/java/org/programmers/board/repository/BoardRepositoryTest.java
> +    @DisplayName("게시글 저장 실패 - 사유: 빈 제목")
해당 테스트는 Title VO에서 단위 테스트로 진행하는 게 더 빠른 테스트가 되지 않을까요? 🤔

2022-05-23 07:42 UTC, hyuk0309 commented on src/test/java/org/programmers/board/service/BoardServiceTest.java
> +@SpringBootTest
Controller, Service, Repository를 모두 테스트하는 게 아니면, SpringBootTest는 개인적으로 테스트를 느리게 만들어 사용하지 않는 게 좋은 것 같아요! 🙋‍♂️

2022-05-23 13:19 UTC, wisehero commented on src/main/java/org/programmers/board/entity/User.java
> +    protected User() {
@yanJuicy JPA 엔티티는 기본 생성자를 요구하는데 기본 생성자의 접근제어자는 Public 혹은 protected만 가능합니다. 안정성적인 측면에서 public보다는 protected가 좋은 것 같아서 protected로 했습니다.

자세한 내용은 https://hyeonic.tistory.com/191 참고하시면 될 것 같아요!

2022-05-23 13:20 UTC, wisehero commented on src/main/java/org/programmers/board/entity/vo/Name.java
> +        System.out.println(name);
@yanJuicy  NPE가 나던걸 추적하려고 넣은 거였는데 실수로 못지웠네요 ㅠㅠ

2022-05-23 13:30 UTC, wisehero commented on src/main/java/org/programmers/board/controller/BoardApiController.java
> +        Board updatedBoard = boardService.getBoard(updatedBoardId);
@hyuk0309 아직 반환타입을 정해주는 것에 있어서 여러 예시를 참고하다보니 조금 뒤죽박죽인 것 같아요. 한번에 Board를 넘겨주는 것이 낫겠네요!

2022-05-23 13:32 UTC, wisehero commented on src/main/java/org/programmers/board/entity/Board.java
> +    @JoinColumn(name = "created_by", referencedColumnName = "user_id")
@hyuk0309 게시글을 누가 작성했는 지를 한번에 보기 편할려고 '의미'에 포커스를 두고 네이밍을 했는데 관리 측면에서는 생각 못해본 것 같습니다. 좋은 지적 감사합니다!

2022-05-23 13:37 UTC, wisehero commented on src/main/java/org/programmers/board/entity/Board.java
> +    public void setUser(User user) {
@hyuk0309 연관관계 편의 메소드의 경우 애플리케이션 전반에 중요도가 크지 않아 네이밍은 크게 상관없다고 생각했습니다!

2022-05-23 14:47 UTC, wisehero commented on src/main/java/org/programmers/board/controller/BoardApiController.java
> +                        board.getUser().getName().getName()))).collect(Collectors.toList());
@ksy90101 API 스펙에 따라 필요한 정보만 내릴 수 있어서 성능에 대한 이점을 얻을 수 있고 엔티티를 직접 UI 계층에 노출하지 않으므로서 의존성이 생기는 문제를 막고 검증 코드와 모델링 코드를 구분할 수 있다는 점 때문에 DTO를 리턴합니다!

2022-05-28 17:23 UTC, wisehero commented on src/main/java/org/programmers/board/controller/BoardApiController.java
> +    @PatchMapping("/{id}")
@ksy90101 다른 분들과 동일하게 저도 아직은 PATCH가 맞는것 같습니다. 이 부분에 대해서는 좀 더 고려해보겠습니다!

2022-05-29 07:27 UTC, ksy90101 commented on src/main/java/org/programmers/board/controller/BoardApiController.java
> +public class BoardApiController {
예외처리를 위해 CotnrollerAdvice를 추가해볼까요?

2022-05-29 07:27 UTC, ksy90101 commented on src/main/java/org/programmers/board/controller/BoardApiController.java
> +    private final Logger log = LoggerFactory.getLogger(BoardApiController.class);
상수는 static final로 사용해주시면 좋을거 같고 순서를 맞춰주세요.

2022-05-29 07:28 UTC, ksy90101 commented on src/main/java/org/programmers/board/controller/BoardApiController.java
> +                        board.getUser().getName().getName()
생성하는 것 자체가 중복이네요.
이런경우에는 가장 쉬운방법은 controller에 메서드를 만드는방법이 있겟죠.
아울러 직므같이 서비스에서 eneity를 리턴하면 어떤 단점이 잇을까요?

2022-05-29 07:28 UTC, ksy90101 commented on src/main/java/org/programmers/board/controller/BoardApiController.java
> +        log.info("{}", board.getId());
id를 로그로 찍어놓는게 의미가 잇나요?

2022-05-29 07:29 UTC, ksy90101 commented on src/main/java/org/programmers/board/controller/BoardApiController.java
> +        return ResponseEntity.status(HttpStatus.CREATED).body(boardResponse);
created 메서드도 있어요!

2022-05-29 07:29 UTC, ksy90101 commented on src/main/java/org/programmers/board/controller/UserApiController.java
> +    public ResponseEntity<?> removeUser(Long userId) {
내려줄값이 없다면 타입은 Void가 더 좁은 범위겠네요 :)

2022-05-29 07:30 UTC, ksy90101 commented on src/main/java/org/programmers/board/entity/vo/Name.java
> +        if (name.length() > 15) {
매직넘버!

2022-05-29 07:30 UTC, ksy90101 commented on src/main/java/org/programmers/board/entity/vo/Name.java
> +        if (name.isBlank()) {
name이 공백일때 이 로직을 탈까요?

2022-05-29 07:30 UTC, ksy90101 commented on src/main/java/org/programmers/board/exception/NoBoardException.java
> +}
```suggestion
    }
}
```

2022-05-29 07:31 UTC, ksy90101 requested changes
피드백을 좀 더 남겼는데 마지막 피드백이 될거 같네요 :)
확인해주세요~

2022-06-02 05:43 UTC, wisehero commented on src/main/java/org/programmers/board/entity/vo/Name.java
> +        if (name.isBlank()) {
@ksy90101 타지...않나요??!!

2022-06-02 05:45 UTC, wisehero commented on src/main/java/org/programmers/board/controller/UserApiController.java
> +    public ResponseEntity<?> removeUser(Long userId) {
@ksy90101 감사합니다. 이런 경우에 <>안에 뭘 넣어야되는지를 몰랐는데 해결됐네요!

2022-06-02 06:27 UTC, wisehero commented on src/main/java/org/programmers/board/controller/BoardApiController.java
> +        log.info("{}", board.getId());
@ksy90101 실수로 안지웠습니다 ㅠ !

2022-06-02 06:28 UTC, wisehero commented on src/main/java/org/programmers/board/controller/BoardApiController.java
> +        return ResponseEntity.status(HttpStatus.CREATED).body(boardResponse);
@ksy90101 넵 근데 URI 사용해서 하는 것보다는 저게 익숙해서 저렇게 했습니다!

2022-06-04 16:31 UTC, wisehero commented on src/main/java/org/programmers/board/controller/BoardApiController.java
> +                        board.getUser().getName().getName()
@ksy90101 서비스에서 엔티티를 리턴했을 때는 OSIV 이슈가 있고, 컨트롤러의 변경을 촉발하는 유지보수 문제를 일으키는 것 같습니다. 상황에 따라 유연하게 선택할 수 있는 열린결말의 부분이기는 한데... 마틴 파울러의 의견을 곰곰이 생각해보니 entity 서비스에서 DTO를 받고 DTO를 리턴하는게 좋을 수 있겠다는 생각이 듭니다!

2022-06-05 04:49 UTC, ksy90101 commented on src/main/java/org/programmers/board/entity/vo/Name.java
> +        if (name.isBlank()) {
위의 로직이 있다면 아래 로직은 안탈꺼 같은데요 :)

2022-06-05 04:49 UTC, ksy90101 commented on src/main/java/org/programmers/board/entity/vo/Name.java
> +        if (name.isBlank()) {
정확한 방법은 테스트 코드를 작성해보는거같아요.

2022-12-20 13:02 UTC, merged