[2기-C]이한주 JPA 게시판 구현 미션 제출
prgrms-be-devcourse/SpringBoot-Board pull request #138
Opened 2022-05-22 14:47 UTC by yanJuicy

## 📌 과제 설명 
게시판 구현

## 👩‍💻 요구 사항과 구현 내용 
### API를 구현한다.
- 게시글 조회
    - 페이징 조회 (GET "/posts")
    - 단건 조회 (GET "/posts/{id}")
- 게시글 작성 (POST "/posts")
- 게시글 수정 (POST "/posts/{id}")

### REST-DOCS를 이용해서 문서화한다.

2022-05-23 07:42 UTC, Pawer0223 reviewed
고생하셨습니다. 정답이 아닌 제 고민과 의견을 남겨보았습니다 !

2022-05-23 07:42 UTC, Pawer0223 commented on src/main/java/me/prgms/board/domain/BaseEntity.java
> +public class BaseEntity {
저는 공통처리는 Embedeed, 분류는 MappedSuperclass와 같은 역할이 더 어울린다 생각하여 createdBy, createdAt을 Embedeed로 정의해보았습니다. 한주님은 어떤기준으로 공통필드를 BaseEntity로 작성하신건지 궁금합니다 !

2022-05-23 07:42 UTC, Pawer0223 commented on src/main/java/me/prgms/board/domain/User.java
> +        super("createdBy-yanju", LocalDateTime.now());
- 하드코딩에 대한 내용을 참조해보시면 좋을것 같습니다 !
    - [참조](https://tecoble.techcourse.co.kr/post/2020-05-07-avoid-hard-coding/)

2022-05-23 07:42 UTC, Pawer0223 commented on src/main/java/me/prgms/board/domain/post/Content.java
> +    public Content() {}
기본 생성자가 단순히 JPA 사용시 프록시 객체를 위해 정의된 것이라면 protected가 더 좋을것 같습니다 !

2022-05-23 07:42 UTC, Pawer0223 commented on src/main/java/me/prgms/board/domain/User.java
> +    private int age;
음수가 들어올 수 도 있을것 같습니다. 유효성 검사를 하면 좋을것 같아요 !

2022-05-23 07:42 UTC, Pawer0223 commented on src/main/java/me/prgms/board/domain/post/Post.java
> +        this.user = user;
생성자에서 User정보가 전달안되면 NPE가 발생할것 같은데요.. 이게 정답인지는 모르겠지만, 저는 null인경우 빈 Entity를 생성하도록 했습니다.

2022-05-23 07:42 UTC, Pawer0223 commented on src/main/java/me/prgms/board/domain/post/Title.java
> +        if (title.length() > 50) {
매직넘버 !
개인적으로 50이라는 숫자가 변경되면, 에러메시지에 포함 된 50도 영향을 받기 때문에, 상수로 관리했습니다

2022-05-23 07:42 UTC, Pawer0223 commented on src/main/java/me/prgms/board/post/service/PostService.java
> +    public ResponsePostDto findPostById(Long postId) {
@Transactional이 없어도 괜찮나요?

2022-05-23 07:42 UTC, Pawer0223 commented on src/test/java/me/prgms/board/SpringbootBoardJpaApplicationTests.java
> +class SpringbootBoardJpaApplicationTests {
사용되지 않는 테스트코드는 삭제해도 좋을것 같습니다 !

2022-05-23 07:42 UTC, Pawer0223 commented on src/test/java/me/prgms/board/post/contoller/PostControllerTest.java
> +        CreatePostDto postDto = new CreatePostDto("test-title", "", userDto);
여기서 테스트하는 항목은 Converter에서 Entity객체로 변환되는 과정에서 발생하는 에러로 보입니다.
컨트롤러 Layer에서 해당 테스트 케이스를 작성하는것보다 Entity에 대한 단위 테스트를 별도로 작성하는것이 더 좋을것 같다는 의견입니다.
(제목, 게시글 등등..)

2022-05-23 07:42 UTC, Pawer0223 commented on src/test/java/me/prgms/board/post/service/PostServiceTest.java
> +@Import({PostService.class, PostConverter.class})
오! 이런방법이 있었군요

2022-05-23 14:45 UTC, ksy90101 commented on src/main/java/me/prgms/board/domain/User.java
> +    private List<Post> posts = new ArrayList<>();
연습겸 한번 1급 컬렉션으로 만들어 볼까요

2022-05-23 14:52 UTC, ksy90101 requested changes
한주님 :) 미션하시느라 너무 고생 많으셨습니다 💯 
간단한 피드백을 남겼으니 참고해주세요~

2022-05-23 14:52 UTC, ksy90101 commented on src/main/java/me/prgms/board/domain/post/Post.java
> +        this.content.setContent(content);
이두개는 같이 변경되지 않을까요?

2022-05-23 14:52 UTC, ksy90101 commented on src/main/java/me/prgms/board/post/contoller/PostController.java
> +    }
생성자는 더 위에!

2022-05-23 14:52 UTC, ksy90101 commented on src/main/java/me/prgms/board/post/contoller/PostController.java
> +    }
exceptionHandler는 따로 뺴주시는게 좋을거 같아요.

2022-05-23 14:52 UTC, ksy90101 commented on src/main/java/me/prgms/board/post/contoller/PostController.java
> +    public ResponseEntity<Long> save(@RequestBody CreatePostDto postDto) {
Dto라는 단어보다 좀 더 명시적으로 Request, Response로 작성하는게 더 좋더라구요.

2022-05-23 14:52 UTC, ksy90101 commented on src/main/java/me/prgms/board/post/dto/CreatePostDto.java
> +    public void setTitle(String title) {
setter는 필요 없어요.
한번 Spring이 json을 어떻게 직렬화 하는지 알아볼까요?

2022-05-23 14:52 UTC, ksy90101 commented on src/main/java/me/prgms/board/post/service/PostService.java
> +
공통 valdiate 로직 같은데 메서드로 분리해보면 어떨까요?

2022-05-26 05:31 UTC, yanJuicy commented on src/main/java/me/prgms/board/domain/BaseEntity.java
> +public class BaseEntity {
저번에 스크럼 때 이야기한 것처럼 모든 엔터티 클래스에서 사용해서 상속을 이용했습니다!

2022-05-26 05:31 UTC, yanJuicy commented on src/main/java/me/prgms/board/domain/User.java
> +        super("createdBy-yanju", LocalDateTime.now());
생성자에 직접 문자열을 넣는것도 하드코딩이었군요!

2022-05-26 05:32 UTC, yanJuicy commented on src/main/java/me/prgms/board/domain/post/Post.java
> +        this.user = user;
null이 들어오는 경우는 생각을 못했네요. 감사합니다!

2022-05-26 05:49 UTC, yanJuicy commented on src/main/java/me/prgms/board/post/service/PostService.java
> +    public ResponsePostDto findPostById(Long postId) {
Read 작업에는 트랜잭션이 필요없지 않나요?
저는 C,U,D 작업에만 필요하다고 생각해서 넣진 않았습니다!

2022-05-26 05:53 UTC, yanJuicy commented on src/main/java/me/prgms/board/domain/post/Post.java
> +        this.content.setContent(content);
아 그렇네요. 한 메소드로 묶겠습니다!

2022-05-26 05:54 UTC, yanJuicy commented on src/main/java/me/prgms/board/post/service/PostService.java
> +
아직 공통처리를 빼는게 습관이 안됐네요.. 하나로 묶겠습니다!

2022-05-26 16:20 UTC, Pawer0223 commented on src/main/java/me/prgms/board/post/service/PostService.java
> +    public ResponsePostDto findPostById(Long postId) {
아, 우선 현재 한주님 코드에서는 문제가 없네요..
다만 @Transactional을 붙이지않으면 지연로딩 관해서 LazyInitializationException이 발생할 수 있습니다.
(EntityManager에의해 관리되지 못하기 때문인것 같습니다.)
그래서 Jpa사용시 Read작업에는 `@Transactional(readonly=true)` 옵션을 주는것이 안전할것 같다는 의견입니다 !

- [참조](https://dundung.tistory.com/238)
- [참조](https://gmlwjd9405.github.io/2019/08/06/persistence-context.html)

2022-05-27 02:22 UTC, wisehero commented on src/main/java/me/prgms/board/domain/User.java
> +    public User() {}
아무대서나 생성하는걸 막기 위해 protected로 하는 것이 좋아보입니다!

2022-05-27 02:24 UTC, wisehero commented on src/main/java/me/prgms/board/post/converter/PostConverter.java
> +    }
컨버터 클래스를 정말 깔끔하게 작성해주셨네요. 저도 보고 배웁니다!

2023-06-05 18:45 UTC, closed without merging