[2기-P] 김형욱 SpringBoot-Board-JPA 미션 제출합니다.
prgrms-be-devcourse/SpringBoot-Board pull request #163
Opened 2022-06-04 00:00 UTC by HyoungUkJJang

## 작업 단위

- [x] Entity
  - [x] Post
  - [x] User
- [x] Repository
  - [x] Post
- [x] Service
  - [x] Post
- [x] Controller / ControllerAdvice 
  - [x] Post
- [ ] Test
  - [x] Unit Test 
  - [x] Repository Test
  - [ ] Service Test
  - [ ] Controller Test

## 작업 사항

* PostController를 통해 작성자 정보를 함께 받아 데이터가 저장되도록 만들어 봤습니다.
  * 개인적인 생각으로 비회원 게시글 작성하는 느낌? 으로 진행해서 강의와 유사하게 cascade를 ALL을 사용해서 기능을 구현했는데 블로그를 여러곳을 보니까 ALL 사용하면 발생할 수 있는 문제점들이 좀 있었던 것 같습니다. 
  * UserRepository / Service 를 따로 분리하도록 다시 개선시키도록 하겠습니다.

## 궁금했던 부분

* 엘레강트 오브젝트를 읽으면서 생성자에 코드를 넣지 말라는 챕터가 있었는데 이 부분에서 도메인을 검증하는 코드도 해당 챕터 내용에 포함이 되는 건지 궁금했습니다. 
* 제가 이해한 바로는 초기화하는 인자값들에 대해 변경하거나 조작하는 행위를 하는 코드를 작성하면 안된다 라는 의미로 이해를 했었습니다. 책의 모든 내용이 정답은 아니겠지만 만약 검증하는 코드도 내용에 포함된다면 다른 어떤 방법이 있는지 궁금했습니다.
  * 만약 검증하는 코드도 책에서 말하는 내용에 포함이 된다면 값이 넘어오는 DTO에서 유효성 검증을 자세히 처리해야 할 것 같은데 그렇게 된다면 멘토님께서 말씀해주셨던 DTO 중심의 개발이 되버리는 것은 아닐지 생각이 들었습니다.

2022-06-04 04:18 UTC, Jo-GyuHyeon commented on src/main/java/com/prgrms/work/controller/PostRestController.java
> +@RequestMapping("/api/v1/post")
restful 한 엔드포인트는 리소스를 복수형으로 대개 표현합니다.

2022-06-04 04:18 UTC, Jo-GyuHyeon commented on src/main/java/com/prgrms/work/controller/PostRestController.java
> +    public ApiResponse<Object> write(@RequestBody @Validated PostRequest.PostCreateDto createDto) {
@Valid 가 아닌 @Validated 에노테이션을 사용한 이유는 무엇인가요?

2022-06-04 04:18 UTC, Jo-GyuHyeon commented on src/main/java/com/prgrms/work/user/domain/User.java
> +    private static void verifyValid(String name) {
이름에 대한 검증이라는 의미를 알 수 있도록 하는 네이밍이였으면 더 좋을 것 같습니다.

2022-06-04 06:34 UTC, HYEBPARK commented on src/main/java/com/prgrms/work/controller/PostErrorController.java
> +        return ApiResponse.fail("해당 게시글을 찾을 수 없습니다.", HttpStatus.NOT_FOUND);
ResponseStatus 어노테이션과 ApiResponse 두 군데에서 상태 코드를 넘겨주시는 이유가 있으실까요?

2022-06-04 07:28 UTC, HYEBPARK reviewed
형욱님 ~ 수고하셨습니당 😊
++ 우와 엔티티 부분 보면서 Create라는 static 메서드를 따로 만드셨길래 책 내용이 딱 떠올랐는데 
그 부분을 적용하신게 맞군요 👍

2022-06-04 07:28 UTC, HYEBPARK commented on src/main/java/com/prgrms/work/controller/PostErrorController.java
> +        return ApiResponse.fail("해당 게시글을 찾을 수 없습니다.", HttpStatus.NOT_FOUND);
ResponseStatus 어노테이션과 ApiResponse 두 군데에서 상태 코드를 넘겨주시는 이유가 있으실까요?

2022-06-04 07:28 UTC, HYEBPARK commented on src/main/java/com/prgrms/work/post/domain/Post.java
> +    long id;
id 값에 Wrapper 타입을 사용하는 이유에 대해 찾아보면 좋을 것 같습니당
[백기선님 인프런 질문](https://www.inflearn.com/questions/35759) 
해당 링크 이외에도 JPA id Long 이라고 검색하면 자료가 나오더라구요 ! 
(private 빠져있어요! )

2022-06-04 07:28 UTC, HYEBPARK commented on src/main/java/com/prgrms/work/controller/dto/PostRequest.java
> +        private String title;
Valid 하는 김에 NotNull 이외에도  length도 넣어주면 좋지 않을까용 ? 😊
엔티티에서 length 옵션을 주셨더라구요 !

2022-06-04 07:28 UTC, HYEBPARK commented on src/main/java/com/prgrms/work/controller/dto/PostRequest.java
> +    public static class PostCreateDto {
PostRequest.CreateDto 로 줄여도 읽기 편할 것 같아요 ㅎㅎ

2022-06-04 13:27 UTC, HYEBPARK commented on src/main/java/com/prgrms/work/common/BaseEntity.java
> +    @CreatedBy
Auditing기능을 사용하지 않으시는 것 같은데 해당 어노테이션을 달아두신 이유가 있으실까용 ? 🤔

2022-06-05 13:41 UTC, pjh612 reviewed
고생하셨습니다. 도움이 될진 모르겠지만 소소한 코멘트 남겼습니다~

2022-06-05 13:41 UTC, pjh612 commented on src/main/java/com/prgrms/work/controller/PostRestController.java
> +    public ApiResponse<List<Posts>> getPosts() {
과제 요구사항에 페이징이 있을텐데 페이징을 사용해보시죠!

2022-06-05 13:41 UTC, pjh612 commented on src/main/java/com/prgrms/work/controller/PostErrorController.java
> +        return ApiResponse.fail("해당 게시글을 찾을 수 없습니다.", HttpStatus.NOT_FOUND);
PostNotFoundException에서 해당 예외를 생성할때 메시지를 하드코딩하셨던데 그러면 e.getMessage()로 가져와도 되지않나요? 중복때문에 유지보수가 버거워질 수도 있을것 같습니다

2022-06-05 13:41 UTC, pjh612 commented on src/main/java/com/prgrms/work/controller/PostErrorController.java
> +        return ApiResponse.fail(e.getMessage(), HttpStatus.BAD_REQUEST);
IllegalArgumentException은 무조건 도메인 유효성 검사에서만 발생하나요? 지금까지 봐서는 해당 애플리케이션에서는 도메인 유효성 검사를 할때만 발생할 것 같긴한데 아무래도 표준 예외다보니까 도메인 유효성 검사가 아닌 곳에서도 종종 발생할 것 같아서 과연 적절한 네이밍인가 의심스럽습니다! (기타 라이브러리를 추가하여 사용한다던가 하면 점점 혼란이 늘어날 수 있을것 같습니다)

2022-06-05 13:41 UTC, pjh612 commented on src/test/java/com/prgrms/work/post/domain/PostTest.java
> +class PostTest {
실패에 대한 테스트도 추가되면 좋을 것 같습니다!

2022-06-05 15:02 UTC, whyWhale requested changes
진형님 말씀대로 실패에 대한 예외 테스트도 짜보시면 좋을 것 같슴둥 👍🏼 

수고하셨습니 🥕  !

2022-06-05 15:02 UTC, Onigiriiiiiiii commented on src/main/java/com/prgrms/work/controller/dto/MemberRequest.java
> +import com.prgrms.work.user.domain.User;
컨벤션 적용하시면 좋을 것 같슴둥!

2022-06-05 15:02 UTC, Onigiriiiiiiii commented on src/main/java/com/prgrms/work/controller/dto/MemberRequest.java
> +        private String name;
String @NotNull 애노테이션은 이러한 [ -> "" , " "]에도 값이 허용될수 있어서 @NotEmpty를 쓰시면 좋을 것 같슴둥 👍🏼

2022-06-05 15:02 UTC, Onigiriiiiiiii commented on src/main/java/com/prgrms/work/controller/dto/PostResponse.java
> +        public static PostDetail of(Post post) {
client에게 줄 dto에게 Post라는 entity를 알게 하는 것이 layer가 깨져보이는데 어떻게 생각하시나용 ⁉️

2022-06-05 15:02 UTC, Onigiriiiiiiii commented on src/main/java/com/prgrms/work/post/domain/Post.java
> +    @ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.ALL)
게시판이 삭제되면서 연쇄적으로 회원이 삭제될 것 같은데 테스트 해보셧나용 ⁉️

2022-06-05 15:02 UTC, Onigiriiiiiiii commented on src/main/java/com/prgrms/work/post/domain/Post.java
> +    public Post(String createdBy, String title, String content, User user) {
정적 팩토리 메서드 패턴을 사용하셧는데 생성자 접근제한자를 public으로 하신 이유가 있으신가요 ⁉️

2022-06-07 01:13 UTC, midasWorld approved these changes
고생하셨습니다! 👍
팀원 분들이 다 작성을 해주셔서, 제가 따로 적을게 없네요.. ㅎㅎ

2022-06-10 19:12 UTC, HyoungUkJJang commented on src/main/java/com/prgrms/work/controller/PostRestController.java
> +    public ApiResponse<Object> write(@RequestBody @Validated PostRequest.PostCreateDto createDto) {
특별한 이유가 있진 않았습니다..! 스프링에서 제공해주기 때문에 Validated를 적용해도 괜찮다고 생각했습니다..!

2022-06-10 19:12 UTC, HyoungUkJJang commented on src/main/java/com/prgrms/work/controller/PostErrorController.java
> +        return ApiResponse.fail("해당 게시글을 찾을 수 없습니다.", HttpStatus.NOT_FOUND);
맞는 말씀이십니다 ! 반영하겠습니다 !

2022-06-10 19:13 UTC, HyoungUkJJang commented on src/main/java/com/prgrms/work/common/BaseEntity.java
> +    @CreatedBy
앗 추가하도록 하겠습니다.!

2022-06-10 19:14 UTC, HyoungUkJJang commented on src/main/java/com/prgrms/work/controller/PostErrorController.java
> +        return ApiResponse.fail(e.getMessage(), HttpStatus.BAD_REQUEST);
넵 커스텀한 예외가 있는게 좋을 것 같습니다 ! 반영하도록 하겠습니다 !

2022-06-10 19:15 UTC, HyoungUkJJang commented on src/main/java/com/prgrms/work/post/domain/Post.java
> +    @ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.ALL)
넵 저는 비회원 게시글의 방향으로 작성을 했기 때문에 ALL로 설정하였습니다 !

2022-06-10 19:16 UTC, HyoungUkJJang commented on src/main/java/com/prgrms/work/controller/dto/PostResponse.java
> +        public static PostDetail of(Post post) {
converter도 좋지만 dto에서 변환해주는 방법도 괜찮다고 생각이 들었습니다 :)

2022-06-10 19:21 UTC, HyoungUkJJang commented
## 작업 사항
* 전체적으로 코드리뷰 남겨주신 부분을 반영하였습니다.
  * Post, User 엔티티 id 래퍼타입, 검증 메서드 네이밍 수정
  * EintityInvalidException 커스텀 예외 추가 및 예외처리 메시지 전달 방법 수정
  * PostService, PostController 게시글 전체조회 Page 타입으로 수정
  * Post, User 유닛 테스트 실패 케이스 작성
  * PostServiceTest 코드 작성

* PostServiceTest 코드를 BDDMockito를 사용하여 Nested로 작성을 한번 해봤습니다..! DCI 패턴을 적용해 보고 싶어서 작성을 해봤는데 테스트가 올바른지 잘 작성된 것인지 모르겠습니다 ㅠ
* 컨트롤러 테스트코드도 작성해서 Push하도록 하겠습니다 !

2022-12-08 03:01 UTC, merged