[3기-C 박세준] JPA 게시판 구현 미션 제출합니다.
prgrms-be-devcourse/SpringBoot-Board pull request #174
Opened 2022-12-19 04:56 UTC by rhdtn311

## 📌 과제 설명
JPA 게시판 구현 미션 과제입니다.

## 👩‍💻 요구 사항과 구현 내용
### **엔티티를 구성한다**

- 회원(User)

     id (PK) (auto increment)
    - [x] name
    - [x] age
    - [x] hobby
    - [x] created_at
    - [x] created_by -> modified_at 으로 대체하였습니다.
- 게시글(Post)
    - [x] id (PK) (auto increment)
    - [x] title
    - [x] content
    - [x] created_at
    - [x] created_by
- [x] 회원과 게시글에 대한 연관관계를 설정한다.
    - [x] 회원과 게시글은 1:N 관계이다.
- [x] 게시글 Repository를 구현한다. (PostRepository)

### **API를 구현한다.**

- [x] 게시글 조회
    - [x] 페이징 조회 (GET "/posts")
    - [x] 단건 조회 (GET "/posts/{id}")
- [x] 게시글 작성 (POST "/posts")
- [x] 게시글 수정 (POST "/posts/{id}")

### **REST-DOCS를 이용해서 문서화한다.** ✅

## ✅ PR 포인트 & 궁금한 점
- Post에서만 쓰는 User의 정보(UserXXXDTO)를 Post 패키지에서 관리하는 것이 좋을까요 User 패키지에서 관리하는 것이 좋을까요?

## 실행 방법
- 간단한 Post 엔티티의 CRUD를 구현하였습니다. 
- API의 요청과 응답 확인은 src/main/resources/static/docs에 html파일로 저장되어있습니다.
  - 화면이나 콘솔은 없어서 애플리케이션 실행에 대한 DB 설정은 따로 작성하지 않았습니다.
- test 코드 작성했습니다.

2022-12-23 01:50 UTC, thguss reviewed
수고 많으셨습니다! 여러모로 좋은 코드 보고 많이 배워 가서 너무 감사하네요 👍
단순 궁금한 점, 배워간 점, 개인적 의견을 제시한 점 3가지로 나눠 코드 리뷰 했는데 필터링 해서 잘 봐주세요 ㅎㅁㅎ !! 이해 안가거나 반박할 글 있으면 마구마구 리코멘트 달아주세요!!!!

2022-12-23 01:50 UTC, thguss commented on src/main/java/com/devcourse/springbootboardjpa/common/dto/CommonResponse.java
> +public class CommonResponse<T> extends ResponseDTO {
ErrorResponse 파일 내용과 합쳤어도 좋았을 것 같은데 분리한 이유가 있을까요?? 단순히 궁금해요!

2022-12-23 01:50 UTC, thguss commented on src/main/java/com/devcourse/springbootboardjpa/common/dto/page/PageDTO.java
> +public class PageDTO {
PageDTO를 따로 구현하셨네요! Pageable 를 이용해서 Pagination 처리할 수도 있으니 이것도 사용해보시면 좋을 것 같아요 :)

2022-12-23 01:50 UTC, thguss commented on src/main/java/com/devcourse/springbootboardjpa/common/exception/BusinessException.java
> +public class BusinessException extends RuntimeException {
예외 다른 객체로 뺀 거 배워갑니다,, 깔끔하네용

2022-12-23 01:50 UTC, thguss commented on src/main/java/com/devcourse/springbootboardjpa/common/exception/ErrorCode.java
> +public enum ErrorCode {
enum으로 뺀 거 깔끔하고 좋은 것 같아요~! 뺀 김에 ErrorCode에는 에러 코드만 넣고(400, 404 등), 에러 메시지는 ErrorMessage라는 enum으로 따로 빼는 것은 어떻게 생각하시나요??

2022-12-23 01:50 UTC, thguss commented on src/main/java/com/devcourse/springbootboardjpa/common/exception/post/PostNotFoundException.java
> +public class PostNotFoundException extends BusinessException {
별도의 예외 처리 폴더로 구분한 이유가 있을까요?? 단순 궁금해요!

2022-12-23 01:50 UTC, thguss commented on src/main/java/com/devcourse/springbootboardjpa/post/controller/PostController.java
> +        Long postId = postService.savePost(saveRequest);
개인적으로 객체 저장 후 객체 모든 정보를 반환하는 것을 선호하는 입장인데, 모든 정보를 반환하는 것은 어떻게 생각하시나요?? 모든 정보를 줘야할 지, 객체 고유 id만 줘야할 지 고민이 되더라구요

2022-12-23 01:50 UTC, thguss commented on src/main/java/com/devcourse/springbootboardjpa/post/controller/PostController.java
> +public class PostController {
Mapping 공통적으로 "/posts"가 포함되어있는 것 같아서 RequestMapping("/posts")로 라우터 지정해도 좋을 것 같아요!

2022-12-23 01:50 UTC, thguss commented on src/main/java/com/devcourse/springbootboardjpa/post/controller/PostController.java
> +    @GetMapping("/posts/{id}")
개인적으로 id 보다는 postId와 같은 직관적인 변수명을 선호하는데 어떻게 생각하시나요?

2022-12-23 01:50 UTC, thguss commented on src/main/java/com/devcourse/springbootboardjpa/post/domain/Post.java
> +    public void changeTitle(String title) {
setter 대신 changeTitle 메서드로 빼낸 거 배워갑니다,, 끄적

2022-12-23 01:50 UTC, thguss commented on src/main/java/com/devcourse/springbootboardjpa/post/domain/dto/PostDTO.java
> +public class PostDTO {
오호 공통된 객체 DTO를 한 클래스로 묶는 방법도 있군요!! 저는 DTO를 분리했는데 어느 게 더 좋은 방식일까요?? 이것 또한 단순 궁금한 점입니다!

2022-12-23 01:50 UTC, thguss commented on src/main/java/com/devcourse/springbootboardjpa/post/service/PostService.java
> +    public PageDTO.Response<Post, PostDTO.FindResponse> findAllPostsPage(PageDTO.Request pageRequest) {
여기서 PageDTO도 좋지만 Pageable을 사용하면 더 수월하다고 위에서 말씀드린 의미였어요~! 혹시 의도적으로 따로 DTO를 만드신 거라면 왜 Pageable을 별도로 사용하지 않았는지도 궁금해요!

2022-12-23 01:50 UTC, thguss commented on src/main/java/com/devcourse/springbootboardjpa/user/domain/User.java
> +    private String hobby;
지극히 개인적으로 String 대신 Hobby라는 별도 클래스를 만들어보시는 건 어떤가요! (강의에서 hobby라는 칼럼을 제시한 이유가 클래스를 가지는 칼럼도 만들어보라는 의미로 해석했거든요! 물론 아닐 수도 있지만 ㅎㅁㅎ)

2022-12-23 01:50 UTC, thguss commented on src/main/java/com/devcourse/springbootboardjpa/user/domain/User.java
> +    private Integer age;
int 대신 Integer 타입을 사용한 이유도 궁금합니다!

2022-12-23 01:50 UTC, thguss commented on src/main/java/com/devcourse/springbootboardjpa/user/domain/User.java
> +    private List<Post> posts = new ArrayList<>();
addPost 메서드는 따로 구현하지 않은 이유가 있을까요 ?~?

2022-12-23 01:50 UTC, thguss commented on src/test/java/com/devcourse/springbootboardjpa/post/controller/PostControllerTest.java
> +class PostControllerTest {
given then when 으로 잘 나누셨네요! 배워갑니다,,,

2022-12-23 01:50 UTC, thguss commented on src/test/java/com/devcourse/springbootboardjpa/post/controller/PostControllerTest.java
> +                        pathParameters(
파라미터 관련 진짜 고민하고 있었는데 pathParameters로 다시 찾아보고 시도해봐야겠네요,, 감사합니다!

2022-12-23 01:50 UTC, thguss commented on src/test/java/com/devcourse/springbootboardjpa/post/controller/PostControllerTest.java
> +class PostControllerTest {
Mock 활용해서 테스트 코드도 전체적으로 잘 짜신 것 같아 대단해요!! 배움 ㅠㅠ

2022-12-23 01:50 UTC, thguss commented on src/test/java/com/devcourse/springbootboardjpa/post/service/PostServiceTest.java
> +                .thenThrow(UserNotFoundException.class);
예외처리 테스트까지 꼼꼼하고 좋네용

2022-12-23 03:09 UTC, ksy90101 commented on src/main/java/com/devcourse/springbootboardjpa/common/dto/CommonResponse.java
> +        super(200, message);
200도 좋지만, 하드코딩보단, HTTPStatus 상수를 쓰는게 좋습니다.
[https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/http/HttpStatus.html](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/http/HttpStatus.html)
위 문서 한번 참고해보세요 :)

2022-12-23 03:09 UTC, ksy90101 commented on src/main/java/com/devcourse/springbootboardjpa/common/dto/ErrorResponse.java
> +    private static final Integer CONFLICT_STATUS = 409;
https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/http/HttpStatus.html

이 문서 보면 다 있어요.

2022-12-23 03:10 UTC, ksy90101 commented on src/main/java/com/devcourse/springbootboardjpa/common/dto/page/PageDTO.java
> +            int startPageNumber = 10 * ((page.getNumber()) / 10) + 1;
perPage가 10이 아닌 케이스가 잇을수도 있습니다.
무조건 10개씩 내려준다는 보장을 하기엔 유동적으로 관리하는것이 좋습니다.

2022-12-23 03:12 UTC, ksy90101 commented on src/main/java/com/devcourse/springbootboardjpa/common/exception/GlobalExceptionHandler.java
> +public class GlobalExceptionHandler {
기본적으로 RunTimeException을 headling을 해두는게 디버깅 하기 편할겁니다.

2022-12-23 03:13 UTC, ksy90101 commented on src/main/java/com/devcourse/springbootboardjpa/post/controller/PostController.java
> +    public ResponseEntity<ResponseDTO> savePost(@RequestBody @Valid PostDTO.SaveRequest saveRequest) {
생성시에는 https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/201 201 status를 사용하는것이 좋습니다.

2022-12-23 03:18 UTC, ksy90101 commented on src/main/java/com/devcourse/springbootboardjpa/post/controller/PostController.java
> +    @PostMapping("/posts/{id}")
update인 경우엔 PUT이나 PATCH를 사용하는게 좋습니다.
HTTP method를 찾아보세요.

2022-12-23 03:22 UTC, ksy90101 commented on src/main/java/com/devcourse/springbootboardjpa/post/domain/Post.java
> +    public void changeTitle(String title) {
대부분 title, content는 같이 변경될거 같아요.
동일한 값이면 어차피 JPA는 업데이트르 하지 않기 떄문에, 이렇게 굳이 두개를 분리할 필요는 없어보여요.
이렇게 하면 setter랑 다를바가 없습니다.

2022-12-23 03:22 UTC, ksy90101 commented on src/main/java/com/devcourse/springbootboardjpa/post/domain/dto/PostDTO.java
> +    public static class FindResponse {
inner calss는 복잡성을 많이 늘리게 됩니다.
혹시 inner calss를 쓴 이유가 있나요?

2022-12-23 03:25 UTC, ksy90101 requested changes
간단한 피드백을 남겼으니 확인해보시고 알려주세요.

2022-12-25 10:32 UTC, rhdtn311 commented on src/main/java/com/devcourse/springbootboardjpa/common/dto/CommonResponse.java
> +public class CommonResponse<T> extends ResponseDTO {
> ErrorResponse 파일 내용과 합쳤어도 좋았을 것 같은데 분리한 이유가 있을까요?? 단순히 궁금해요!

우선 `ErrorResponse`와 `CommonResponse`는 반환하는 값들을 다르게 하고 싶어서 구분을 했습니다.
그리고 `ErrorResponse`의 생성자와 `CommonResponse`의 생성자에 들어가는 인자가 달라서 다른 클래스로
구분해주는 것이 관리하기에 더 편하다고 개인적으로 생각했습니다.

2022-12-25 10:39 UTC, rhdtn311 commented on src/main/java/com/devcourse/springbootboardjpa/common/exception/ErrorCode.java
> +public enum ErrorCode {
> enum으로 뺀 거 깔끔하고 좋은 것 같아요~! 뺀 김에 ErrorCode에는 에러 코드만 넣고(400, 404 등), 에러 메시지는 ErrorMessage라는 enum으로 따로 빼는 것은 어떻게 생각하시나요??

오 그런 경우도 생각해봐야겠네요. 저는 `BusinessException`에 `ErrorCode`를 인자로 넣어서 `message`와 `status`를 한 번에 처리해주기 위해 하나의 `enum`으로 관리하도록 했습니다!!

2022-12-25 10:41 UTC, rhdtn311 commented on src/main/java/com/devcourse/springbootboardjpa/common/exception/post/PostNotFoundException.java
> +public class PostNotFoundException extends BusinessException {
> 별도의 예외 처리 폴더로 구분한 이유가 있을까요?? 단순 궁금해요!

특별한건 없는 것 같습니다. 단지 예외 처리와 관련된 클래스들 (`ErrorCode`, `BusinessException`, GlobalExceptionHandler` 등)을 하나의 폴더에서 관리하는게 편할 것 같았습니다.

2022-12-25 11:19 UTC, rhdtn311 commented on src/main/java/com/devcourse/springbootboardjpa/post/controller/PostController.java
> +        Long postId = postService.savePost(saveRequest);
> 개인적으로 객체 저장 후 객체 모든 정보를 반환하는 것을 선호하는 입장인데, 모든 정보를 반환하는 것은 어떻게 생각하시나요?? 모든 정보를 줘야할 지, 객체 고유 id만 줘야할 지 고민이 되더라구요

저도 고민 했습니다. 제 생각은 클라이언트에서 저장 후 객체의 Id 이외의 여러 값들을 사용해야 한다면 객체 모든 정보를 반환하는 것도 좋고 특별히 객체의 정보를 사용하지 않는다면 id만 반환하는게 더 효율적이라는 생각은 듭니다.

2022-12-25 11:27 UTC, rhdtn311 commented on src/main/java/com/devcourse/springbootboardjpa/post/controller/PostController.java
> +    @GetMapping("/posts/{id}")
> 개인적으로 id 보다는 postId와 같은 직관적인 변수명을 선호하는데 어떻게 생각하시나요?

여러 복잡한 상황까지 생각하면 그게 더 일관성 있고 좋은 방법 같습니다. 감사합니다!

2022-12-25 11:30 UTC, rhdtn311 commented on src/main/java/com/devcourse/springbootboardjpa/post/domain/Post.java
> +    public void changeTitle(String title) {
> 대부분 title, content는 같이 변경될거 같아요. 동일한 값이면 어차피 JPA는 업데이트르 하지 않기 떄문에, 이렇게 굳이 두개를 분리할 필요는 없어보여요. 이렇게 하면 setter랑 다를바가 없습니다.

title, content 를 수정하는 메서드를 하나의 메서드로 갖도록 변경하는 것이 더 좋을 것 같다는 말씀으로 이해해도 괜찮을까요 ??

2022-12-25 11:56 UTC, rhdtn311 commented on src/main/java/com/devcourse/springbootboardjpa/post/domain/dto/PostDTO.java
> +public class PostDTO {
> 오호 공통된 객체 DTO를 한 클래스로 묶는 방법도 있군요!! 저는 DTO를 분리했는데 어느 게 더 좋은 방식일까요?? 이것 또한 단순 궁금한 점입니다!

저는 하나의 클래스에 DTO를 모으는게 더 관리하기 편하다고 생각했는데, 마르코님께서 이렇게 관리하면 복잡도가 증가하신다고 하네요. 현재는 프로젝트가 작아서 괜찮지만 프로젝트가 커질 수록 나눠서 관리하는게 더 좋을 것 같다는 생각도 듭니다.

2022-12-25 12:05 UTC, rhdtn311 commented on src/main/java/com/devcourse/springbootboardjpa/post/service/PostService.java
> +    public PageDTO.Response<Post, PostDTO.FindResponse> findAllPostsPage(PageDTO.Request pageRequest) {
> 여기서 PageDTO도 좋지만 Pageable을 사용하면 더 수월하다고 위에서 말씀드린 의미였어요~! 혹시 의도적으로 따로 DTO를 만드신 거라면 왜 Pageable을 별도로 사용하지 않았는지도 궁금해요!

`Pageable`은 -1 같은 값이 들어갔을 때 디폴트 값을 넣더라구요. 그래서 예상치 못한 값이 들어가는게 좀 그래서 입력값을 검증할 수 있도록 DTO를 사용했습니다. 근데 깜빡하고 검증 로직을 안넣었네요 ..

2022-12-25 12:08 UTC, rhdtn311 commented on src/main/java/com/devcourse/springbootboardjpa/user/domain/User.java
> +    private String hobby;
> 지극히 개인적으로 String 대신 Hobby라는 별도 클래스를 만들어보시는 건 어떤가요! (강의에서 hobby라는 칼럼을 제시한 이유가 클래스를 가지는 칼럼도 만들어보라는 의미로 해석했거든요! 물론 아닐 수도 있지만 ㅎㅁㅎ)

오.. 근데 `Hobby` 클래스 안에는 어떤 값들이 들어가나요 ?

2022-12-25 12:31 UTC, rhdtn311 commented on src/main/java/com/devcourse/springbootboardjpa/user/domain/User.java
> +    private Integer age;
> int 대신 Integer 타입을 사용한 이유도 궁금합니다!

https://hyune-c.tistory.com/entry/Entity%EC%9D%98-field-type%EC%9D%80-%EB%AC%B4%EC%97%87%EC%9D%B4-%EC%A0%81%ED%95%A9%ED%95%A0%EA%B9%8C

저는 이 글을 참고했습니다!

2022-12-25 12:41 UTC, rhdtn311 commented on src/main/java/com/devcourse/springbootboardjpa/user/domain/User.java
> +    private List<Post> posts = new ArrayList<>();
> addPost 메서드는 따로 구현하지 않은 이유가 있을까요 ?~?

현재 프로젝트에서 사용되는 부분이 없어서 구현하지 않았습니다.

2022-12-25 12:42 UTC, rhdtn311 commented on src/test/java/com/devcourse/springbootboardjpa/post/controller/PostControllerTest.java
> +                        pathParameters(
> 파라미터 관련 진짜 고민하고 있었는데 pathParameters로 다시 찾아보고 시도해봐야겠네요,, 감사합니다!

https://godekdls.github.io/Spring%20REST%20Docs/documentingyourapi/

여기 참고하시면 도움이 될 것 같습니다!

2022-12-26 19:43 UTC, rhdtn311 commented on src/main/java/com/devcourse/springbootboardjpa/post/domain/dto/PostDTO.java
> +    public static class FindResponse {
> inner calss는 복잡성을 많이 늘리게 됩니다. 혹시 inner calss를 쓴 이유가 있나요?

하나의 클래스에서 관련된 DTO를 관리하는 것이 더 편하다고 생각했습니다.

2023-06-05 18:45 UTC, closed without merging