[3기-C 김영수] JPA 게시판 미션 구현 리뷰 부탁드립니다.
prgrms-be-devcourse/SpringBoot-Board pull request #178
Opened 2022-12-21 04:28 UTC by devYSK

## 📌 과제 설명 
JPA 게시판 미션 입니다. 

* User를 생성하기 위해 간단하게 User 생성 로직과 API를 구현하였습니다.
* 페이징은 요구사항에 더하여 커서 기반 페이지네이션으로 동작하게 하였습니다.
* API 문서는 Application 실행 시 `localhost:8080/docs/index.html`로 접속 가능합니다.
* DataSource는 h2로 하였고, application.yml은 보안에 큰 문제가 없을것 같아 같이 업로드 하였습니다. 

## 👩‍💻 요구 사항과 구현 내용 

- [X] SpringDataJPA를 설정한다.
   - datasource: h2
 
- [X] 엔티티를 구성한다.
- - [X] 회원(User)
    - id (PK) (auto increment)
    - name
    - age
    - hobby
    - **created_at** - 맵퍼드슈퍼클래스 사용 
    - **created_by**
- - [X] 게시글(Post)
  - id (PK) (auto increment)
  - title
  - content
  - **created_at**  - 맵퍼드슈퍼클래스 사용 
  - **created_by**

- [X] **API를 구현한다.**

- - [X]  게시글 조회
  - - [X]  페이징 조회 (GET "/posts")
  - - [X]  단건 조회 (GET "/posts/{id}")
- - [X]  게시글 작성 (POST "/posts")
- - [X] 게시글 수정 (POST "/posts/{id}")
  
  
- [X] **REST-DOCS를 이용해서 문서화한다.**
  - localhost:8080/docs/index.html

- [X] 페이징은 커서기반 페이지네이션으로 구현
- [X] 페이징 결과는 등록된 날짜가 최신일수로 먼저 조회되도록 DESC 구현

## ✅ PR 포인트 & 궁금한 점 
* MapperedSuperClass와 Audit을 이용해서 createdBy를 구현할 수 있다고 생각합니다. 허나 Session 이나 SecurityContext, `@Authentication` 같은 현재 요청을 보낸 사용자를 구분할 수 있는 객체 를 이용하지 않고, createdBy를 구현할 수 있는 방법을 찾지 못했습니다. 어떤 방법들이 있을까요? 

* 페이징 요청을 할 때, 다음 페이지의 존재 여부를 응답으로 주기 위한 필드인 hasNext를 구현하기 위하여 Service Class에 연산 로직을 사용하였습니다. 
  * Repository가 interface여서 연산 로직을 가지면 안된다고 생각하는데, PostService Class 에 저 로직이 있는것이 올바를까요? 

* 현재 Service 계층간에 의존성을 갖지 않게 하기 위해 PostServiceFacade라는 Facade 클래스를 만들어 사용하고 있습니다. 
  * 현재 요구사항과 기능들을 보았을 때, Interface까지는 필요 없다고 생각되어 Service들은 구체 클래스로 구현하였습니다.  
  * 컨트롤러는 Facade Service만 호출하면 되고 내부 구현은 몰라도 됩니다.
  * 한 기능을 구현하기 위하여 동작하는 여러 Service는 이제 다른 Service와의 의존이 필요 없게되며 SRP를 지킬 수 있다고 생각합니다. 
  * 그러나, 계층이 하나 더 추가됨으로서 코드량과 관리포인트, 테스트코드 량이 늘어난다고 생각합니다. 
  * 잘 설계되었을까요? 아니면 또 다른 방법이 있을까요. 
  * Facade 클래스의 패키지적 위치, 계층적 위치, 네이밍 등을 어떻게 하는것이 좋을지 궁금합니다. 

* 테스트 레벨에서 아쉬운점이나 더 테스트 해야 할 방안들을 리뷰 부탁드립니다.
  * Service 계층은 SliceTest와 IntegrationTest를 병행하고 있고 Web Controller 계층 테스트는 Integeration Test로 진행하고 있습니다.
  * 추가되어야 할 계층의 테스트와 어떤 테스트 가 추가되면 좋을지 궁금합니다.  
  * 아니면 이 테스트는 굳이 여기서 없거나 안해도 되는 테스트가 있을지도 궁금합니다. 

* 이외에 다른 문제점이나 좋은 방안 있으시면 말씀해주시길 부탁드리겠습니다. 감사합니다.

2022-12-21 15:38 UTC, choi1204 reviewed
수고하셨습니다 영수님. 코멘트 확인하시고 학습에 도움이 되시면 좋겠습니다.

궁금한점에 관련하여 간략하게 제 생각을 말씀드리겠습니다.

Q1. MapperedSuperClass와 Audit을 이용해서 createdBy를 구현할 수 있다고 생각합니다. 허나 Session 이나 SecurityContext, @Authentication 같은 현재 요청을 보낸 사용자를 구분할 수 있는 객체 를 이용하지 않고, createdBy를 구현할 수 있는 방법을 찾지 못했습니다. 어떤 방법들이 있을까요?
A1. 우선 CreatedBy는 수정자, 또는 작성자와 같이 사용자를 구분하기 위해서 사용되기 때문에 일반적으로 사용자를 구분할 수 있는 객체를 사용하는게 맞습니다. 하지만 학습적으로 저 부분을 랜덤하게 커스텀하고 싶다면 AuditAware을 빈으로 등록하는 방법을 찾아보시면 될 것 같습니다.

Q2. 페이징 요청을 할 때, 다음 페이지의 존재 여부를 응답으로 주기 위한 필드인 hasNext를 구현하기 위하여 Service Class에 연산 로직을 사용하였습니다.

- Repository가 interface여서 연산 로직을 가지면 안된다고 생각하는데, PostService Class 에 저 로직이 있는것이 올바를까요?

A2. 저러한 연산로직이 필요하다면 Service 또는 Util클래스로 만들어서 처리하는게 맞다고 생각합니다.

Q3. 현재 Service 계층간에 의존성을 갖지 않게 하기 위해 PostServiceFacade라는 Facade 클래스를 만들어 사용하고 있습니다.

현재 요구사항과 기능들을 보았을 때, Interface까지는 필요 없다고 생각되어 Service들은 구체 클래스로 구현하였습니다.
컨트롤러는 Facade Service만 호출하면 되고 내부 구현은 몰라도 됩니다.
한 기능을 구현하기 위하여 동작하는 여러 Service는 이제 다른 Service와의 의존이 필요 없게되며 SRP를 지킬 수 있다고 생각합니다.
그러나, 계층이 하나 더 추가됨으로서 코드량과 관리포인트, 테스트코드 량이 늘어난다고 생각합니다.
잘 설계되었을까요? 아니면 또 다른 방법이 있을까요.
Facade 클래스의 패키지적 위치, 계층적 위치, 네이밍 등을 어떻게 하는것이 좋을지 궁금합니다

A3. User와 관련이 되었을경우에는 Security가 적용되 일반적인 방법과 다르게 적용이 됩니다. 하지만 현재 Security가 도입되지 않은 것을 고려했을 때 Facade를 잘사용하고 있는 것 같습니다. 하지만 충분한 의미를 가지는 네이밍과 패키지 클래스를 따로 가지면 좋을 것 같습니다.

테스트의 경우에는 현재 잘 진행되고 있는 것 같습니다. 다만 현재 통합 테스트로 진행되고 있는 코드들이 꼭 통합테스트여야 할까? 를 고민하시고 테스트 코드의 F.I.R.S.T원칙을 생각하면 리팩토링하시면 좋을 것 같습니다.

2022-12-21 15:38 UTC, choi1204 commented on board/board/src/main/java/com/ys/board/domain/post/model/Post.java
> +    @NotBlank
이부분에 @ NotBlank를 하신 이유가 있을까요?

2022-12-21 15:38 UTC, choi1204 commented on board/board/src/main/java/com/ys/board/domain/post/service/PostService.java
> +        Pageable pageable = PageRequest.of(0, pageSize + 1);
pageSize + 1을 하신 이유가 다음 페이지가 있는 없는지를 확인하기 위해서 인것으로 보입니다.
이 부분은 직접 하시는것보다 Slice 클래스를 활용하시면 코드가 더 간결해질 것으로 보입니다.

2022-12-21 15:38 UTC, choi1204 commented on board/board/src/main/java/com/ys/board/domain/post/service/PostService.java
> +            throw new EntityNotFoundException(Post.class);
이 부분에 예외가 필요할까요? 
비즈니스 상황마다 정답은 다르다고 생각이 들지만 jpa에서 지원해주는 paging 쿼리를 사용했을때를 생각하면 예외가 필요할까 생각해보면 좋을 것 같습니다

2022-12-21 15:38 UTC, choi1204 commented on board/board/src/main/java/com/ys/board/domain/post/service/PostServiceFacade.java
> +        post.changeUser(findUser);
현재 security context나 session을 사용할 수 없는 환경이여서 Post를 생성 후에 user를 생성하여서 이런 구조가 된것 같습니다. 
change라는 메서드명이 Post의 유저가 변경될 수 있다는 의미로 보일 수도 있어서 메서드명을 수정하면 더 좋을 것 같습니다

2022-12-21 15:38 UTC, choi1204 commented on board/board/src/main/java/com/ys/board/domain/post/repository/PostRepository.java
> +    List<Post> findByIdLessThanOrderByIdDescCreatedAtDesc(@Param("id") long id, Pageable pageable);
unique를 보장하는 id로 정렬을 하면서 CreatedAt을 정렬을 더한 이유가 있을까요?

2022-12-21 15:38 UTC, choi1204 commented on board/board/src/main/java/com/ys/board/domain/user/DuplicateNameException.java
> +package com.ys.board.domain.user;
exception 패키지로 변경하셔야 할것같아요

2022-12-21 15:38 UTC, choi1204 commented on board/board/src/main/java/com/ys/board/domain/user/api/UserCreateResponse.java
> +@NoArgsConstructor
(access = AccessLevel.PROTECTED) 빼먹으신것같아요

2022-12-21 15:38 UTC, choi1204 commented on board/board/build.gradle
> +        from "${asciidoctor.outputDir}"
copy까지 하셨군요 굿입니다

2022-12-21 16:01 UTC, devYSK commented on board/board/src/main/java/com/ys/board/domain/post/model/Post.java
> +    @NotBlank
@choi1204 

콘텐츠 내용은 빈 값이면 안된다고 생각해서 NotBlank를 사용했습니다!

2022-12-21 16:01 UTC, devYSK commented on board/board/src/main/java/com/ys/board/domain/post/repository/PostRepository.java
> +    List<Post> findByIdLessThanOrderByIdDescCreatedAtDesc(@Param("id") long id, Pageable pageable);
@choi1204 

흑구님이 추가해주신 요구사항 중 생성 날짜를 내림차순으로 정렬하라는 요구사항이 있었는데,
사실 이부분에 있어 CreatedAt으로 정렬을 다시 해야하나 넣어야 하나 고민을 했습니다.
> unique하고 sequence한 id값이 있으므로 생성날짜와 비례하는데 또 CreatedAt으로 정렬이 필요할까? 
라는 고민이였습니다. id 정렬만으로 생성날짜의 내림차순이라는 요구사항을 충족시킬 수 있을까요?

2022-12-21 16:01 UTC, devYSK commented on board/board/src/main/java/com/ys/board/domain/post/service/PostService.java
> +        Pageable pageable = PageRequest.of(0, pageSize + 1);
@choi1204 

제가 알기로 Slice는 무한스크롤을 구현하기 위한 api로만 알고있었는데 내부적으로 limit (size)+1을 해주는군요!. 감사합니다! 참고하고 공부해보겠습니다

2022-12-21 16:01 UTC, devYSK commented on board/board/src/main/java/com/ys/board/domain/post/service/PostService.java
> +            throw new EntityNotFoundException(Post.class);
@choi1204 

리스트 조회시 빈 값이면 empty하다는 파라미터들을  같이 보내주라는 말씀이실까요!!

2022-12-21 16:01 UTC, devYSK commented on board/board/src/main/java/com/ys/board/domain/post/service/PostServiceFacade.java
> +        post.changeUser(findUser);
@choi1204 

참고하여 수정해보겠습니다!

2022-12-21 16:01 UTC, devYSK commented on board/board/src/main/java/com/ys/board/domain/user/DuplicateNameException.java
> +package com.ys.board.domain.user;
넵!! 수정해서 관리하도록 하겠습니다.

2022-12-22 03:34 UTC, choi1204 commented on board/board/src/main/java/com/ys/board/domain/post/model/Post.java
> +    @NotBlank
Bean Validation이 어떻게 동작되는지 학습하시면 좋을 것 같아요!

2022-12-22 03:35 UTC, choi1204 commented on board/board/src/main/java/com/ys/board/domain/post/service/PostService.java
> +            throw new EntityNotFoundException(Post.class);
네 맞습니다 단일조회가 아닐때 빈값이면 에러가 필요로할까? 라는  생각을 가지고 결론에 도달하면 좋을 것 같습니다

2022-12-22 03:37 UTC, choi1204 commented on board/board/src/main/java/com/ys/board/domain/post/repository/PostRepository.java
> +    List<Post> findByIdLessThanOrderByIdDescCreatedAtDesc(@Param("id") long id, Pageable pageable);
id 정책에 따라서 생성날짜의 내림차순을 만족시킨다는 보장을 가지기는 힘들다고 생각합니다.

2022-12-22 11:37 UTC, WooSungHwan requested changes
영수님 과제하시느라 고생하셨습니다!
리뷰 몇자 남기니 확인 부탁드립니다!

2022-12-22 11:37 UTC, WooSungHwan commented on board/board/src/main/java/com/ys/board/common/RestGlobalExceptionHandler.java
> +    @ExceptionHandler(MethodArgumentNotValidException.class)
http status가 다르게 나갈것 같습니다!

2022-12-22 11:37 UTC, WooSungHwan commented on board/board/src/main/java/com/ys/board/domain/post/api/PostController.java
> +    }
RequestMapping 어노테이션들이 모두 `produces`와 `consumes` 속성이 비어있습니다.
content-type을 명시적으로 제한해주시는게 좋을 것 같습니다. laugh한 api 설계보다 타이트하게 설계해주는게 좋을것 같아요.

2022-12-22 11:37 UTC, WooSungHwan commented on board/board/src/main/java/com/ys/board/domain/post/api/PostCreateRequest.java
> +    @NotBlank
`message = "제목을 입력해주세요."` 정도의 노티는 필요하다고 생각합니다.
설령 클라이언트에서 해당 메시지를 사용하지 않더라도 클라 개발자도 api를 사용하는 입장이라 뭐가 잘못됐는지는 아는게 좋을거에요.

2022-12-22 11:37 UTC, WooSungHwan commented on board/board/src/main/java/com/ys/board/domain/post/api/PostResponses.java
> +    }
얘는 왜필요한건가요??

2022-12-22 11:37 UTC, WooSungHwan commented on board/board/src/main/java/com/ys/board/domain/post/api/PostsRequest.java
> +    private int pageSize;
최소도 검증해주면 좋ㅇ르것같아요.

2022-12-22 11:37 UTC, WooSungHwan commented on board/board/src/main/java/com/ys/board/domain/post/repository/PostRepository.java
> +    List<Post> findByIdLessThanOrderByIdDescCreatedAtDesc(@Param("id") long id, Pageable pageable);
이 부분은 우선..
사실 id로 하나  createtime으로 하나 크게 차이는 없어보이고 orderby에 대한 조건을 추가해보려고 했던걸로 기억합니다. 통상 목록에 order 조건은 새로 유입된 기준으로 desc 하니까요. id desc, createdAt desc는 조금 어색해요. 둘중 하나 기준으로 잡고 여기서 좀더 고민해야될 부분이 있긴한데 이건 팀미팅때 더 추가적으로 이야기해봐요.

그리고 Pageable 인터페이스를 조금 열어봤다면 혹은 관련 클래스를 살펴봤다면 정렬을 메소드 명으로 하지는 않았을 거 같습니다.
order by 조건을 적용할 수 있는 다른 방법을 찾아보셔요

2022-12-22 11:37 UTC, WooSungHwan commented on board/board/src/main/java/com/ys/board/domain/user/model/User.java
> +    }
둘중에 뭐로 생성할건지 택해야 할것 같아보입니다. 
전체 생성자를 protected 이하로 두고 static으로만 접근하게 할것인지 static을 안쓸건지 결정해야할 것같아요.

2022-12-22 11:37 UTC, WooSungHwan commented on board/board/src/main/resources/application.yml
> +    database: h2
ddl-auto: 실제 현업에서 erd를 변화시킬 수 있는 update, create 이상의 값은 사용하지 않습니다. 이미 테이블이 생성되어있는 경우 update로는 해결되지 않는 부분이 있어 어차피 거기서 거기입니다. 
직접 ddl을 이용하여 테이블을 변경하곤하고 관리되는 코드로는 none으로 두는게 좋습니다.

show-sql : 개발할때만 true로 두고 운영상황에서는 제거해야 좋을 것 같습니다.

추가적으로 graceful shutdown 한번 알아보시면 좋을 것 같습니다.

2022-12-23 01:42 UTC, WooSungHwan reviewed
추가리뷰 몇자 남겼습니다! 확인 부탁드립니다~

2022-12-23 01:42 UTC, WooSungHwan commented on board/board/src/main/java/com/ys/board/common/RestGlobalExceptionHandler.java
> +    }
순간 CONFLICT를 봤을 때, 맞구나 하고 간과했는데 해당 응답 코드가 상당히 오해를 불러일으킬 수 있을만한 부분이 있습니다. 우선 해당 응답코드는 PUT 수정과정에서 나와야 맞습니다.

어떤 데이터를 수정하고자 하는데 현재의 이름과 그때의 이름이 맞지 않았을 경우 내보낼 수 있는 응답코드이죠.
예컨데 유저정보를 수정하는 화면에서 오랜기간 있다가 다른 크롬의 탭에서 수정을 하고 기존에 켜놨던 수정에서 다시한번 수정버튼을 누르는 경우가 대표적인 conflict 응답코드를 내려줄 수 있는 상황입니다. 오래전 내려줬던 데이터와 현재 서버에 저장된 데이터의 버전이 다르기 때문이죠. 하지만 지금은 단순히 이름중복의 비즈니스 로직에서의 유효성 처리이다보니 오해가 있어보입니다.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/409
409 코드를 소개하는 모질라 사이트에서는 대표적인 예제로 파일업로드 부분을 소개하고 있습니다. 현재 업로드 하려는 버전이 이미 이전 버전(예를 들어 파일 생성 혹은 수정 날짜가 서버에 있는 파일의 생성 혹은 수정 날짜보다 이전이라면) 의 파일이라면 해당 응답코드를 내려주어 예외상황을 나타내 줄 수 있다고 하네요.

현재 영수님의 코드로 봤을때 DuplicateNameException 예외는 단순히 유저를 생성할 때 (Post 겠죠?) validateDuplicateName 이라는 유효성 메소드에서 발생하고 있습니다. 이러한 비즈니스 로직에 의한 이름중복 같은 처리는 BAD_REQUEST로 처리하는게 좀더 혼동되지 않는 처리방법으로 생각됩니다.

2022-12-27 08:42 UTC, devYSK commented on board/board/src/main/java/com/ys/board/domain/user/model/User.java
> +    }
접근제한자 변경하여 반영하도록 하겠습니다!

2022-12-27 08:44 UTC, devYSK commented on board/board/src/main/java/com/ys/board/domain/post/api/PostsRequest.java
> +    private int pageSize;
반영하도록 하겠습니다 !

2022-12-27 08:50 UTC, devYSK commented on board/board/src/main/java/com/ys/board/domain/post/api/PostResponses.java
> +    }
has라는 prefix를 붙이고 싶었는데 붙지 않아서 새로 만들었습니다. 
`@Accessors` 어노테이션을 찾아서 해결했습니다 !

2022-12-27 10:18 UTC, devYSK commented on board/board/src/main/java/com/ys/board/domain/post/api/PostCreateRequest.java
> +    @NotBlank
추가해놓겠습니다!!

2022-12-27 10:18 UTC, devYSK commented on board/board/src/main/java/com/ys/board/domain/post/api/PostController.java
> +    }
추가 하겠습니다! 
requestBody가 없는 상황에서의 Get Request에서는 Consumes는 명확하게 지정할 필요가 없어 보이는데 제 생각이 맞을까요?

2022-12-27 10:21 UTC, devYSK commented on board/board/src/main/java/com/ys/board/common/RestGlobalExceptionHandler.java
> +    @ExceptionHandler(MethodArgumentNotValidException.class)
맞춰 설정하여 다르게 나가지 않도록 하겠습니다 !

2022-12-27 13:43 UTC, devYSK commented on board/board/src/main/java/com/ys/board/common/RestGlobalExceptionHandler.java
> +    }
409 에러는 충돌, 즉 클라이언트의 요청이 서버의 상태와 충돌이 발생한 경우의 에러코드로 알고있습니다.
리소스의 상태가 존재하고(유저 이름),  같은 리소스 생성을 요청하니 충돌해서 요청을 처리할 수 없으므로 클라이언트가 요청을 다시 클라이언트가 이 것을 수정해서 요청을 다시 보낼 수 있는 상황이니까 충돌로 이해하고,BAD_REQUEST랑 CONFLICT랑 어떤 응답이 좋을까 고민하다 사용한 부분인데, 말씀주신대로 혼동되는 여지가 있는것 같습니다. 

그렇다면 PUT 메서드 수정과정이 아닌 다른 과정에서는 나올 수가 없는걸까요?

2022-12-28 08:38 UTC, WooSungHwan commented on board/board/src/main/java/com/ys/board/common/RestGlobalExceptionHandler.java
> +    }
중복에 대한 검사는 일종의 비즈니스 로직이기 때문에 서버 리소스와 관련된 코드인 409와는 차이가 있습니다. API 서버가 아닌 별도의 리소스(이미지, 멀티미디어 등 정적 리소스)를 저장하고 있는 서버라고 생각해보시면 이해가 빠를겁니다.

2022-12-28 08:46 UTC, WooSungHwan commented on board/board/src/main/java/com/ys/board/domain/post/api/PostController.java
> +    }
웹서버를 톰캣으로 이용한다면 맞다고 할 수 있습니다. 웹서버마다 GET 메소드의 body 를 바라볼 수도 있고 바라보지 않을 수도 있습니다.
https://brunch.co.kr/@kd4/158
해당 내용 참조해보세요. 무작정 GET이라고 BODY를 쓸수 있다. 없다. 단정짓기엔 무리가 있습니다. 

대체적으로 관습 및 여러 웹서버 혹은 클라이언트(api 호출하는)를 고려한 설계를 한다면 GET에서 body에 대한 content-type 은 통상 고려하지 않아도 됩니다.

2023-06-05 18:45 UTC, closed without merging