[3기-C 이수영] JPA 게시판 과제 제출합니다.
prgrms-be-devcourse/SpringBoot-Board pull request #184
Opened 2022-12-22 15:11 UTC by twotwobread

## 📌 과제 설명
SpringBoot JPA 과제 - 게시판 구현

## 👩‍💻 요구 사항과 구현 내용
- [x]  **SpringDataJPA 를 설정한다.**
    - [x]  datasource : h2 or mysql
- [x]  **엔티티를 구성한다**
    - [x]  회원(User)
        - id (PK) (auto increment)
        - name
        - age
        - hobby
        - **created_at**
        - **created_by** -> **modified_at** 으로 수정
    - [x]  게시글(Post)
        - id (PK) (auto increment)
        - title
        - content
        - **created_at**
        - **created_by** -> **modified_at** 으로 수정
    - [x]  회원과 게시글에 대한 연관관계를 설정한다.
        - 회원과 게시글은 1:N 관계이다.
    - [x]  게시글 Repository를 구현한다. (PostRepository)
- [x]  **API를 구현한다.**
    - [x]  게시글 조회
        - 페이징 조회 (GET "/posts")
        - 단건 조회 (GET "/posts/{id}")
    - [x]  게시글 작성 (POST "/posts")
    - [x]  게시글 수정 (PATCH "/posts/{id}")
- [x]  **REST-DOCS를 이용해서 문서화한다.**

## ✅ 프로그램 실행 방법
포트번호 : 8000
localhost:8000 접속 시 api 문서화 페이지가 출력됩니다.

## ✅ PR 포인트 & 궁금한 점
1. PostController와 ControllerExceptionHandler 컨트롤러 어드바이스에서 ApiResponse라는 공통 응답을 위한 클래스를 구현해서 응답합니다. 이 부분은 JPA 강의에서 강사님께서 이런 식으로 반환해주셔서 똑같이 따라해봤는데 이런 식으로 구현하는 이유를 잘모르겠습니다. 공통의 응답을 만들고 싶다면 ResponseEntity를 이용해서 하면 될텐데 굳이 이런 클래스를 만들어주는 이유가 뭘까요?? 그리고 ResponseEntity를 사용하는 방법과 ResponseStatus를 이용해서 status를 지정하고 Dto를 그대로 반환하는 방법에서 ResponseEntity를 이용하는 이유는 더 자세한 정보를 주기 위함뿐일까요??
2. PostServiceTest에서 update에 관한 테스트를 진행하는데 mocking을 통한 테스트를 합니다. 그 때 when, thenReturn을 이용해서 반환 값을 정해주면서 테스트를 진행하는데 해당 테스트의 수행이 의미가 없다는 느낌을 받았습니다. 어짜피 내가 달라는 값 가지고 오는 건데 해당 값들이 같은지를 검증하는게 맞나? 라는 생각이 들었는데 제가 짠 update 테스트가 의미가 있는 테스트가 맞을까요??
3. 페이지를 이용한 모든 게시글 조회 (PostController의 getAll 메서드 부분)에서 Page를 그대로 data에 넣고 반환해주니까 응답 json을 봤을때 pageable까지 들어가면서 좀 지저분하다는 느낌을 받았고 해당 부분이 다 필요한가 의문이 들었습니다. 이 부분에 ResponseDto를 따로 만들어 주는 것이 더 좋은 선택일까요??

2022-12-23 10:48 UTC, Seongjun-Kwon requested changes

2022-12-23 10:48 UTC, Seongjun-Kwon commented on src/main/java/com/prgrms/be/app/controller/PostController.java
> +    }
생성하고 Long 값만 반환해주는 이유가 있을까요?

2022-12-23 10:48 UTC, Seongjun-Kwon commented on src/main/java/com/prgrms/be/app/controller/PostController.java
> +        return ApiResponse.ok(
200 status 도 괜찮지만 201(created) 를 써보는 것은 어떨까요?

2022-12-23 10:48 UTC, Seongjun-Kwon commented on src/main/java/com/prgrms/be/app/controller/PostController.java
> +    public ApiResponse<Page<PostDTO.PostsResponse>> getAll(@RequestBody PostDTO.PageRequest pageRequest) {
Page<PostDTO.PostsResponse> 를 래핑하는 클래스를 만들어보면 어떨까요?

Page 에서 필요하지 않은 정보는 사용하지 않을 수도 있고, 더 관리하기도 용이할 것 같습니다.

2022-12-23 10:48 UTC, Seongjun-Kwon commented on src/main/java/com/prgrms/be/app/controller/PostController.java
> +    @PostMapping("/{id}")
Post 말고 Patch, Put 메서드를 이용해보는 것은 어떨까요?
patch 와 put 은 차이점이 있는데 그 점도 고려해보시면 좋을 것 같습니다.

2022-12-23 10:48 UTC, Seongjun-Kwon commented on src/main/java/com/prgrms/be/app/domain/Post.java
> +    @NotBlank
NotBlank 는 NotNull 과는 다르게 jpa 가 ddl 시 필드에 not null 을 자동으로 적용해주지 않는다고 합니다.

2022-12-23 10:48 UTC, Seongjun-Kwon commented on src/main/java/com/prgrms/be/app/domain/User.java
> +    @OneToMany(mappedBy = "createdBy", fetch = FetchType.LAZY)
~ToMany 에서 fetch 의 디폴트 값이 Lazy 라 명시해주지 않아도 될 것 같습니다!

2022-12-23 10:48 UTC, Seongjun-Kwon commented on src/main/java/com/prgrms/be/app/domain/dto/PostDTO.java
> +
이너 클래스로 관리해주신 이유가 궁금합니다.
DTO 가 많아질수록 PostDTO 가 엄청 많은 책임을 가지는 뚱뚱한 클래스가 되지 않을까요?

2022-12-23 10:48 UTC, Seongjun-Kwon commented on src/test/java/com/prgrms/be/app/controller/PostControllerTest.java
> +    }
테스트 로직이 완성되지 않은 것 같습니다!

2022-12-23 10:48 UTC, Seongjun-Kwon commented on src/test/java/com/prgrms/be/app/service/PostServiceTest.java
> +        assertThat(postId).isEqualTo(post.getId());
verify 로 동작 테스트를 추가하면 어떨까요?

2022-12-23 10:48 UTC, Seongjun-Kwon commented on src/test/java/com/prgrms/be/app/service/PostServiceTest.java
> +        assertThat(postUpdateRequest.getContent()).isEqualTo(updatedPostDto.content());
hasFieldOrPropertyWithValue 로 필드 값 테스트를 해봐도 좋을 것 같아요!

2022-12-23 10:48 UTC, Seongjun-Kwon commented on src/main/java/com/prgrms/be/app/controller/ControllerExceptionHandler.java
> +
ResponseEntityExceptionHandler 를 상속해주신 이유가 있나요?
따로 재정의 해준 메서드가 없는 것 같습니다!

2022-12-23 10:49 UTC, Seongjun-Kwon commented
수영님 간단한 리뷰 남겼습니다!
리뷰하면서 많이 배웠습니다! 😀

2022-12-25 09:03 UTC, twotwobread commented on src/main/java/com/prgrms/be/app/controller/PostController.java
> +    }
Long 값을 반환해주는 이유는 생성했음을 알리고 해당 데이터가 제대로 저장되었는지 확인하기 위한 최소의 값을 반환해주는 것이 좋다고 생각되어서 Id만을 반환하게 구성했습니다.

2022-12-25 09:04 UTC, twotwobread commented on src/main/java/com/prgrms/be/app/controller/PostController.java
> +        return ApiResponse.ok(
조금 더 디테일한 정보를 주는게 좋을 것 같습니다!! 감사합니다!!

2022-12-25 09:05 UTC, twotwobread commented on src/main/java/com/prgrms/be/app/controller/PostController.java
> +    public ApiResponse<Page<PostDTO.PostsResponse>> getAll(@RequestBody PostDTO.PageRequest pageRequest) {
안그래도 질문으로 남겼던 부분이었습니다. 필요하지 않은 정보를 사용하지 않고 더 관리하기 용이할 것 같다는 의견 감사합니다!!

2022-12-25 09:08 UTC, twotwobread commented on src/main/java/com/prgrms/be/app/controller/PostController.java
> +    @PostMapping("/{id}")
주어진 요구사항에서 Post를 사용하라고 했어서 생각을 안했었는데 고려해보겠습니다.
patch와 put의 차이점은 patch는 자원의 부분 교체이기에 부분적인 필드만을 바꿀 수 있지만 put은 자원의 전체 교체라서 특정 필드만 교체할 경우 이외의 필드는 null 값이나 초기값으로 설정된다고 알고 있습니다!!

2022-12-25 09:10 UTC, twotwobread commented on src/main/java/com/prgrms/be/app/domain/User.java
> +    @OneToMany(mappedBy = "createdBy", fetch = FetchType.LAZY)
말하신 것처럼 엔티티의 필드이니만큼 테이블과 동일한 컬럼, 제약조건을 가지는 것이 더 좋을 것 같습니다. @NotNull 통해서 null에 대한 validation을 수행하고 추가적인 처리를 통한 공백에 대한 validation을 수행하겠습니다.

2022-12-25 09:12 UTC, twotwobread commented on src/main/java/com/prgrms/be/app/domain/dto/PostDTO.java
> +
PostDTO가 커진다고 저는 많은 책임을 가진다고 생각하지 않습니다. PostDTO는 Post 엔티티의 DTO에 대한 책임만을 가지는 것이 아닐까요?? 많은 책임을 가진다고 생각하시는 이유가 궁금합니다!!

2022-12-25 09:13 UTC, twotwobread commented on src/test/java/com/prgrms/be/app/controller/PostControllerTest.java
> +    }
해당 로직에 대한 테스트를 따로 수행을 했는데 지우는 것을 깜박한 것 같습니다. 죄송합니다!!

2022-12-25 09:13 UTC, twotwobread commented on src/test/java/com/prgrms/be/app/service/PostServiceTest.java
> +        assertThat(postId).isEqualTo(post.getId());
추가하는게 더 좋아보입니다 감사합니다!!

2022-12-25 09:14 UTC, twotwobread commented on src/test/java/com/prgrms/be/app/service/PostServiceTest.java
> +        assertThat(postUpdateRequest.getContent()).isEqualTo(updatedPostDto.content());
혹시 hasFieldOrPropertyWithValue를 이용한 테스트로 바꿨을 떄 생기는 이점이 뭐라고 생각하시나요??

2022-12-25 09:18 UTC, twotwobread commented on src/main/java/com/prgrms/be/app/controller/ControllerExceptionHandler.java
> +
ResponseEntityExceptionHandler는 스프링 예외를 미리 처리해둔 추상 클래스로 알고 있는데 이에 대한 에러 응답 또한 통일해주려 했으나 어떤 식으로 처리해야할지 생각하다가 오버라이딩을 해주지 않았던 것 같습니다. 감사합니다!!

2022-12-28 17:34 UTC, Seongjun-Kwon commented on src/test/java/com/prgrms/be/app/service/PostServiceTest.java
> +        assertThat(postUpdateRequest.getContent()).isEqualTo(updatedPostDto.content());
저도 바꿔봤는데 저에게는 좀 더 직관적으로 읽혀서 가독성이 좋았습니다!

2022-12-28 17:50 UTC, Seongjun-Kwon commented on src/main/java/com/prgrms/be/app/domain/dto/PostDTO.java
> +
제가 전달하고자 하는 의미를 책임이라고 잘못 적은 것 같아요😂 책임이라기보단 확장될수록 PostDTO 가 점점 뚱뚱해지니까 코드를 보거나 찾을 때 점점 더 귀찮아질 것 같다는 의미를 전달하려고 했습니다.
이걸 어떤 단어로 표현해야할지 모르겠네요😂

DTO 가 많아질수록 패키지 내의 많은 파일이 생기는 것 vs DTO 의 내부 클래스가 많아지는 것
둘 다 각자의 장단점이 있는 것 같은데 취향의 차이라고 할 수 있는 것인지 저도 궁금해졌습니다😅
멘토님들의 도움이 필요합니다!

2022-12-30 03:13 UTC, ksy90101 commented on src/main/java/com/prgrms/be/app/controller/ControllerExceptionHandler.java
> +        return ApiResponse.fail(404, exception.getMessage(), ResponseMessage.ERRORED);
HTTPStauts 상수로 이미 Spring에선 존재합니다.
한번 찾아보고 상수를 쓰는게 어떨까요?

2022-12-30 03:14 UTC, ksy90101 commented on src/main/java/com/prgrms/be/app/controller/PostController.java
> +    //toDo : 생성
todo는 이미 구현되어 잇다면 주석은 최소화 해주세요.

2022-12-30 03:14 UTC, ksy90101 commented on src/main/java/com/prgrms/be/app/controller/PostController.java
> +    @PostMapping()
()는 생략 가능합니다 :)

2022-12-30 03:14 UTC, ksy90101 commented on src/main/java/com/prgrms/be/app/domain/Post.java
> +        checkArgument(!title.isBlank() && title.length() > 0 && title.length() <= 20, "게시물 제목의 길이가 0보다 크고 20 이하가 되야 합니다.", title);
👍

2022-12-30 03:15 UTC, ksy90101 commented on src/main/resources/logback-spring.xml
> +
여기도 주석이 있네요?

2022-12-30 03:18 UTC, ksy90101 commented on src/main/java/com/prgrms/be/app/domain/dto/PostDTO.java
> +
내부 클래스는 복잡성을 높인다고 생각합니다.

왜 내 부 클래스를 쓰려고 한지는 예측이 되는데요.
어떻게보면 한곳에 관련되어 있는 애들을 모아두고 싶었던거같아요.

그러나, 패키지로 충분히 한곳에 관련되어 있는 애들을 충분히 모아둘수 있다고 생각합니다.

또한 내부 클래스로 한다면 차후에 확장성도 떨어질듯 합니다.

뚱뚱한 클래스가 되는것도 공감되구요.

@Seongjun-Kwon @twotwobread

2022-12-30 03:19 UTC, ksy90101 commented on src/main/java/com/prgrms/be/app/domain/dto/PostDTO.java
> +}
```suggestion
    }
}
```

2022-12-30 03:19 UTC, ksy90101 commented on src/main/java/com/prgrms/be/app/domain/dto/PostDTO.java
> +            return org.springframework.data.domain.PageRequest.of(page - 1, size, direction, "createdAt");
제대로 import 해보실래요?

2022-12-30 03:19 UTC, ksy90101 commented on src/main/java/com/prgrms/be/app/util/PostConverter.java
> +                allPost.getContent().stream().map(this::convertToPostDetailResponse).collect(Collectors.toList()),
한줄에 점 하나씩 작성해야, 보기가 더 편리합니다 :)

2022-12-30 03:20 UTC, ksy90101 requested changes
전체적으로 잘 구현해주셨네요 💯 
간단한 피드백을 남겼으니, 참고해보시고 확인되면 다음엔 머지할게요~

2023-01-11 10:16 UTC, ksy90101 approved these changes
추가 게시판 구현때 다시 같이봐요. 고생하셨어요 :+1

2023-01-11 10:17 UTC, merged