[3기-C 김기서] JPA 게시판 구현 미션 제출합니다.
prgrms-be-devcourse/SpringBoot-Board pull request #189
Opened 2022-12-26 12:38 UTC by rlarltj

멘토님들 안녕하세요!
잘부탁드립니다.

## 📌 과제 설명
JPA를 이용해 게시판을 구현하는 과제입니다.
- createBy 컬럼은 현재 세션에 저장된 Member의 id값을 가져와 사용했습니다.
- 예외 발생 시 ApiBindErrorResponse(bean validation 예외 시), ApiErrorResponse(내부 예외 시)를 응답객체로 사용했습니다.
- 정상 응답의 경우 ApiResponse라는 객체로 각 Entity의 반환Dto를 한번 더 포장해서 반환하도록 했습니다.

## 👩‍💻 요구 사항과 구현 내용

- [X] 엔티티를 구성한다.
- 회원(Member)
    - id (PK) (auto increment)
    - name
    - age
    - hobby
    - created_at
    - created_by
-  게시글(Post)
   - id (PK) (auto increment)
   - title
   - content
   - created_at
   - created_by
- 회원과 게시글에 대한 연관관계를 설정한다.
- 게시글 Repository를 구현한다(PostRepository)

- [X] API를 구현한다.
- 게시글 조회
  - 단건 조회 (GET "/posts/{id}")
  - 페이징 조회 (GET "/posts")
- 게시글 작성 (POST "/posts")
- 게시글 수정 (PUT "/posts/{id}")

- [X] REST-DOCS를 이용해서 문서화한다.

- [X] 커서 기반 페이지네이션

## ✅ PR 포인트 & 궁금한 점
테스트 코드의 허점이나 코드 중 어색한 부분 가감없이 말씀해주시면 정말 감사하겠습니다!!!!!!!!!

2022-12-28 09:17 UTC, WooSungHwan requested changes
기서님! 과제하시느라 고생하셨습니다.
리뷰 몇자 남겼으니 확인해주세요!

2022-12-28 09:17 UTC, WooSungHwan commented on src/main/java/com/prgrms/board/JpaBoardApplication.java
> +@EnableJpaAuditing
메인에 넣기보단 별도의 config 클래스에서 동작하도록 하면 좋을 것 같습니다.

2022-12-28 09:17 UTC, WooSungHwan commented on src/main/java/com/prgrms/board/controller/PostApiController.java
> +    }
성공적으로 api 호출이 마무리됐으면 200으로 전달될거라 responseStatus ok는 붙일 필요는 없을 것 같습니다. 
created 같은 경우는 responseEntity를 활용하기 어려우니 어노테이션을 써서 status를 제어한건 알겠지만 모든 api 마다 ok를 붙일 필요는 없어보여요

2022-12-28 09:17 UTC, WooSungHwan commented on src/main/java/com/prgrms/board/domain/Member.java
> +import javax.validation.constraints.Positive;
해당 어노테이션이 여기 있을 이유가 없습니다. 이 어노테이션들이 어떻게 활용되는지 참조해보셔야 할 것 같아요.
관련 로직을 테스트한 코드도 없어보이고요.

2022-12-28 09:17 UTC, WooSungHwan commented on src/main/java/com/prgrms/board/domain/Member.java
> +    }
equals and hashcode 롬복 어노테이션을 활용하여 코드를 줄여보는게 좋을 것 같습니다.

2022-12-28 09:17 UTC, WooSungHwan commented on src/main/java/com/prgrms/board/dto/CursorResult.java
> +    private Boolean hasNext;
final 이면 좀더 좋겠네요.

2022-12-28 09:17 UTC, WooSungHwan commented on src/main/java/com/prgrms/board/dto/request/PostCreateDto.java
> +    @NotBlank(message = "exception.post.title.null")
클라이언트 입장에서 post title 이 null이구나 할 수는 있겠지만 해당 메시지로 어떤  제어를 하기엔 단순히 post를 추가하려고 하는데 어떤 값이 없는지 뭔가가 넘친건지 아니면 비즈니스 로직에서 에러가 난건지 파악이 불가능해서 이후 프로그래밍이 어려울 것 같습니다.

이런 경우 서버의 에러 메시지를 클라이언트가 받아서 유저에게 보여주어 처리하거나 코드를 통해 어떤 부분이 부족한지를 정의해주어야 하는데 두 경우가 혼합되어 이도저도 아닌것처럼 보입니다.

1. 유저가 직접 보는 메시지를 만들어내어 클라이언트의 에러 메시지 처리를 용이하게 한다.
2. 클라이언트에게 에러를 정의해주어 정의된 내용으로 에러메시지를 정의할 수 있게 제공해준다.

두가지 중 하나의 방향이 성립되도록 하는게 좋을 것 같습니다.

2022-12-28 09:17 UTC, WooSungHwan commented on src/main/java/com/prgrms/board/dto/response/ApiBindErrorResponse.java
> +    }
인스턴스 생성 경로 단일화하는게 좋아보입니다.
1.생성자로 인스턴스 생성
2. static 메소드 호출 -> private 생성자 호출.

2022-12-28 09:17 UTC, WooSungHwan commented on src/main/java/com/prgrms/board/global/ApiControllerAdvice.java
> +    }
null처리 잘못해서 NullPointerException 나면 해딩 리소스를 찾을 수 없는 상태코드가 반환될텐데 왜 RuntimeException을 404로 반환하는건가요?

2022-12-28 09:17 UTC, WooSungHwan commented on src/main/java/com/prgrms/board/service/PostServiceImpl.java
> +        if (!registeredMember.equals(postUpdateMember)) {
`Objects.equals`을 사용하는 것을 권장합니다.

2022-12-28 09:21 UTC, WooSungHwan commented
테스트코드에서 assertThrow를 하는 부분이 있어서 추가로 말씀드리자면
현재 대부분의 BadRequest 처리를 IllegalArgumentException으로 처리하셨는데 이는 자바에서 이미 제공하는 exception입니다. 기서님이 짠 코드에서 의도대로 나올 수도 있고 의도하지 않은 다른 코드에서도 나올 수 있는데 실패테스트에서 하필 그부분이 걸려 본인이 의도하지 않은 같은  exception을 발생시킨다면 올바른 실패테스트라고 할 수 있을까요?

따라서 비즈니스가 들어간 부분에서는 거의 별도의 Exception을 정의하는 편이 좋습니다. 본인이 개발한, 의도한 방향대로만 Exception을 발생시켯을테니까요. 이부분도 함께 고려되면 좋을 것 같습니다.

2022-12-28 20:21 UTC, rlarltj commented on src/main/java/com/prgrms/board/JpaBoardApplication.java
> +@EnableJpaAuditing
기존에 생성한 AuditorAwareConfig에서 동작하도록 변경했습니다!

2022-12-28 20:36 UTC, rlarltj commented on src/main/java/com/prgrms/board/dto/response/ApiBindErrorResponse.java
> +    }
모든 ResponseDto에서 생성 경로가 둘 다 열려있었네요
static 메소드를 이용해 생성자를 호출하도록 변경했습니다!!

2022-12-28 21:19 UTC, rlarltj commented on src/main/java/com/prgrms/board/domain/Member.java
> +import javax.validation.constraints.Positive;
엔티티의 검증은 다른 방법을 찾아 테스트까지 진행해보겠습니다!!

2022-12-28 22:39 UTC, rlarltj commented on src/main/java/com/prgrms/board/dto/request/PostCreateDto.java
> +    @NotBlank(message = "exception.post.title.null")
@WooSungHwan 
저는 **2번**을 염두해두고 메시지를 `messages.properties`에서 관리했는데요,
제가 이 부분은 중괄호를 누락해서 에러 메시지가 `exception.post.title.null` 그대로 출력됐던 것 같습니다..ㅜ

`exception.member.name.null="이름은 필수 입력사항입니다."`
현재 value값은 위와 같은데요, 메시지에 보다 더 구체적인 정보를 담아야 할 지 궁금합니다!!

2022-12-28 22:50 UTC, rlarltj commented on src/main/java/com/prgrms/board/global/ApiControllerAdvice.java
> +    }
NullPointerException과 같은 예외는 아래 500을 반환하는 메소드에서 처리하는 것이 자연스러울까요?
코멘트 달아주신 메소드를 아예 지워도 괜찮겠다는 생각이 듭니다


    @ExceptionHandler(Exception.class) 
    @ResponseStatus(HttpStatus.INTERNAL_SERVER_ERROR)
     public ApiErrorResponse internalServerErrorHandler(Exception e) {
        String message = getMessage(e.getMessage());

        log.warn("Exception 발생-> {}", message);

        return ApiErrorResponse.fail(message, 500);
    }

2022-12-29 02:46 UTC, WooSungHwan commented on src/main/java/com/prgrms/board/global/ApiControllerAdvice.java
> +    }
runtime exception은 BAD_REQUEST로 반환하는게 적절하다는 생각이 듭니다. 그와 관련된 unchecked exception을 직접 정의하시고 본인의 비즈니스 로직에서 발생할 수 있는 비즈니스 Exception 을 정의해보시면 좋을 것 같습니다.
어제 팀미팅떄 이야기 했던 부분과 일치합니다.

2022-12-29 02:49 UTC, WooSungHwan commented on src/main/java/com/prgrms/board/global/ApiControllerAdvice.java
> +    }
NullPointerException같은 예외들도 여기 핸들러에서 모두 다 처리해야한다는 말은 아닙니다. 그런 예외들 묶어 500으로 내보내줄 수도 있지만 결국엔 잘못된 요청으로 기인한 내용이기 때문에 server internal error일수도 bad request로 볼수도 있을 것 같습니다. 다만 요청 파라미터에 의한 null pointer는 발생하지 않도록 해야곘죠.

2023-06-05 18:45 UTC, closed without merging