[1-P 이상민] JPA 게시판 만들기
prgrms-be-devcourse/SpringBoot-Board pull request #19
Opened 2021-10-14 05:43 UTC by sangmin7648

# 📌 과제 설명 

## **요구 사항**

### **SpringDataJPA 를 설정한다.**

- datasource : h2 or mysql

### **엔티티를 구성한다**

- 회원(User)
  - id (PK) (auto increment)
  - name
  - age
  - hobby
  - **created_at**
  - **created_by**
- 게시글(Post)
  - id (PK) (auto increment)
  - title
  - content
  - **created_at**
  - **created_by**
- 회원과 게시글에 대한 연관관계를 설정한다.
  - 회원과 게시글은 1:N 관계이다.
- 게시글 Repository를 구현한다. (PostRepository)

### **API를 구현한다.**

- 게시글 조회
  - 페이징 조회 (GET "/posts")
  - 단건 조회 (GET "/posts/{id}")
- 게시글 작성 (POST "/posts")
- 게시글 수정 (POST "/posts/{id}")

### **REST-DOCS를 이용해서 문서화한다.**

### 우선 요구 사항을 만족하는 과제를 올리고 추가하고 싶을걸 추가하는게 맞는거 같아 PR 올립니다 

## 특이사항

- 게시글 수정 엔드 포인트를 PATCH를 사용하도록 변경 : 수정 기능은 PUT 또는 PATCH가 맞고, 생성은 막고 싶어 PATCH로 했습니다 
- 유저 관련 기능이 없기때문에 별도로 패키지를 도메인으로 나누진 않았고, domain 패키지 밑에 유저 엔티티를 넣었습니다 

# 📌 궁금점 및 리뷰 중점 사항

- DTO를 제대로 사용하는게 처음이라서 어느 역할까지하는지 개념이 어렵네요. 데이터의 변화가 없다면 동일한 DTO 객체를 그대로 다음 레이어에 전달해도 괜찮을까요? 아니면 레이어 이동 시 구분을 위해 새로운 DTO 객체로 담아서 보내야할까요?

- PostDto의 경우 요청으로 들어오는 데이터와 나가는 데이터를 모두 담기 위해 동일한 필드에 생성자를 두개 뒀는데요, dto를 분리하는게 더 좋을까요?

- Page<T> 객체를 사용하니 너무 많고 불필요한 데이터까지 클라이언트에 반환되어 PageDto를 두고 선택한 데이터만 담아 반환하도록 했습니다. 다른 분들은 어떻게 이 문제를 해결하셨는지 궁금해요!

2021-10-14 17:08 UTC, taehyungz commented on src/main/java/com/kdt/programmers/forum/domain/Post.java
> +    private Integer userId;
User엔티티의 Id는 Long타입이므로 Post의 userId필드의 타입은 Long이 되어야 할 것 같습니다.

2021-10-14 17:08 UTC, taehyungz commented on src/main/java/com/kdt/programmers/forum/transfer/PostDto.java
> +        this.id = null;
this.id=null 이 꼭 들어가야 하는 이유가 있는지 궁굼합니다.

2021-10-14 17:15 UTC, taehyungz commented on src/main/java/com/kdt/programmers/forum/domain/Post.java
> +@Setter
https://velog.io/@aidenshin/%EB%82%B4%EA%B0%80-%EC%83%9D%EA%B0%81%ED%95%98%EB%8A%94-JPA-%EC%97%94%ED%8B%B0%ED%8B%B0-%EC%9E%91%EC%84%B1-%EC%9B%90%EC%B9%99

2021-10-14 17:34 UTC, sangmin7648 commented on src/main/java/com/kdt/programmers/forum/transfer/PostDto.java
> +        this.id = null;
@taehyungz final로 하고 싶어서 null을 줬습니다. 저 생성자가 존재하는 이유는 PR 설명에서 언급했듯 내려가는 DTO와 올라가는 DTO를 하나로 퉁쳐서 그렇습니다. 분리하는것이 맞을까요? 어떻게 생각하시나요

2021-10-14 17:37 UTC, sangmin7648 commented on src/main/java/com/kdt/programmers/forum/PostService.java
> +    @Transactional
readonly 옵션에 대해 처음알게 됐습니다 감사합니다!

2021-10-15 02:31 UTC, eunseo2 commented on src/main/java/com/kdt/programmers/forum/PostService.java
> +        postRepository.save(entity);
set을 사용하기보다는 entity.update(dto.getTitle(),dto.getContent())로
바꾸는 것을 추천드립니다😃
저번 스크럼 때 나왔지만 .save를 사용하지 않아도 JPA 더티 체킹을 통해 
변경 됩니다!

2021-10-15 02:32 UTC, eunseo2 commented on src/main/java/com/kdt/programmers/forum/PostService.java
> +    }
앞서 태형님께서 말씀해주신대로 조회는 @Transactional이
필요하지 않습니다!

2021-10-15 02:37 UTC, eunseo2 commented on src/main/java/com/kdt/programmers/forum/domain/Post.java
> +    private Integer userId;
```
   @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", referencedColumnName = "id")
    private User user;
```
위에처럼 매핑을 시키면 DB에 user_id 컬럼이 생성되는 것으로 알고 있습니다. 
 @Column(name = "user_id") 가 또 사용하신 이유가 있을까요??

2021-10-15 02:41 UTC, eunseo2 commented on src/main/java/com/kdt/programmers/forum/domain/User.java
> +
기본적으로 **단방향 매핑**으로 하고
나중에 역방향으로 객체 탐색이 꼭 필요하다고 느낄 때 추가하는 것이 좋다고 합니다😀

2021-10-15 02:52 UTC, eunseo2 commented on src/main/java/com/kdt/programmers/forum/utils/PostConverter.java
> +        return post;
post 리턴했을 때 
User, CreatedBy 둘다 null값이지 않나요?? 🙄
Post id는 GenerationType.AUTO 사용하기 때문에 dto에 id가 있을 필요가 있을까요?0?

2021-10-15 02:55 UTC, eunseo2 commented on src/main/java/com/kdt/programmers/forum/domain/Post.java
> +    private Integer userId;
```
   @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", referencedColumnName = "id")
    private User user;
```
위에처럼 매핑을 시키면 DB에 user_id 컬럼이 생성되는 것으로 알고 있습니다. 
 @Column(name = "user_id") 가 또 사용하신 이유가 있을까요??

2021-10-16 13:52 UTC, sangmin7648 commented
예외처리를 공부하면서 예외 체이닝의 중요성을 알게되어 NotFoundException을 통해 적용해봤습니다. 사실 프로젝트가 너무 작아서 별로 도움도 안되지만 잘 만들었는지 봐주시면 감사드리겠습니다!

2021-10-18 04:45 UTC, 0923kdh requested changes

2021-10-18 04:45 UTC, 0923kdh commented on src/main/java/com/kdt/programmers/forum/PostService.java
> +            return this.savePost(postRequest);
업데이트를 하는 로직인데 possibleEntity일 경우 postRequest를 저장하는 흐름이 조금 이질적으로(?) 느껴집니다! 제가 생각하기엔 업데이트를 한다는건 이미 만들어진 게시물이 있고 이 게시물을 수정한다. 로 생각이 되는데요. 업데이트를 하려고 하는데 게시물을 찾지 못했으면 예외 처리를 하는건 어떨까 생각합니다!😮

2021-10-18 04:45 UTC, 0923kdh commented on src/main/java/com/kdt/programmers/forum/domain/User.java
> +
저도 그렇게 생각합니다!

2021-10-18 04:45 UTC, 0923kdh commented on src/main/java/com/kdt/programmers/forum/PostController.java
> +            throw new NotFoundException("requested post was not found", e);
예외를 서비스랑 컨트롤러 2개 레이어에서 던지는 기준이 무엇인지 궁금합니다!

2021-10-18 04:45 UTC, 0923kdh commented on src/main/java/com/kdt/programmers/forum/transfer/request/PostRequest.java
> +        validateTitle(title);
bean validation 을 이용하셔도 좋을 것 같습니다!

2021-10-18 04:45 UTC, 0923kdh commented on src/main/java/com/kdt/programmers/forum/transfer/response/ApiResponse.java
> +    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd HH:mm:ss", timezone = "Asia/Seoul")
timezone = "Asia/Seoul"로 설정하신 이유가 있을까요 ?

2021-10-18 04:45 UTC, 0923kdh commented on src/test/java/com/kdt/programmers/forum/PostControllerTest.java
> +                    preprocessResponse(prettyPrint()),
어떤 메서드인지 궁금합니다!

2021-10-18 04:53 UTC, sangmin7648 commented on src/main/java/com/kdt/programmers/forum/PostService.java
> +            return this.savePost(postRequest);
PUT 메소드는 멱등성을 보장해야된다고 생각해서 존재하지 않으면 생성하도록 했는데요. 저도 처음에는 예외를 던지고 컨트롤러에서 예외 발생시 저장을 하도록 했는데 그렇게 되면 일반적으로 안티패턴 중 하나인 예외로 흐름제어하는게 되어 버리더라구요 ㅠㅠ 어떻게 하는게 맞을지 의견 듣고 싶습니다

2021-10-19 03:12 UTC, 0923kdh commented on src/main/java/com/kdt/programmers/forum/transfer/response/ApiResponse.java
> +    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd HH:mm:ss", timezone = "Asia/Seoul")
UTC 설정해주셔도 좋지않을까 생각합니다!

2021-10-19 03:12 UTC, 0923kdh commented on src/test/java/com/kdt/programmers/forum/PostControllerTest.java
> +                    preprocessResponse(prettyPrint()),
오! 감사합니다!

2021-10-19 03:15 UTC, 0923kdh commented
제가 다른분들 리뷰를 남길때 커밋 단위로 리뷰를 남겼었는데요. 상민님 피알 리뷰를 남기려고 커밋을 누르니..! 커밋 개수가 조금 많아서 당황(?) 했었습니다...! 이건 저의 조그마한 생각이지만 커밋 단위를 지금보단 조금 더 크게 가져가는건 어떨까 생각합니다...!!🎊🎊🎊🎊🎊🎊

2021-10-19 03:15 UTC, 0923kdh approved these changes

2021-10-19 19:33 UTC, Jo-GyuHyeon requested changes

2021-10-23 18:40 UTC, DevRunner21 reviewed
지나가다가 리뷰 남겨봅니다.ㅎㅎ

2021-10-25 19:17 UTC, Jo-GyuHyeon requested changes

2022-03-16 09:23 UTC, closed without merging