[3기-C 이동준] JPA 게시판 구현 미션 제출합니다
prgrms-be-devcourse/SpringBoot-Board pull request #210
Opened 2023-01-09 01:23 UTC by Albatross3

\## 📌 과제 설명 

## 👩‍💻 요구 사항과 구현 내용 
### **SpringDataJPA 를 설정한다.**

- [x] datasource : h2 

### **엔티티를 구성한다**

- [x] 회원(User)
    - id (PK) (auto increment)
    - name
    - age
    - hobby
    - **created_at**
    - **created_by**
- [x] 게시글(Post)
    - id (PK) (auto increment)
    - title
    - content
    - **created_at**
    - **created_by**
- [x] 회원과 게시글에 대한 연관관계를 설정한다.
    - 회원과 게시글은 1:N 관계이다.
- [x] 게시글 Repository를 구현한다. (PostRepository)

### **API를 구현한다.**

- [x] 게시글 조회
    - [x] 페이징 조회 (GET "/posts")
    - [x] 단건 조회 (GET "/posts/{id}")
- [x] 게시글 작성 (POST "/posts")
- [x] 게시글 수정 (POST "/posts/{id}")

### **REST-DOCS를 이용해서 문서화한다.**
- [x] 조회(페이징 조회, 단건 조회), 작성, 수정에 관한 API 문서

## ✅ PR 포인트 & 궁금한 점 
1.  Post 엔티티가 User 객체를 가지고 있어서 게시글이 작성될 때 User에 관한 정보가 필요합니다. Test code에서는 user 객체를 임의로 만들어서 test 하고 있지만 실제 서비스에서는 User에 관한 정보를 어떻게 가져오는지 궁금합니다. 세션이나 JWT 토큰을 이용해서 User 정보를 가져올 것 같은데 혹시 맞는지 궁금합니다
2.  Controller 단의 메소드에서 반환 형태를 **ResponseEntity<T>** 나 **custom한 ApiResponse<T>** 를 섞어서 사용하고 있는데 REST API 작성할 때는 보통 어떤 형태로 반환하는 것이 일반적인지 궁금합니다
3. 글의 작성과 수정과 같은 API 에서 일반적으로 어떤 값을 반환하는지 궁금합니다 (현재는 데이터 값으로 id를 Long으로 반환하고 있습니다)
4. REST - Docs 문서화가 잘 되었는지 궁금합니다

2023-01-09 12:40 UTC, kimziou77 requested changes

2023-01-09 12:40 UTC, kimziou77 commented on src/main/java/com/example/bulletin_board_jpa/post/Post.java
> +            this.user.getPosts().remove(this); // User -> Post 관계를 삭제
유저한테 포스트 목록을 빼앗지 말고 처리해보는 것은 어떨까요 !

2023-01-09 12:40 UTC, kimziou77 commented on src/main/java/com/example/bulletin_board_jpa/post/controller/PostController.java
> +        return new ApiResponse<>(201, save);
postService에서 save메서드를 호출해서 나온 리턴값을
설명 해줄필요가 없다면 인라인으로도 충분할 것 같고
설명 해주기 위해 변수로 분리한 것이라면 save라는 이름은 적절하지 않은 것 같습니다!

2023-01-09 12:40 UTC, kimziou77 commented on src/main/java/com/example/bulletin_board_jpa/post/controller/PostController.java
> +        System.out.println(update);
로깅용도라면 로거로 찍어보는것은 어떨까요?

2023-01-09 12:40 UTC, kimziou77 commented on src/main/java/com/example/bulletin_board_jpa/post/controller/PostController.java
> +        return new ApiResponse<>(201, save);
전체적으로 이름이 모두 자동생성된 것 같네요!

2023-01-09 12:40 UTC, kimziou77 commented on src/main/java/com/example/bulletin_board_jpa/post/dto/PutRequestDto.java
> +    private String content;
자바 17버전 쓰시는 김에 record도 사용해보세요!

2023-01-09 12:40 UTC, kimziou77 commented on src/test/java/com/example/bulletin_board_jpa/post/PostRepositoryTest.java
> +        post.setUser(user);
User나 Post가 가져야 할 최소한의 정보를 생성자를 통해 받고, setter를 없애보는 것은 어떨까요?

현재는 객체를 생성하기 위해서 항상 저 4줄이 따라다녀야 합니다. 
만약 실수로 저 중 하나를 set 하지 않으면 불안정한 객체로 사용될 것 같습니다.

예를들어 필수 속성이 하나 더 추가되었을 때를 가정한다면, 저 모든 부분을 빠짐없이 찾아가서 추가된 속성을 set 해주는 코드를 작성해주어야 하는데, 이 과정에서도 실수가 일어나기 쉬울 것 같습니다. 반대로 생성자를 변경하면 수정해야 하는 부분을 컴파일러가 잡아줄 수 있을 것 같습니다.

2023-01-09 12:40 UTC, kimziou77 commented on src/test/java/com/example/bulletin_board_jpa/BulletinBoardJpaApplicationTests.java
> +
정렬이 안 되어 있는 것 같습니다.

2023-01-09 12:40 UTC, kimziou77 commented on src/test/java/com/example/bulletin_board_jpa/post/PostRepositoryTest.java
> +//    }
😨

2023-01-09 12:40 UTC, kimziou77 commented on src/test/java/com/example/bulletin_board_jpa/user/UserRepositoryTest.java
> +        }
1테스트에는 적어도 1 Assert문을 작성해서 확인해주세요!

2023-01-09 12:40 UTC, kimziou77 commented on src/main/java/com/example/bulletin_board_jpa/post/controller/PostController.java
> +    }
이곳에서 핸들링 하도록 하신 이유가 있으신가요?

2023-01-09 12:56 UTC, kimziou77 commented
**Post 엔티티가 User 객체를 가지고 있어서 게시글이 작성될 때 User에 관한 정보가 필요합니다. Test code에서는 user 객체를 임의로 만들어서 test 하고 있지만 실제 서비스에서는 User에 관한 정보를 어떻게 가져오는지 궁금합니다. 세션이나 JWT 토큰을 이용해서 User 정보를 가져올 것 같은데 혹시 맞는지 궁금합니다**
- 저도 세션이나 인증정보를 통해서 가져온다고 생각합니다. 하지만 뭔가 명확히 말씀드릴 경험이 따로 없네요 :cry:


**Controller 단의 메소드에서 반환 형태를 ResponseEntity 나 custom한 ApiResponse 를 섞어서 사용하고 있는데 REST API 작성할 때는 보통 어떤 형태로 반환하는 것이 일반적인지 궁금합니다**
- 둘 다 보긴 했습니다. 하지만 저의 주관으로는 ApiResponse와 같이 래핑해서 사용해야 할 이유를 아직까지는 크게 못느껴서 ResponseEntity 사용을 좋아하는 것 같습니다 :)

**글의 작성과 수정과 같은 API 에서 일반적으로 어떤 값을 반환하는지 궁금합니다 (현재는 데이터 값으로 id를 Long으로 반환하고 있습니다)**
- 흠 또다시 저를 기준으로 말씀드리면,
`글의 작성` 경우에는 created status랑 새로 생성된 리소스를 식별할 수 있는 location 헤더등이 있으면 좋을 것 같고,
`글의 수정` 경우에는 2xx status 정도 반환할 것 같습니다.
이외에 추가한다고 한다면 프로젝트를 진행하면서 팀원들과 상황에 맞게 논의해서 채울 것 같아요

**REST - Docs 문서화가 잘 되었는지 궁금합니다**
- 잘 되었을 것이라고 믿습니다 :)

2023-01-13 02:49 UTC, lleellee0 commented on src/main/java/com/example/bulletin_board_jpa/BaseEntity.java
> +    private LocalDateTime createdBy;
createdAt이랑 createdBy랑 각각 어떤 의미에요?

2023-01-13 02:54 UTC, lleellee0 commented on src/main/java/com/example/bulletin_board_jpa/post/Post.java
> +    }
연관관계 편의 메서드 생각하셔서 추가하신 것 같은데, 이런식으로 그냥 추가하실게 아니라 관계가 필요한지 따져봐야합니다.
통상적인 게시판 서비스에서 누군가 작성한 게시글을 다른 사용자로 변경한다는게 존재하는 기능인가요?

2023-01-13 02:57 UTC, lleellee0 commented on src/main/java/com/example/bulletin_board_jpa/post/Post.java
> +    }
setter를 안쓸 수 없을까요 ㅎㅎ

2023-01-13 02:57 UTC, lleellee0 commented on src/main/java/com/example/bulletin_board_jpa/post/converter/PostConverter.java
> +    }
setter를 안쓸 수 없을까요 ㅎㅎ 2

2023-01-13 03:01 UTC, lleellee0 commented on src/main/java/com/example/bulletin_board_jpa/post/controller/PostController.java
> +        return new ApiResponse<>(201, save);
ㅇㅈ

2023-01-13 03:05 UTC, lleellee0 commented on src/main/java/com/example/bulletin_board_jpa/post/controller/PostController.java
> +    }
ChangeSetPersister.NotFoundException 가 뭔줄 알고 쓰고 계시는건가요?

2023-01-13 03:12 UTC, lleellee0 commented on src/main/java/com/example/bulletin_board_jpa/post/dto/PostRequestDto.java
> +    private UserDto userDto;
이번 프로젝트에 인증에 대한 내용이 없어서 그렇긴 하지만.. 인증 방법이 따로 있는 경우에도 UserDto가 필요했을까요?

2023-01-13 03:14 UTC, lleellee0 commented on src/main/java/com/example/bulletin_board_jpa/post/dto/PutRequestDto.java
> +    private String content;
이름이 PutRequestDto 라뇨... ㅋ

2023-01-13 03:15 UTC, lleellee0 commented on src/main/java/com/example/bulletin_board_jpa/post/service/PostService.java
> +        Post post = postRepository.findById(id).orElseThrow(() -> new ChangeSetPersister.NotFoundException());
왜 ChangeSetPersister.NotFoundException 를 사용하시는건지 ^^

2023-01-13 03:16 UTC, lleellee0 commented on src/main/java/com/example/bulletin_board_jpa/post/service/PostService.java
> +        post.setContent(putRequestDto.getContent());
이렇게 각각 set 해주는게 최선인가요 ㅎㅎ

2023-01-13 03:19 UTC, lleellee0 commented on src/test/java/com/example/bulletin_board_jpa/post/PostRepositoryTest.java
> +//    }
신고 해도 되나요??

2023-01-13 03:20 UTC, lleellee0 commented on src/test/java/com/example/bulletin_board_jpa/post/PostRepositoryTest.java
> +        post.setUser(user);
저도 동일한 생각입니다.
위에도 리뷰 남겨놨어요.

2023-01-13 03:40 UTC, lleellee0 commented on src/test/java/com/example/bulletin_board_jpa/user/UserRepositoryTest.java
> +        }
수빈님 리뷰 주신것도 그렇고..
모든 테스트가 스프링 컨테이너가 뜨는 통합 테스트들인데요, 혹시 단위테스트는 없을까요? ^^

2023-01-13 03:47 UTC, lleellee0 commented
동준님 수고하셨습니다.
일단 코드 전반적으로 일관성, 오타 등 여러가지로 검토가 안된 것 같은 코드들인데요..
PR 작성하시고 한번 코드를 돌아보시면 어떨까요? ^^

> Post 엔티티가 User 객체를 가지고 있어서 게시글이 작성될 때 User에 관한 정보가 필요합니다. Test code에서는 user 객체를 임의로 만들어서 test 하고 있지만 실제 서비스에서는 User에 관한 정보를 어떻게 가져오는지 궁금합니다. 세션이나 JWT 토큰을 이용해서 User 정보를 가져올 것 같은데 혹시 맞는지 궁금합니다

이거 리뷰에도 남겨놨는데 말씀하신대로 인증 수단에서 User 정보를 가져오는게 일반적입니다. :)

> Controller 단의 메소드에서 반환 형태를 ResponseEntity 나 custom한 ApiResponse 를 섞어서 사용하고 있는데 REST API 작성할 때는 보통 어떤 형태로 반환하는 것이 일반적인지 궁금합니다

가급적 애플리케이션에서 일관된 방식으로 반환하는게 좋겠죠.
양쪽 다 사용하시기 보다는 한쪽으로 통일하여 사용하시는게 좋을 것 같습니다.
안그러면 클라이언트나 API 문서를 보는 사람이 헷갈려요.

> 글의 작성과 수정과 같은 API 에서 일반적으로 어떤 값을 반환하는지 궁금합니다 (현재는 데이터 값으로 id를 Long으로 반환하고 있습니다)

id를 반환하는 경우도 일반적입니다. 왜냐하면 클라이언트에서는 AJAX 요청으로 글 작성이나 수정 한 후 반환된 id를 가지고 작성/수정된 페이지로 이동을 시켜줄 수 있을테니까요. :)

> REST - Docs 문서화가 잘 되었는지 궁금합니다

이건 안봤는데 ㅋ;;
이거 보려면 페이지를 열어봐야해서요. Controller 상으로 봤을 때는 문제 없어보입니다. 리뷰 드린 내용들 중 글 작성 요청시 User 정보를 넘긴다던지 하는 부분들은 물론 인증 수단이 추가되면 없어져야할겁니다.

2023-06-05 18:45 UTC, closed without merging