[4기 김주웅] Spring Boot JPA 게시판 구현 미션 제출합니다
prgrms-be-devcourse/SpringBoot-Board pull request #233
Opened 2023-08-01 21:49 UTC by JuwoongKim

## 📌 과제 설명 
- Spring Boot JPA - Rest API를 강의에 기반한 게시판 구현 과제입니다.
- RestDoc 적용은 다른 PR을 통해 반영할 예정입니다.

## 👩‍💻 요구 사항과 구현 내용 

### **SpringDataJPA 를 설정한다.**

- [X] datasource : h2 or mysql

### **엔티티를 구성한다.**

- [X] 회원(User)
    - id (PK) (auto increment)
    - name
    - age
    - hobby
    - **created_at**
    - **created_by**
- [X] 게시글(Post)
    - id (PK) (auto increment)
    - title
    - content
    - **created_at**
    - **created_by**
- [X] 회원과 게시글에 대한 연관관계를 설정한다.
    - 회원과 게시글은 1:N 관계이다.
- [X] 게시글 Repository를 구현한다. (PostRepository)

### **API를 구현한다.**

- [X] 게시글 조회
    - 페이징 조회 (GET "/posts")
    - 단건 조회 (GET "/posts/{id}")
- [X] 게시글 작성 (POST "/posts")
- [X] 게시글 수정 (POST "/posts/{id}")

### **REST-DOCS를 이용해서 문서화한다.**
- [ ] REST Docs 적용

## 👩‍💻 작업 수행 순서 

- [X] 프로젝트 초기화 
- [X] 데이터베이스 설정 
- [X] JPA Auditiong 기능 설정 설정
- [X] 공통 필드에 필요한 BaseEntity 추가 
- [X] User Entity 및 Repository 추가
- [X] Post Entity 및 Repository 추가 및 연관관계 설정 
- [X] User 생성 및 PK 조건 조회 기능에 대한 Controller, Service 구현
- [X] Post 생성, 수정, PK 조건 조회, 페이징 조회 기능에 대한 Controller, Service 구현

## ✅ PR 포인트 & 궁금한 점 

- 연관관계를 가지는 객체를 서비스단에서 조회해 DTO로 변경하는 과정에서 getter를 통해 필드 그대로 사용할 시 lazyloading에 따라 proxy가 그대로 유지되는 문제가 발생합니다. getField().getId() 과 같은 방법으로 오류는 피했지만 제대로된 해결방법에 대 논의하고 싶습니다.
- 학습을 위해 양뱡향 연관관계를 사용했는데 contoller에서 json으로 변환하는 과정에 순환참조에 의한 스택오버플로우 오류가 발생했습니다. 관련 애너테니션을 추가해 오류는 피했지만 제대로된 해결방법에 대해 논의하고 싶습니다.

</br>

2023-08-03 09:37 UTC, Hejow reviewed
게시판 미션 구현하느라 고생 많으셨습니다!
아직 테스트 코드를 다 작성해주시지 않아서 테스트 코드 관련해서는 나중에 한번 더 이야기하면 좋을 것 같습니다!
리뷰 가볍게 봐주시고 논의 시간에 자세하게 이야기해보면 좋을 것 같아요 😉

2023-08-03 09:37 UTC, Hejow commented on src/main/java/com/juwoong/springbootboardjpa/common/BaseEntity.java
> +public class BaseEntity {
BaseEntity가 직접적으로 사용될 일이 없을 것 같아요!
그러면 어떻게 만들면 좋을까요?

2023-08-03 09:37 UTC, Hejow commented on src/main/java/com/juwoong/springbootboardjpa/config/JpaConfig.java
> +public class JpaConfig {
혹시 따로 class 파일을 추가하신 이유가 있을까요?

2023-08-03 09:37 UTC, Hejow commented on src/main/java/com/juwoong/springbootboardjpa/post/api/PostController.java
> +    @PostMapping("/create")
Restful Api를 작성하는데 고려해보면 좋을 것 같아요!
[Restful API 작성하기](https://meetup.nhncloud.com/posts/92)를 한번 참고해보시면 좋을 것 같아요!

2023-08-03 09:37 UTC, Hejow commented on src/main/java/com/juwoong/springbootboardjpa/post/api/PostController.java
> +        return postService.searchAll(pageRequest);
다른 요청들은 `ResponseEntity<>`를 사용해서 응답을 해주고 있어요.
근데 여기서만 Page로 응답을 했는데, 이때 클라이언트가 받는 상태코드는 무엇일까요?

2023-08-03 09:37 UTC, Hejow commented on src/main/java/com/juwoong/springbootboardjpa/post/api/PostController.java
> +    public ResponseEntity<PostDto> searchById(@PathVariable("id") Long id) {
Path에 있는 변수가 동일하다면 `@PathVariable` 내부에 이름을 안 넘겨줘도 될 것 같은데 어떻게 생각하시나요??

2023-08-03 09:37 UTC, Hejow commented on src/main/java/com/juwoong/springbootboardjpa/post/api/model/PostRequest.java
> +public class PostRequest {
의논하고 싶은 의견인데 DTO에 `@Data`를 붙이는거는 어떻게 생각하시나요?

2023-08-03 09:37 UTC, Hejow commented on src/main/java/com/juwoong/springbootboardjpa/post/application/PostService.java
> +        return posts.map(this::toDto);
강의에서 스트림으로 사용하는 코드를 보여줬는데 이렇게 사용하시는데 뭔가 다른 이유가 있을 것 같아요!
혹시 어떤 의도였을까요??

2023-08-03 09:37 UTC, Hejow commented on src/main/java/com/juwoong/springbootboardjpa/post/application/PostService.java
> +        Post searchedPost = postRepository.findById(postId).get();
`Optional`을 바로 get()을 하면 문제가 생길 수도 있을 것 같은데 어떻게 생각하시나요?

2023-08-03 09:37 UTC, Hejow commented on src/main/java/com/juwoong/springbootboardjpa/post/application/PostService.java
> +        Post searchedPost = postRepository.findById(id).get();
위의 리뷰와 다른 내용으로 여러번 코드가 등장할 수 있는 것 같은데 어떻게 처리하면 좋을까요??

`@Transcation(readOnly = true)` 속성에 대해서 잘 알고 계신가요??
제가 공유드린 내용을 한번 참고 해보시고 조금 찾아보시면 도움될 것 같아요!

2023-08-03 09:37 UTC, Hejow commented on src/main/java/com/juwoong/springbootboardjpa/post/domain/Post.java
> +    @JsonBackReference
혹시 이게 말씀하신 순환 참조 문제 때문에 설정하신 부분인가요??

2023-08-03 09:37 UTC, Hejow commented on src/main/java/com/juwoong/springbootboardjpa/post/domain/Post.java
> +@Builder
빌더를 도입하신 이유가 있을까요?

2023-08-03 09:37 UTC, Hejow commented on src/main/java/com/juwoong/springbootboardjpa/post/domain/repository/PostRepository.java
> +    Page<Post> findAll(Pageable pageable);
따로 선언해두신 이유가 있는지 궁금합니다!

2023-08-03 09:37 UTC, Hejow commented on src/main/java/com/juwoong/springbootboardjpa/post/api/PostController.java
> +@RequestMapping("/api/post")
URI를 표현하는 방식에 대해서 어떻게 표현하는게 좀더 자연스러울 것 같으신가요??
```
1. /api/post
2. /api/posts
```

2023-08-03 09:37 UTC, Hejow commented on src/main/java/com/juwoong/springbootboardjpa/user/api/UserController.java
> +public class UserController {
`PostController` 쪽의 리뷰와 비슷한 맥락인 것 같습니다!
한번 참고 부탁드릴게요 😉

2023-08-03 09:37 UTC, Hejow commented on src/main/java/com/juwoong/springbootboardjpa/post/domain/Post.java
> +    public void update (String title, String content){
혹시 메서드 이름과 변수 사이의 공백이.. 오타겠쬬..!?!?!

2023-08-03 09:37 UTC, Hejow commented on src/main/java/com/juwoong/springbootboardjpa/user/application/UserService.java
> +public class UserService {
여기도 `PostService` 쪽과 비슷한 내용인 것 같습니다!
한번 참고 부탁드릴게요 😉

2023-08-03 09:37 UTC, Hejow commented on src/main/java/com/juwoong/springbootboardjpa/user/domain/User.java
> +    private List<Post> posts;
특정 경우에 어떤 값도 들어있지 않아서 `NPE`가 발생할 수 있을 것 같아요! 어떻게 생각하시나요??

2023-08-03 09:37 UTC, Hejow commented on src/main/java/com/juwoong/springbootboardjpa/user/domain/User.java
> +    private Integer age;
나이를 특별하게 Integer 타입으로 저장하신 이유가 있을까요??

2023-08-03 18:09 UTC, kys0411 commented on src/main/java/com/juwoong/springbootboardjpa/config/JpaConfig.java
> +public class JpaConfig {
저도 이부분 궁금합니다!!

2023-08-03 18:09 UTC, kys0411 commented on src/main/java/com/juwoong/springbootboardjpa/post/api/PostController.java
> +@RequestMapping("/api/post")
2번이요!!

2023-08-03 18:12 UTC, kys0411 commented on src/main/java/com/juwoong/springbootboardjpa/post/api/model/PostRequest.java
> +public class PostRequest {
저는 개인적으로 좋지 않다고 생각합니다ㅎㅎ

2023-08-03 18:14 UTC, kys0411 commented on src/main/java/com/juwoong/springbootboardjpa/user/api/model/UserRequest.java
> +    private Integer age;
age를 int가 아닌 래퍼클래스로 선언하신 이유가 궁금합니다!

2023-08-03 18:21 UTC, kys0411 requested changes
안녕하세요 주웅님!! jpa 게시판 미션 하시느라 너무 고생많으셨습니다!!
열심히 노력하신게 너무 느껴집니다 ㅜㅜ

전체적으로 희조님이랑 굉장히 겹치게 궁금한 점이 많아서 전부 일일이 코멘트를 남기진 못했지만
그래도 몇 개 적어보았습니다! 
이에 관해서는 내일 얘기해보아요👍🏻👍🏻 고생하셨습니다!

2023-08-04 03:47 UTC, JuwoongKim commented
개인 상황을 고려해 RestDoc생성을 위한 Controller 테스트 코드를 우선적으로 작성했습니다. 
확인 부탁드립니다!!

2023-08-04 12:25 UTC, JuwoongKim commented on src/main/java/com/juwoong/springbootboardjpa/post/api/PostController.java
> +    @PostMapping("/create")
0d638d0ff9676a95afa33e8636bdfb41963cd9ca 커밋 피드백 반영 
- URI를 RET API 형식을 고려하여 수정했습니다.

2023-08-04 12:34 UTC, JuwoongKim commented on src/main/java/com/juwoong/springbootboardjpa/post/api/PostController.java
> +    public ResponseEntity<PostDto> searchById(@PathVariable("id") Long id) {
0d638d0ff9676a95afa33e8636bdfb41963cd9ca 커밋 피드백 반영 
- URI를 REST API 형식을 고려하여 수정할 떄 함께 수정했습니다.

2023-08-04 12:42 UTC, JuwoongKim commented on src/main/java/com/juwoong/springbootboardjpa/common/BaseEntity.java
> +public class BaseEntity {
f80b1112e00ad22397b75a3035578f35112f29a1 커밋 피드백 반영 
- BaseEntity를 추상 클래스로 만들어 인스턴스 생성을 방지했습니다.

2023-08-04 12:58 UTC, JuwoongKim commented on src/main/java/com/juwoong/springbootboardjpa/config/JpaConfig.java
> +public class JpaConfig {
3d24ccd1af75ff383bf409129ef7e230e46bbea0 커밋 피드백 반영 
- 메인 클래스에 설정하고 불필요한 설정파일을 삭제했습니다.

초기에 Jpa 설정을 명시한다는게 지저분하다는 생각이 들었으나, 설정파일을 만드는 것이 더 지저분했고 , 오히려 테스트에서도 추가 작업을 해야했습니다.

2023-08-04 13:01 UTC, JuwoongKim commented on src/main/java/com/juwoong/springbootboardjpa/post/api/model/PostRequest.java
> +public class PostRequest {
데이터 전달 이라는 역할을 가진다는 점에서 사용해도 괜찮다고 생각합니다.
다만 해당 과정에서는 Lombok을 사용하지 않고 진행하기로 결정했습니다.

2023-08-04 13:03 UTC, JuwoongKim commented on src/main/java/com/juwoong/springbootboardjpa/post/api/PostController.java
> +@RequestMapping("/api/post")
0d638d0ff9676a95afa33e8636bdfb41963cd9ca 커밋 피드백 반영 
- URI를 REST API 형식을 고려하여 수정했습니다.

2023-08-04 13:04 UTC, JuwoongKim commented on src/main/java/com/juwoong/springbootboardjpa/post/domain/Post.java
> +    public void update (String title, String content){
오타입니다. 정렬처리 해주었어욥 ㅠㅠㅠㅎㅎ

2023-08-04 13:20 UTC, JuwoongKim commented on src/main/java/com/juwoong/springbootboardjpa/post/domain/Post.java
> +@Builder
생성자를 private으로 둠으로써 생성자를 통한 외부 생성을 막고 싶었습니다.
생각해보니, 생상자 매개변수가 많은 것도 아니고, 생성자가 많은 것도 아니여서 Builer 적용이 투 머치이지 않았나 싶습니다.

2023-08-04 13:45 UTC, JuwoongKim commented on src/main/java/com/juwoong/springbootboardjpa/post/domain/Post.java
> +@Builder
92c9877ceb09c17a166b38317b4a0f7ac2d2f8f9 커밋 피드백 반영 
- 팀 규칙에 맞게 롬북 의존성을 제거하며 현재 상황에 Builder 패턴이 불필요하다 판단해 제거했습니다.

2023-08-04 19:19 UTC, JuwoongKim commented on src/main/java/com/juwoong/springbootboardjpa/post/api/PostController.java
> +        return postService.searchAll(pageRequest);
테스트를 해보니 200을 반환하고 있습니다. 
페이징 처리를 별도로 검색하는 과정에서 ResponseEntity<>를 누락되었으나 @RestController의 @ResponseBody default 적용으로 동작이 되었던 것 같습니다.
현재 응답에 대한 제어가 명시되지 않아 추가작업을 해야하는데 기존 코드의 일관성에 맞게 ResponseEntity<>를 사용해 수정하겠습니다.

2023-08-04 19:33 UTC, JuwoongKim commented on src/main/java/com/juwoong/springbootboardjpa/post/api/PostController.java
> +        return postService.searchAll(pageRequest);
63a1399742eab1561596623518d84eb99950c03c 커밋 피드백 반영

2023-08-04 19:54 UTC, JuwoongKim commented on src/main/java/com/juwoong/springbootboardjpa/post/application/PostService.java
> +        return posts.map(this::toDto);
5366e0024852ea375c117249f142fbee58aa9d0c 커밋 피드백 반영 
- findAll의 반환 값을 고려해 메서드 체인 형식으로 간소화 했습니다.

강의의 세부 내용을 기억하지 않았습니다. 특별한 이유는 없었습니다. ^^

2023-08-04 22:10 UTC, Jo-GyuHyeon reviewed
고생하셨어요.
리뷰 코멘트가 마무리가 되셨다면 resolve 처리도 해주시면 좋을것 같아요.

2023-08-04 22:10 UTC, Jo-GyuHyeon commented on build.gradle
> +    testImplementation 'org.springframework.restdocs:spring-restdocs-mockmvc'
별거는 아니지만 구분감을 주거나 주석을 남기면 관리 하기 좋은것 같아요.

2023-08-04 22:10 UTC, Jo-GyuHyeon commented on src/main/java/com/juwoong/springbootboardjpa/post/api/PostController.java
> +    public ResponseEntity<PostDto> createPost(@RequestParam Long userId,
리소스를 표현하기 위해 RequestParam 이 아닌 path 로 userId 표현 하는것이 좋은것 같아요.
RequestParam 은 데이터 전달 하기에 적합하다고 생각해요.

2023-08-04 22:10 UTC, Jo-GyuHyeon commented on src/main/java/com/juwoong/springbootboardjpa/post/api/PostController.java
> +        headers.setContentType(MediaType.APPLICATION_JSON);
불필요하다고 생각하는데 해주는 이유는 무엇인가요?

2023-08-04 22:10 UTC, Jo-GyuHyeon commented on src/main/java/com/juwoong/springbootboardjpa/post/api/PostController.java
> +
ById 라는 접미가사 필요할까요? JPA 의 쿼리메서드의 네이밍 처럼 사용하고 계시진 않는지 확인 해보시면 좋을것 같아요.

2023-08-04 22:10 UTC, Jo-GyuHyeon commented on src/main/java/com/juwoong/springbootboardjpa/post/application/PostService.java
> +        User searchedUser = userService.searchByIdForPost(userId);
searched 라는 접두사가 필요 할까요? 다른 네이밍과 겹친다면 모르겠지만, search 라는 의미가 중요한지 잘 모르겠어요.

2023-08-04 22:10 UTC, Jo-GyuHyeon commented on src/main/java/com/juwoong/springbootboardjpa/post/application/PostService.java
> +        return toDto(post);
개행이 너무 많은것 같아요.

2023-08-04 22:10 UTC, Jo-GyuHyeon commented on src/main/java/com/juwoong/springbootboardjpa/post/application/PostService.java
> +    }
시작 로직이 없다면 return 이라도 붙여주는게 좋을것 같아요.

2023-08-04 22:10 UTC, Jo-GyuHyeon commented on src/main/java/com/juwoong/springbootboardjpa/post/application/PostService.java
> +    }
생성자 인자가 많으니 실수 있을것 같아요.
여러 기법으로 해결 가능 할 것 같아요.

2023-08-04 22:10 UTC, Jo-GyuHyeon commented on src/main/java/com/juwoong/springbootboardjpa/user/application/UserService.java
> +    }
메서드명을 보았을때 post 가 아니면 다른 도메인에서는 못사용하게 되는 걸까요??
Optional 에서 get() 을 사용 하신다면 Null 예외가 발생 할 수 있어요. (NPE)
NPE 는 발생하면 안됀다고 생각해요.

2023-08-04 23:33 UTC, JuwoongKim commented on src/main/java/com/juwoong/springbootboardjpa/post/application/PostService.java
> +        Post searchedPost = postRepository.findById(id).get();
readOnly설정 시 하이버네이트 플러시 모드가 manual이 되어
강제로 플러시를 호출하지 않는한 플러시 연산이 일어나지 않습니다.
또한 이에 따라 변경 감지에 대한 스냅샷 연산도 발생하지 않습니다.

이러한 점에서 조회시 사용하면 좋다고 생각합니다.

다만 공유해주신 자료를 보니 read only가 적절히 반영되는지 체크해야할 필요성이 느껴집니다.

2023-08-04 23:47 UTC, JuwoongKim commented on src/main/java/com/juwoong/springbootboardjpa/post/application/PostService.java
> +        Post searchedPost = postRepository.findById(id).get();
2e1b792bd0f5e0e72cc44169d561ca86a30c45b7 커밋 피드백 반영 
- 여러번 반복되는 코드를 private한 메서드로 묶어주었습니다.
- 조회에 대한 메서드에 transactoin read only 설정을 해주었습니다.

2023-08-04 23:48 UTC, JuwoongKim commented on src/main/java/com/juwoong/springbootboardjpa/post/application/PostService.java
> +        Post searchedPost = postRepository.findById(postId).get();
2e1b792bd0f5e0e72cc44169d561ca86a30c45b7 커밋 피드백 반영 
- orElseThrow 메서드를 사용해 값이 없을 때 NoSuchElementException 예외가 발생하도록 했습니다.

2023-08-04 23:57 UTC, JuwoongKim commented on src/main/java/com/juwoong/springbootboardjpa/post/domain/repository/PostRepository.java
> +    Page<Post> findAll(Pageable pageable);
내부적으로 제공되는 메서드를 다시 정의했네요!!
제거하도록 하겠습니다.

2023-08-04 23:57 UTC, JuwoongKim commented on src/main/java/com/juwoong/springbootboardjpa/post/domain/repository/PostRepository.java
> +    Page<Post> findAll(Pageable pageable);
ac15ae53e05dad5ff8b047ba8a054c190c53dc94 커밋 피드백 반영

2023-08-05 00:00 UTC, JuwoongKim commented on src/main/java/com/juwoong/springbootboardjpa/user/domain/User.java
> +    private Integer age;
ac15ae53e05dad5ff8b047ba8a054c190c53dc94 커밋 피드백 반영 
- 원시타입으로 변경했습니다.

2023-08-05 00:03 UTC, JuwoongKim commented on src/main/java/com/juwoong/springbootboardjpa/user/api/model/UserRequest.java
> +    private Integer age;
0d638d0ff9676a95afa33e8636bdfb41963cd9ca 커밋 피드백 반영 
- 요청에 대한 값이 없을 때 null로 받을 수 있도록 하기 위해 Integer를 사용했었습니다.
- 리뷰를 진해아며 받는 것이 더 안좋다라는 것을 알게되었고 해당 객체를 record로 변경하며 수정했습니다.

2023-08-05 00:07 UTC, JuwoongKim commented on src/main/java/com/juwoong/springbootboardjpa/user/api/UserController.java
> +public class UserController {
2e1b792bd0f5e0e72cc44169d561ca86a30c45b7 - 커밋 피드백 반영 
- PostController와 동일합니다.

2023-08-05 00:07 UTC, JuwoongKim commented on src/main/java/com/juwoong/springbootboardjpa/user/application/UserService.java
> +public class UserService {
2e1b792bd0f5e0e72cc44169d561ca86a30c45b7 - 커밋 피드백 반영 
- PostController와 동일합니다.

2023-08-05 00:11 UTC, JuwoongKim commented on src/main/java/com/juwoong/springbootboardjpa/user/domain/User.java
> +    private List<Post> posts;
c1591f6128a802c6ff18cf4120a1e3b7e8939edb 커밋 피드백 반영 
- 초기화 해줌으로써 NPE가 발생 가능성을 방지하도록 했습니다.

2023-08-05 00:22 UTC, JuwoongKim commented on build.gradle
> +    testImplementation 'org.springframework.restdocs:spring-restdocs-mockmvc'
79ee5298b0b887612cbaae96e8da95d413572f73 커밋 피드백 반영 
- 사용 목적별로 구분하고 주석을 남겼습니다.

2023-08-05 00:50 UTC, JuwoongKim commented on src/main/java/com/juwoong/springbootboardjpa/post/api/PostController.java
> +
119ac4caeb63231a03c4cbaf4b5f6f3fb8d9e7b3 커밋 피드백 반영 
- 쿼리메서드를 의식해서 작성한 것 맞습니다.
- id를 통한 조회 의미를 전달하고 싶었는데, 뒤의 파라미터가 충분히 의미를 전달할 것 같습니다.
- 따라서 ById 가 불필요하다고 생각해 삭제했습니다.

2023-08-05 01:17 UTC, JuwoongKim commented on src/main/java/com/juwoong/springbootboardjpa/post/api/PostController.java
> +    public ResponseEntity<PostDto> createPost(@RequestParam Long userId,
37c306721bc7607f5cede093fdb166459eda5973 커밋 피드백 반영 
- 작원 식별 및 식별자를 전달할 때 경로변수가 적합함을 학습하고 반영했습니다.

2023-08-05 02:35 UTC, JuwoongKim commented on src/main/java/com/juwoong/springbootboardjpa/post/api/PostController.java
> +        headers.setContentType(MediaType.APPLICATION_JSON);
463449bbe6a176d913718fbf9882ffdc990683f7 커밋 피드백 반영 
- @RestController, 또는 @ResponseBody의 정확한 역할을 생각하지 않고 사용했습니다.
- 애너테이션을 통해 프레임워크가 ContentType정을 해주기 때문에 불필요하다 생각해 제거했습니다.

2023-08-05 02:37 UTC, JuwoongKim commented on src/main/java/com/juwoong/springbootboardjpa/post/application/PostService.java
> +        User searchedUser = userService.searchByIdForPost(userId);
119ac4caeb63231a03c4cbaf4b5f6f3fb8d9e7b3 커밋 피드백 반영 
- 어색하다고 생각해 getPost 로 수정했습니다.
- 유사한 메서드명도 함께 수정했습니다.

2023-08-05 02:47 UTC, JuwoongKim commented on src/main/java/com/juwoong/springbootboardjpa/post/application/PostService.java
> +        return toDto(post);
7e4c65e317e062ff6ea3d273077f4504e5ccc030 커멋피드백 반영

2023-08-05 02:49 UTC, JuwoongKim commented on src/main/java/com/juwoong/springbootboardjpa/post/application/PostService.java
> +    }
7e4c65e317e062ff6ea3d273077f4504e5ccc030 커밋 피드백 반영

2023-08-05 02:52 UTC, JuwoongKim commented on src/main/java/com/juwoong/springbootboardjpa/user/application/UserService.java
> +    }
2e1b792bd0f5e0e72cc44169d561ca86a30c45b7 커밋 피드백 반영 
- Optional에서 제공하는 orElseThrow 메서드를 사용해 Null 예외 발생을 방지했습니다.

2023-08-05 04:00 UTC, JuwoongKim commented on src/main/java/com/juwoong/springbootboardjpa/post/application/PostService.java
> +    }
603644ccfa5a9e5fbdbbac029567b066bc854cf5 커밋 피드백 반영 
- 엔티티를 인자로 받는 Custom 생성자를 만들고 내부에 전체 생성자를 호출하는 방식으로 dto 필드값을 초기화했습니다.
- 처음 인자가 많다는 조건만 보고 빌더 패턴을 생각헀지만 Record에 대한 사용이 어색했고, 가능하지도 않았습니다.

2023-08-05 06:03 UTC, JuwoongKim commented on src/main/java/com/juwoong/springbootboardjpa/post/domain/Post.java
> +    @JsonBackReference
맞습니다 히조님.  
자료 검색해서 오류발생없이 동작하도록 했지만 근본적인 해결책은 아니라는 생각이 들어요 
또 양방향 연관관계에 따른 lazyloading 문제랑도 관련 있어보이고요. 
규현팀 이슈공유에 자세한 상황을 써놓았는데, 괜찮으시면 같이 논의해보고 싶습니다!

2023-08-05 09:12 UTC, kys0411 commented on src/main/java/com/juwoong/springbootboardjpa/post/api/PostController.java
> +    @PostMapping("/create")
주웅님 @PostMapping() <- 이 괄호도 빼주시면 좋을 것 같아요!

2023-08-05 15:10 UTC, Jo-GyuHyeon commented on src/main/java/com/juwoong/springbootboardjpa/post/application/PostService.java
> +    }
빌더패턴이 불가 하지 않을거라 생각해요. 빌더 패턴 말고 다른 방식은 또 없었을지.. 생각 해보면 좋을것 같아요. (반영 해야 한다는 말은 아니에요)

2023-08-05 23:02 UTC, HyoungUkJJang reviewed
안녕하세요 주웅님 ~! JPA 과제 진행하시느라 고생하셨습니당 :) 

먼저 팀원분들과 멘토님께서 활발하게 리뷰를 해주셨네요 ! 
저도 간단하게 몇개 남겨 봤습니다 ~ 참고해 보시구 주웅님도 의견을 자유롭게 말씀해주세요 !

2023-08-05 23:02 UTC, HyoungUkJJang commented on src/main/java/com/juwoong/springbootboardjpa/post/api/PostController.java
> +    }
path로 유저의 id를 받아 게시글을 생성하는 것 같습니다.  다른 방법으로 PostRequest의 필드에 userId를 추가해서 처리하는 부분은 어떻게 생각하시나요?

추가적으로 여기서는 userId로 사용되고 있지만 게시글을 조회하는 GetMapping에서는 id의 path가 게시글에 대한 id겠죠? 저는 조금 헷갈리는 포인트라고 생각해요 이 부분도 고민해보시면 좋을 것 같습니다 :)

2023-08-05 23:02 UTC, HyoungUkJJang commented on src/main/java/com/juwoong/springbootboardjpa/post/api/PostController.java
> +        @RequestParam(defaultValue = "2") int size) {
defaultValue가 2인 이유는 무엇일까용?

2023-08-05 23:02 UTC, HyoungUkJJang commented on src/main/java/com/juwoong/springbootboardjpa/post/api/model/PostRequest.java
> +public record PostRequest(String title, String content) {
네이밍이 조금 아쉬운 것 같아요 조금 더 고민해보시면 좋을 것 같습니다 ~!

2023-08-05 23:02 UTC, HyoungUkJJang commented on src/main/java/com/juwoong/springbootboardjpa/post/application/PostService.java
> +    private final UserService userService;
UserSerivce에 모든 기능들이 제공이 될 것 같네요? 이 부분에 대해서 주웅님의 의견은 어떠신가요?

2023-08-05 23:02 UTC, HyoungUkJJang commented on src/main/java/com/juwoong/springbootboardjpa/user/domain/repository/UserRepository.java
> +    //@EntityGraph(attributePaths = "posts")
불필요한 주석은 제거해주세용 ~

2023-08-05 23:02 UTC, HyoungUkJJang commented on src/main/java/com/juwoong/springbootboardjpa/post/application/PostService.java
> +    }
```suggestion
    private Post findById(Long id) {
        return postRepository.findById(id)
              .orElseThrow(() -> new NoSuchElementException("게시물이 존재하지 않습니다."));
    }
```

2023-08-05 23:02 UTC, HyoungUkJJang commented on src/test/java/com/juwoong/springbootboardjpa/SpringbootBoardJpaApplicationTests.java
> +class SpringbootBoardJpaApplicationTests {
올라오지 않아도 될 테스트인 것 같아요 ~

2023-08-06 01:03 UTC, Jo-GyuHyeon commented on src/main/java/com/juwoong/springbootboardjpa/user/application/UserService.java
> +    public User getUserByIdForPost(Long id) {
ForPost 라는 접미사가 붙은것을 보았을때 Post 말고는 다른 곳에서는 사용이 불가 하게 느껴지네요.
접미사가 필요 했을까요?

2023-08-06 01:03 UTC, Jo-GyuHyeon commented on src/main/java/com/juwoong/springbootboardjpa/user/application/UserService.java
> +public class UserService {
class 단위에 Transactional 어노테이션이 없었다면 문제가 없지만 class 단위에서 기본 속성으로 read-only 를 하지 않아 모든 메서드에서 트랜잭션으로 처리가 될 것이며 실수로 데이터가 변경 될 수도 있다고 생각해요.

2023-08-06 13:20 UTC, JuwoongKim commented on src/main/java/com/juwoong/springbootboardjpa/post/api/PostController.java
> +    @PostMapping("/create")
e36a68d77745dcee9bdd8c67f1ffd58a4db259a3 커밋 피드백
- 설정이 필요없는 에너테이션에 대한 괄호처리를 제거했습니다!

2023-08-06 13:24 UTC, JuwoongKim commented on src/main/java/com/juwoong/springbootboardjpa/post/application/PostService.java
> +    }
구두로 추가 리뷰를 진행했습니다.
- 반드시 dto가 flat 할 필요가 없다.

2023-08-06 13:35 UTC, JuwoongKim commented on src/main/java/com/juwoong/springbootboardjpa/post/api/PostController.java
> +    }
네 말씀하신대로  id라고 명시했을 때 헷갈릴 포인트가 될 것이라 생각합니다. 
수정하도록 하겠습니다.
PostRequset에 멤버 변수로 넣는 방법도 괜찮은 것 같습니다. 
다만 rest api에 해대 학습하며 식별자를 보낼 때 경로 변수로 보내주는게 적합하다고 생각해 사용해봤습니다.

2023-08-06 13:43 UTC, JuwoongKim commented on src/main/java/com/juwoong/springbootboardjpa/post/api/PostController.java
> +    }
c02d845bfaa3d5152f2fdedaea3662d592736f05 커밋 피드백 반영 
- 정확한 의미전달을 유저 식별자에 대한 변수를 id에서 userId로 변경했습니다.

2023-08-06 14:00 UTC, JuwoongKim commented on src/test/java/com/juwoong/springbootboardjpa/SpringbootBoardJpaApplicationTests.java
> +class SpringbootBoardJpaApplicationTests {
4fbb219556803cf96bb8bf3b14f1f6526ec6820f 커밋 피드백 반영 
- 불필요한 테스트 파일이라 생각해 삭제했습니다!

2023-08-06 17:28 UTC, JuwoongKim commented on src/main/java/com/juwoong/springbootboardjpa/post/api/PostController.java
> +        @RequestParam(defaultValue = "2") int size) {
68bb7b37ea45027f7d5bb465be71beb18a648785 커밋 피드백 반영
- 큰 이유가 없었습니다.
- 고려할 점이 많지만 우선적으로 @PageableDefaul 의 defatul 값인 10을 기준으로 잡아 수정했습니다.

2023-08-06 17:34 UTC, JuwoongKim commented on src/main/java/com/juwoong/springbootboardjpa/post/api/PostController.java
> +    }
https://github.com/prgrms-be-devcourse/springboot-board-jpa/pull/233#discussion_r1284877100
멘토님 해당 부분에 대해서 규현멘토님 리뷰를 반영했던 적이 있습니다.
우선은 이렇게 반영하고 추가적으로 말씀해주신 내용을 학습해서 대화해보는 것을 어떨까요?? (id를 헤더에 넣어 전달) 
약간의 시간을 갖고 생각해보고 싶습니다.

2023-08-06 17:53 UTC, JuwoongKim commented on src/main/java/com/juwoong/springbootboardjpa/post/application/PostService.java
> +    private final UserService userService;
cb499458d3c479e5075d6a6ed7a5c1bd79db1025 커밋 피드백 반영 
- 대화를 통해 논의한 Provider 인터페이스를 반영해 제공 기능을 축소시켰봤습니다.

2023-08-06 18:06 UTC, JuwoongKim commented on src/main/java/com/juwoong/springbootboardjpa/post/application/PostService.java
> +    }
25e73139a46178b65ee7099f8d01748990c64474 커밋 피드백 반영 
- 한줄에 점 하나씩!! 꼼꼼하게 하겠습니다

2023-08-06 18:08 UTC, JuwoongKim commented on src/main/java/com/juwoong/springbootboardjpa/user/application/UserService.java
> +    public User getUserByIdForPost(Long id) {
cb499458d3c479e5075d6a6ed7a5c1bd79db1025 커밋 피드백 반영 
- provideUser 라는 네이밍을 적용해봤습니다.

2023-08-06 18:26 UTC, JuwoongKim commented on src/main/java/com/juwoong/springbootboardjpa/user/application/UserService.java
> +public class UserService {
4655d7efb9d00821369973b2ec56a0e6cb1d7284 커밋 피드백 반영 
- class의 transaction 기본설정을 read-only로 하고 쓰기 작업에 별도로 transaction을 추가했습니다.

2023-08-06 18:47 UTC, JuwoongKim commented on src/main/java/com/juwoong/springbootboardjpa/post/api/model/PostRequest.java
> +public record PostRequest(String title, String content) {
8b8bbfdd867af265c632a50ed95d816f1e0c7599 커밋 피드백 반영
- sealed 클래스와 내부 record 조합을 사용해 의미 전달을 높였습니다.

2023-08-07 14:37 UTC, Jo-GyuHyeon commented on src/main/java/com/juwoong/springbootboardjpa/user/application/UserService.java
> +    public User getUserByIdForPost(Long id) {
제가 축약해서 말씀드려서 의미전달이 조금 의도와 다르게 된것 같아요.
메서드명에서 특정 도메인을 언급 하지 않으시는게 좋겠다고 생각해요.
객체의 행위가 네이밍으로써 특정 도메인을 위해 존재 한다는게 어색하게 느껴져요.
한번 고려 해주셨으면 좋겠어요.

2023-08-09 08:03 UTC, JuwoongKim commented on src/main/java/com/juwoong/springbootboardjpa/user/application/UserService.java
> +    public User getUserByIdForPost(Long id) {
bf1245dc77a33b783c45c2c0770b61edec8c87dd 커밋 피드백 반영 
- 도메인에 얽메이지 않고 게시물 작성자를 요청한다는 기능에 중점을 두어 getAuthor 라는 네이밍을 해줬습니다.

2023-08-09 16:35 UTC, merged