[1기-P] 김다희 - JPA 게시판 구현하기
prgrms-be-devcourse/SpringBoot-Board pull request #30
Opened 2021-10-15 04:41 UTC by 0923kdh

2021-10-15 10:04 UTC, taehyunnn reviewed
테트리스 장인 다희님 코드 깔끔하네요 ㅎ
옥상에서 늦게까지 공부도 열심히 하시고
질문도 많이 하는 모습 멋집니다!!
따봉~ 👍

2021-10-16 07:38 UTC, 0923kdh commented
@sangmin7648 @eunseo2 리뷰 부탁 드립니다!

2021-10-16 13:39 UTC, sangmin7648 requested changes

2021-10-16 13:39 UTC, sangmin7648 commented on src/main/java/com/prgrms/board/dto/post/PostCreateRequest.java
> +}
```suggestion
public record PostCreateRequest(
        @Positive 
        Long userId,
        
        @NotBlank(message = "제목이 비어있습니다.") @Length(max = 250) 
        String title,
        
        String content
        ) {
}
```

레코드 어떻게 쓰는지 잘모르지만, 일단 포메팅을 한번 바꿔봤습니다! 저렇게해도 돌아가는지 궁금하네요 ㅋㅋㅋ

2021-10-16 13:39 UTC, sangmin7648 commented on src/main/java/com/prgrms/board/error/ValidErrorResponse.java
> +public record ValidErrorResponse(String field, String message) {
```suggestion
public record InvalidErrorResponse(String field, String message) {
```
validityerror, validationerror 등등 다양한게 될 수 있지만 validError는 어감이 조금 이상한거 같아요 🤔

2021-10-16 13:39 UTC, sangmin7648 commented on src/main/java/com/prgrms/board/error/ValidExceptionHandler.java
> +public class ValidExceptionHandler {
```suggestion
public class InvalidExceptionHandler {
```

마찬가지로 또는 NotValidExceptionHandler가 어떤가요?

2021-10-16 13:39 UTC, sangmin7648 commented on src/main/java/com/prgrms/board/service/PostService.java
> +        return new IdResponse(postRepository.save(post).getId());
여기 뭘 저장하는건가요?

2021-10-16 13:39 UTC, sangmin7648 commented on .gitignore
> +/src/main/resources/application.yml
설정파일을 숨긴이유가 뭔가요? 실행은 제외하고 코드만 올리는게 목표이셨으면 maven 관련 파일들도 제외하고 올리고, mysql 비밀번호 숨기는게 목표였다면 닷파일이나 환경변수로 비번만 설정하고 나머지 설정은 올리는것도 좋을거 같아요!!  프로젝트를 돌려보지 못해서 아쉽습니다 🤣

2021-10-16 14:00 UTC, sangmin7648 commented on src/main/java/com/prgrms/board/error/ValidExceptionHandler.java
> +}
저도 궁금합니다. 개인적으로 분리가 필요하다고 느끼기전에는 하나에 있는게 깔끔한거 같아서요!

2021-10-16 15:01 UTC, eunseo2 commented on src/main/java/com/prgrms/board/controller/PostController.java
> +    @PutMapping("/{postId}")
PostModifyRequest에서 title, content만 
변경되는데 Patch 대신 Put을 쓴 이유가 있을까요??

2021-10-16 15:15 UTC, eunseo2 commented on src/main/java/com/prgrms/board/dto/IdResponse.java
> +}
엇 저도 궁금합니다! 
Controller 단에서 Long id 바로 반환하면 안좋은 점이 있나요? 😳

2021-10-16 15:43 UTC, eunseo2 commented on src/main/java/com/prgrms/board/controller/PostController.java
> +    @GetMapping("/list")
createPost에 @PostMapping을 부분 처럼
@GetMapping("/list") 대신 @GetMapping만 해도 좋을 거 같습니다!

2021-10-17 08:56 UTC, sangmin7648 commented on src/main/java/com/prgrms/board/controller/PostController.java
> +    @PutMapping("/{postId}")
@eunseo2  저도 처음에는 Patch로 했었는데요, title과 content를 각각 별도로 업데이트하는 api를 제공하지 않는 이상 patch를 사용하는것이 적절한거 같지 않더라구요!

2021-10-18 16:07 UTC, 0923kdh commented on src/test/java/com/prgrms/board/repository/PostRepositoryTest.java
> +class PostRepositoryTest {
이 부분은 적용해보았더니 오류가 .. 납니다!...

2021-10-18 16:08 UTC, 0923kdh commented on src/main/java/com/prgrms/board/BoardApplication.java
> +@EnableJpaAuditing
https://webcoding-start.tistory.com/53 요 블로그 첫 문단을 참고하시면 금방 이해될 것 같습니다~!

2021-10-18 16:17 UTC, 0923kdh commented on src/main/java/com/prgrms/board/error/GlobalExceptionHandler.java
> +                        .build());
음 저는 이부분은 빌더가 더 좋은 것 같아요! 인자 순서를 맞춰서 코드를 짜야하는게 개인적으로는 너무 불편해서요.

2021-10-18 16:18 UTC, 0923kdh commented on src/main/java/com/prgrms/board/service/PostService.java
> +        return new IdResponse(postRepository.save(post).getId());
저도 이 부분에 대해서는 고민이 많긴한데, 코드가 길어졌을 경우에는 조금 더 자세한 변수명이 편리하다고 생각이 들어서 최대한 자세한 변수명으로 적으려고는 하고 있습니다.!

2021-10-18 16:19 UTC, 0923kdh commented on src/main/java/com/prgrms/board/controller/PostController.java
> +    public ResponseEntity<Page<PostFindResponse>> findAllPostByUserId(Pageable pageable, final @RequestBody Long userId) {
오 이 부분은 더 알아보겠습니다! 감사합니다 ㅎㅎ

2021-10-18 16:20 UTC, 0923kdh commented on src/main/java/com/prgrms/board/error/ValidErrorResponse.java
> +public record ValidErrorResponse(String field, String message) {
InvalidErrorResponse 로 반영하였습니다!

2021-10-18 16:21 UTC, 0923kdh commented on src/main/java/com/prgrms/board/error/ValidExceptionHandler.java
> +public class ValidExceptionHandler {
이 부분도 InValidExceptionHandler로 적용하였습니다~

2021-10-19 01:32 UTC, hanjo8813 reviewed
지나가다 들렸읍니다. 정말 잘하셨네요 
스윽 보고 갑니다~

2021-10-19 01:32 UTC, hanjo8813 commented on src/main/java/com/prgrms/board/service/PostService.java
> +public class PostService {
다희님 하이~ 지나가다 들렸는데요
클래스 전체에 `@Transactional(readOnly = true)`로 범위를 좁혀서 걸어놓고,
조회하는 메소드에는 어노테이션을 생략하구 테이블 변경시키는 어노테이션에만 `@Transactional` 달아줘도 될것 같아여
지금 어노테이션이 중복되서 쫌 들어가있는것 같아서용

2021-10-19 01:32 UTC, hanjo8813 commented on src/main/java/com/prgrms/board/domain/User.java
> +    }
다희님 언제부터 이렇게 객체지향적 사람으로 성장하셨나요 
저도 객체지향맨이 되기 위해 분발하겠습니다

2021-10-19 01:32 UTC, hanjo8813 commented on src/main/java/com/prgrms/board/controller/PostController.java
> +    public ResponseEntity<IdResponse> modifyPost(final @PathVariable Long id, final @Valid @RequestBody PostModifyRequest postModifyRequest){
요거 PATCH 메소드가 더 Restful 할것같아요~~

2021-10-23 15:07 UTC, Jo-GyuHyeon requested changes

2021-10-23 15:27 UTC, Jo-GyuHyeon requested changes

2021-10-24 13:09 UTC, DevRunner21 reviewed
지나가다가 리뷰 남겨봅니다.

전체적으로 좋은 코드를 짜기 위해 엄청 고민하고 노력하셨다는게 보이는 코드였습니다!
저도 이렇게 열정적으로 해야하는데 ㅜㅜ 반성하고 갑니다.

2022-03-16 09:22 UTC, closed without merging