[1기 -P] 권태형 - JPA 게시판 구현하기
prgrms-be-devcourse/SpringBoot-Board pull request #34
Opened 2021-10-15 14:10 UTC by taehyungz

## 📌 과제 설명 
-  Spring Boot JPA로 게시판 구현

## ✅ PR 포인트 & 궁금한 점 

## ✅ 피드백 반영사항

## 👩‍💻 요구 사항과 구현 내용
- Spring Data JPA를 설정한다.(h2 database 사용)
- 엔티티를 구성한다.
- API를 구현한다.
- 테스트코드를 작성한다.
- REST-DOCS를 이용해 문서화 한다.

## API 구현

### 게시글 작성

#### (POST) /api/posts

Request

    POST /api/posts HTTP/1.1
    Content-Type: application/json;charset=UTF-8
    Accept: application/json
    Content-Length: 39
    Host: localhost:8080
    Cookie: userid=1
    
    {"title":"제목1","content":"내용1"}

<table class="tableblock frame-all grid-all stretch"><colgroup><col style="width: 33.3333%;"> <col style="width: 33.3333%;"> <col style="width: 33.3334%;"></colgroup> 

<thead>

<tr>

<th class="tableblock halign-left valign-top">Path</th>

<th class="tableblock halign-left valign-top">Type</th>

<th class="tableblock halign-left valign-top">Description</th>

</tr>

</thead>

<tbody>

<tr>

<td class="tableblock halign-left valign-top">

`title`

</td>

<td class="tableblock halign-left valign-top">

`String`

</td>

<td class="tableblock halign-left valign-top">

게시글 제목

</td>

</tr>

<tr>

<td class="tableblock halign-left valign-top">

`content`

</td>

<td class="tableblock halign-left valign-top">

`String`

</td>

<td class="tableblock halign-left valign-top">

게시글 내용

</td>

</tr>

</tbody>

</table>

Response

    HTTP/1.1 200 OK
    Content-Type: application/json;charset=UTF-8
    Content-Length: 102
    
    {"statusCode":200,"message":"게시글 생성 성공","data":1,"serverDatetime":"2021-10-15 22:23:10"}

<table class="tableblock frame-all grid-all stretch"><colgroup><col style="width: 33.3333%;"> <col style="width: 33.3333%;"> <col style="width: 33.3334%;"></colgroup> 

<thead>

<tr>

<th class="tableblock halign-left valign-top">Path</th>

<th class="tableblock halign-left valign-top">Type</th>

<th class="tableblock halign-left valign-top">Description</th>

</tr>

</thead>

<tbody>

<tr>

<td class="tableblock halign-left valign-top">

`statusCode`

</td>

<td class="tableblock halign-left valign-top">

`Number`

</td>

<td class="tableblock halign-left valign-top">

HTTP 상태코드

</td>

</tr>

<tr>

<td class="tableblock halign-left valign-top">

`message`

</td>

<td class="tableblock halign-left valign-top">

`String`

</td>

<td class="tableblock halign-left valign-top">

응답 설명

</td>

</tr>

<tr>

<td class="tableblock halign-left valign-top">

`data`

</td>

<td class="tableblock halign-left valign-top">

`Number`

</td>

<td class="tableblock halign-left valign-top">

작성된 게시글 번호

</td>

</tr>

<tr>

<td class="tableblock halign-left valign-top">

`serverDatetime`

</td>

<td class="tableblock halign-left valign-top">

`String`

</td>

<td class="tableblock halign-left valign-top">

서버 응답시간

</td>

</tr>

</tbody>

</table>

### 게시글 수정

#### (PUT) /api/posts/{id}

Request

    PUT /api/posts/1 HTTP/1.1
    Content-Type: application/json;charset=UTF-8
    Accept: application/json
    Content-Length: 51
    Host: localhost:8080
    Cookie: userid=1
    
    {"title":"수정제목1","content":"수정내용1"}

<table class="tableblock frame-all grid-all stretch"><colgroup><col style="width: 33.3333%;"> <col style="width: 33.3333%;"> <col style="width: 33.3334%;"></colgroup> 

<thead>

<tr>

<th class="tableblock halign-left valign-top">Path</th>

<th class="tableblock halign-left valign-top">Type</th>

<th class="tableblock halign-left valign-top">Description</th>

</tr>

</thead>

<tbody>

<tr>

<td class="tableblock halign-left valign-top">

`title`

</td>

<td class="tableblock halign-left valign-top">

`String`

</td>

<td class="tableblock halign-left valign-top">

게시글 제목

</td>

</tr>

<tr>

<td class="tableblock halign-left valign-top">

`content`

</td>

<td class="tableblock halign-left valign-top">

`String`

</td>

<td class="tableblock halign-left valign-top">

게시글 내용

</td>

</tr>

</tbody>

</table>

Response

    HTTP/1.1 200 OK
    Content-Type: application/json;charset=UTF-8
    Content-Length: 102
    
    {"statusCode":200,"message":"게시글 수정 성공","data":1,"serverDatetime":"2021-10-15 22:23:10"}

<table class="tableblock frame-all grid-all stretch"><colgroup><col style="width: 33.3333%;"> <col style="width: 33.3333%;"> <col style="width: 33.3334%;"></colgroup> 

<thead>

<tr>

<th class="tableblock halign-left valign-top">Path</th>

<th class="tableblock halign-left valign-top">Type</th>

<th class="tableblock halign-left valign-top">Description</th>

</tr>

</thead>

<tbody>

<tr>

<td class="tableblock halign-left valign-top">

`statusCode`

</td>

<td class="tableblock halign-left valign-top">

`Number`

</td>

<td class="tableblock halign-left valign-top">

HTTP 상태코드

</td>

</tr>

<tr>

<td class="tableblock halign-left valign-top">

`message`

</td>

<td class="tableblock halign-left valign-top">

`String`

</td>

<td class="tableblock halign-left valign-top">

응답 설명

</td>

</tr>

<tr>

<td class="tableblock halign-left valign-top">

`data`

</td>

<td class="tableblock halign-left valign-top">

`Number`

</td>

<td class="tableblock halign-left valign-top">

수정된 게시글 번호

</td>

</tr>

<tr>

<td class="tableblock halign-left valign-top">

`serverDatetime`

</td>

<td class="tableblock halign-left valign-top">

`String`

</td>

<td class="tableblock halign-left valign-top">

서버 응답시간

</td>

</tr>

</tbody>

</table>

### 게시글 단건 조회
#### (GET) /api/posts/{id}

Request

    GET /api/posts/1 HTTP/1.1
    Host: localhost:8080

Response

    HTTP/1.1 200 OK
    Content-Type: application/json;charset=UTF-8
    Content-Length: 359
    
    {"statusCode":200,"message":"게시글 단건 조회 성공","data":{"id":1,"title":"제목1","content":"내용1","userResponse":{"userId":1,"name":"유저1","age":25,"hobby":"TV","createdAt":"2021-10-15T22:23:10","modifiedAt":"2021-10-15T22:23:10"},"createdAt":"2021-10-15T22:23:10","modifiedAt":"2021-10-15T22:23:10"},"serverDatetime":"2021-10-15 22:23:10"}

<table class="tableblock frame-all grid-all stretch"><colgroup><col style="width: 33.3333%;"> <col style="width: 33.3333%;"> <col style="width: 33.3334%;"></colgroup> 

<thead>

<tr>

<th class="tableblock halign-left valign-top">Path</th>

<th class="tableblock halign-left valign-top">Type</th>

<th class="tableblock halign-left valign-top">Description</th>

</tr>

</thead>

<tbody>

<tr>

<td class="tableblock halign-left valign-top">

`statusCode`

</td>

<td class="tableblock halign-left valign-top">

`Number`

</td>

<td class="tableblock halign-left valign-top">

HTTP 상태코드

</td>

</tr>

<tr>

<td class="tableblock halign-left valign-top">

`message`

</td>

<td class="tableblock halign-left valign-top">

`String`

</td>

<td class="tableblock halign-left valign-top">

응답 설명

</td>

</tr>

<tr>

<td class="tableblock halign-left valign-top">

`data`

</td>

<td class="tableblock halign-left valign-top">

`Object`

</td>

<td class="tableblock halign-left valign-top">

응답 데이터

</td>

</tr>

<tr>

<td class="tableblock halign-left valign-top">

`data.id`

</td>

<td class="tableblock halign-left valign-top">

`Number`

</td>

<td class="tableblock halign-left valign-top">

게시글 번호

</td>

</tr>

<tr>

<td class="tableblock halign-left valign-top">

`data.title`

</td>

<td class="tableblock halign-left valign-top">

`String`

</td>

<td class="tableblock halign-left valign-top">

게시글 제목

</td>

</tr>

<tr>

<td class="tableblock halign-left valign-top">

`data.content`

</td>

<td class="tableblock halign-left valign-top">

`String`

</td>

<td class="tableblock halign-left valign-top">

게시글 내용

</td>

</tr>

<tr>

<td class="tableblock halign-left valign-top">

`data.userResponse`

</td>

<td class="tableblock halign-left valign-top">

`Object`

</td>

<td class="tableblock halign-left valign-top">

게시글 작성자 정보

</td>

</tr>

<tr>

<td class="tableblock halign-left valign-top">

`data.userResponse.userId`

</td>

<td class="tableblock halign-left valign-top">

`Number`

</td>

<td class="tableblock halign-left valign-top">

게시글 작성자 번호

</td>

</tr>

<tr>

<td class="tableblock halign-left valign-top">

`data.userRe [...]

2021-10-17 17:15 UTC, HwiNyeonKim reviewed
안녕하세요 태형님 😄
리뷰가 늦었습니다. 죄송합니다.
태형님 코드 보면서 정말 배울 점이 많은 것 같습니다. 정말 꼼꼼하게 작성하시는구나 하고 느껴지는 부분이 많네요.
보면서 몇가지 궁금증들 코멘트로 남겨보았습니다. 
고생하셨습니다.

2021-10-17 17:15 UTC, HwiNyeonKim commented on src/test/java/com/kdt/Board/controller/PostControllerTest.java
> +    @MockBean private PostService postService;
@MockBean 어노테이션을 처음 보는데, 정확한 역할과 도입의도를 알고 싶습니다!

2021-10-18 05:11 UTC, taehyungz commented on src/main/java/com/kdt/Board/controller/PostController.java
> +        final Cookie[] cookies = request.getCookies();
넵 그리고 동작하는지 테스트할 때에는 Postman에서 쿠키를 설정하고 요청을 보내서 테스트했습니다. 클라이언트부분이 없어서 이 부분은 쿠키에 userId가 들어있다고 가정하고 하였습니다.

2021-10-18 06:17 UTC, taehyungz commented on src/main/java/com/kdt/Board/controller/PostController.java
> +    @PutMapping("/{id}")
네 휘년님 댓글에 공감합니다. Post객체의 일부를 변경하는 것이기 때문에  Patch가 적당할 것 같습니다. 추후 수정하겠습니다!

2021-10-18 06:53 UTC, 0923kdh requested changes
고생하셨습니다!!🌱

2021-10-18 06:53 UTC, 0923kdh commented on src/main/java/com/kdt/Board/controller/PostController.java
> +        return ApiResponse.ok("게시글 다건 조회 성공", posts);
"게시글 다건 조회 성공" 을 내려주면 프론트쪽에서는 어떤 이점(?) 이 있는지 궁금합니당!

2021-10-18 06:53 UTC, 0923kdh commented on src/main/java/com/kdt/Board/controller/PostController.java
> +        final Cookie[] cookies = request.getCookies();
저도 이 부분에 대해서 고민스러웠는데 아주 좋은 아이디어네요!!!

2021-10-18 06:53 UTC, 0923kdh commented on src/main/java/com/kdt/Board/dto/PostRequest.java
> +@Setter
dto에 setter를 사용한 이유가 있으실까요 ?

2021-10-18 06:53 UTC, 0923kdh commented on src/main/java/com/kdt/Board/entity/Post.java
> +    @Column(columnDefinition = "TEXT", nullable = false)
columnDefinition을 대문자로 하신 이유가 궁금합니다~!

2021-10-18 06:53 UTC, 0923kdh commented on src/main/java/com/kdt/Board/response/ApiResponse.java
> +    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd HH:mm:ss", timezone = "Asia/Seoul")
timezone = "Asia/Seoul" 로 설정하신 이유가 있을까요?

2021-10-18 06:53 UTC, 0923kdh commented on src/main/java/com/kdt/Board/response/ApiResponse.java
> +    public static <T> ApiResponse<T> fail(int statusCode, String message, T data) { return new ApiResponse<>(statusCode, message, data); }
3xx 는 ok로 처리하고 200을 내려주시는건가요 ?

2021-10-18 06:53 UTC, 0923kdh commented on src/test/java/com/kdt/Board/EnableMockMvcEncodingUTF8.java
> +public @interface EnableMockMvcEncodingUTF8 {
이 클래스는 어떤 역할을 하나요? 궁금해지네요!!

2021-10-18 06:56 UTC, taehyungz commented on src/main/java/com/kdt/Board/controller/PostController.java
> +        return ApiResponse.ok("게시글 다건 조회 성공", posts);
프론트쪽에서 사전에 명세한 API명세서 등을 보고 작업하겠지만, 좀 더 명확하게 알 수 있을 거 같습니다. 다만 서버에서 Response에 담기는 내용이 추가되니 응답 과정에서 부하가 좀 더 생길 수 있을 거 같습니다.

2021-10-18 07:15 UTC, taehyungz commented on src/main/java/com/kdt/Board/entity/Post.java
> +    @Column(columnDefinition = "TEXT", nullable = false)
columnDefinition을 대문자로 한 이유라는 질문을 잘 이해하지 못 했어요.
columnDefinition을 " TEXT"로 설정한 이유라면, 기본적으로 String형은 Database table로 매핑시 Varchar(255)로 매핑되는 것으로 알고 있는데 최대 255자까지 저장이 가능해요.  그래서 DB의 속성값 타입을 Text로 하여서 255자를 초과하는 텍스트도 저장할 수 있게 했습니다.

2021-10-18 07:18 UTC, taehyungz commented on src/main/java/com/kdt/Board/response/ApiResponse.java
> +    public static <T> ApiResponse<T> fail(int statusCode, String message, T data) { return new ApiResponse<>(statusCode, message, data); }
3xx상태에 대해서는 아직 만나지 않아 생각해보지 않았습니다. 추후 필요하면 만들거 같지만, 상태코드가 많아지면 추후 관리가 어려워 진다고 해요. 그 효용성을 생각해보고 어떻게 할 지 정할 거 같습니다.

2021-10-18 07:20 UTC, taehyungz commented on src/test/java/com/kdt/Board/EnableMockMvcEncodingUTF8.java
> +public @interface EnableMockMvcEncodingUTF8 {
이 클래스는 제가 만든 커스텀 어노테이션입니다. 테스트코드 작성시 출력할 때 한글이 정상적으로 출력되지 않았습니다. 기본적으로 UTF8로 설정되어 있는 것으로 아는데, 무시되는 거 같더라구요. 그래서 UTF-8로 인코딩 하도록 해주는 어노테이션입니다.

2021-10-18 18:02 UTC, Heejeong01110 reviewed
안녕하세요 태형님!! 코드 보면서 배워가는 점이 많았습니다!! 이미 리뷰가 적혀있는 부분이 많아서 간단하게 남겼습니다!

2021-10-18 18:07 UTC, taehyungz commented on src/main/java/com/kdt/Board/dto/PostRequest.java
> +@NoArgsConstructor
RequestBody로 사용하는 객체기 때문에 NoArgsConstructor가 필요합니다!

2021-10-19 03:07 UTC, 0923kdh commented on src/main/java/com/kdt/Board/entity/Post.java
> +    @Column(columnDefinition = "TEXT", nullable = false)
아! 그렇군요! 제가 잘 모른 상태로 질문을 했네요! 답변 감사합니다~

2021-10-19 03:08 UTC, 0923kdh approved these changes

2021-10-24 03:01 UTC, Jo-GyuHyeon approved these changes
커밋들을 보았는데 작업 api 작업은 한번에 커밋하신것으로 보았습니다. 지긍은 작업단위가 크지 않아 묶을수 있지만, 만약 어떤 기능이 문제가 생겨 revert 를 하게 된다면 커밋단위가 날라가니 작업단위는 나누는 것이 좋을 것 같습니다.
고생하셨습니다 :)

2022-03-16 09:22 UTC, closed without merging