[1기 -C] 강희정 JPA 게시판 구현하기
prgrms-be-devcourse/SpringBoot-Board pull request #36
Opened 2021-10-15 19:45 UTC by Heejeong01110

## 📌 과제 설명 

### **SpringDataJPA 를 설정한다.**

- datasource : h2

### **엔티티를 구성한다**

- 회원(User)
    - id (PK) (auto increment)
    - name
    - age
    - hobby
    - **created_at**
    - **created_by**
- 게시글(Post)
    - id (PK) (auto increment)
    - title
    - content
    - **created_at**
    - **created_by**
- 회원과 게시글에 대한 연관관계를 설정한다.
    - 회원과 게시글은 1:N 관계이다.
- 게시글 Repository를 구현한다. (PostRepository)

### **API를 구현한다.**

- 게시글 조회
    - 페이징 조회 (GET "/posts")
    - 단건 조회 (GET "/posts/{id}")
- 게시글 작성 (POST "/posts")
- 게시글 수정 (POST "/posts/{id}")

### **REST-DOCS를 이용해서 문서화한다.**

## ✅ PR 포인트 & 궁금한 점 
예외처리부분은 공부한 다음에 추가하겠습니다!

2021-10-16 14:02 UTC, 0923kdh commented on src/main/java/spring/jpa/board/domain/BaseEntity.java
> +  private Long createdBy;
private String createdBy가 되어야 할 것 같습니다!

2021-10-16 14:03 UTC, 0923kdh commented on src/main/java/spring/jpa/board/domain/User.java
> +  private Long id;
Post Entity에서는 GenerationType.IDENTITY로 해주셨던데, User 랑 다르게 설정하신 이유가 무엇인지 궁금합니다~!

2021-10-16 14:12 UTC, 0923kdh commented on src/main/java/spring/jpa/board/domain/Post.java
> +@AllArgsConstructor
@AllArgsConstructor 를 사용하는 곳 이 있을까요? 코드를 찾아보긴 했는데 못본것 같아서요 ..ㅎㅎ...

2021-10-16 14:12 UTC, 0923kdh commented on src/main/java/spring/jpa/board/domain/Post.java
> +
개행을 지워주셔도 좋을 것 같습니다...! ㅎㅎㅎㅎ

2021-10-16 14:20 UTC, 0923kdh commented on src/test/java/spring/jpa/board/repository/PostRepositoryTest.java
> +    user.setHobby("낮잠");
User user = new User("강희정", 24, 낮잠) 이런식으로 해도 좋지않을까요?

2021-10-16 14:21 UTC, 0923kdh commented on src/test/java/spring/jpa/board/repository/PostRepositoryTest.java
> +    post.setUser(user);
Post도 set보단 생성자를 이용하는 방식이 더 좋을 것 같습니다~!

2021-10-16 14:23 UTC, 0923kdh commented on src/test/java/spring/jpa/board/repository/UserRepositoryTest.java
> +class UserRepositoryTest {
사용자 조회, 사용자 수정, 사용자 삭제 테스트 코드까지는 기본적으로 들어가면 좋을 것 같습니다!

2021-10-16 14:23 UTC, 0923kdh commented on src/test/java/spring/jpa/board/repository/PostRepositoryTest.java
> +class PostRepositoryTest {
게시글 수정, 게시글 삭제 테스트까지 기본적으로 들어가면 좋을 것 같습니다~

2021-10-16 14:25 UTC, 0923kdh commented on src/main/java/spring/jpa/board/dto/user/UserDto.java
> +@Setter
dto 에 setter가 필요한 경우가 있나용 ...?

2021-10-16 14:30 UTC, 0923kdh commented on src/main/java/spring/jpa/board/controller/PostRestController.java
> +
저는 전역으로 관리하는 방식을 택했는데요! 이렇게 에러를 관리하면 더 편리한 점이 있나요? 이 부분에 대해서는 월요일에 스터디하기로 했지만..? 궁금해서 여쭈어봅니다!

2021-10-16 14:33 UTC, 0923kdh commented on src/main/java/spring/jpa/board/service/PostService.java
> +    }
postMapping으로  save를 하고 있기때문에 
`Post savePost = postRepository.save(
        new Post(
            postCreateRequest.title(),
            postCreateRequest.content(),
            user));`

2021-10-17 14:46 UTC, 0923kdh commented on src/main/java/spring/jpa/board/service/UserService.java
> +  public void deleteAll() {
delete 할 때 return 값을 void로 하신 이유가 궁금합니다! 저도 이 부분에 대해서 고민하다가 아이디값을 내려주긴 했습니다.

2021-10-17 15:20 UTC, HwiNyeonKim reviewed
희정님 코드 잘 봤습니다!
리뷰가 늦어서 죄송합니다. 😭
몇가지 의견 남기고 갑니다. 고생하셨습니다.

2021-10-17 15:20 UTC, HwiNyeonKim commented on src/main/java/spring/jpa/board/service/PostService.java
> +          savePost.setCreatedBy(entity.getCreatedBy());
저는 나중에 수정하려고 일단 전부 setter를 사용해서 놓치고 지나갔던 건데, 기왕 이렇게 생성자를 사용하시는 김에 BaseEntity의 field도 protected로 풀고 createdAt과 createdBy도 생성자로 넣으면 어떨까... 하는 생각을 잠시 해봤습니다. 희정님 의견은 어떠신가요?

2021-10-17 15:20 UTC, HwiNyeonKim commented on src/main/java/spring/jpa/board/service/PostService.java
> +  public PostFindRequest findById(Long id) throws NotFoundException {
이름만 봤을 때에는 PostFIndResponse가 반환되어야 하지 않을까 하는 생각이 드는데, 사용하는 필드가 모두 동일해서 그냥 Request를 다시 사용하신건가요?

2021-10-17 15:20 UTC, HwiNyeonKim commented on src/test/java/spring/jpa/board/service/PostServiceTest.java
> +    assertThat(all, hasSize(1));
저는 size 외에도 생성한 post와 find로 찾아온 post가 같은 post인지도 확인 해 봐야 한다고 생각하는데, 희정님 의견은 어떠신가요?

2021-10-17 15:25 UTC, 0923kdh commented on src/test/java/spring/jpa/board/controller/PostRestControllerTest.java
> +    mockMvc.perform(get("/posts")
상민님이 주신 코드 리뷰인데 희정님한테도 남기고 갑니다! 
`Page객체를 그대로 내보내니 엄청 많은 메타데이터가 같이 전송되더라구요. dto를 만들어서 필요한 정보만 내보내는것이 좋을거 같아요 👍`

2021-10-19 03:22 UTC, 0923kdh commented on src/main/java/spring/jpa/board/controller/PostRestController.java
> +  @PostMapping("/posts/{id}")
@PatchMapping는 1개의 필드를 수정할 경우에 사용하는게 좋다고 생각했습니다!

2021-10-20 07:15 UTC, Heejeong01110 commented on src/main/java/spring/jpa/board/post/domain/Post.java
> +    @Column(name="title", nullable = false, length = 50)
딱히 이유를 정하고 쓰진 않았습니다!

2021-10-20 07:28 UTC, Heejeong01110 commented on src/main/java/spring/jpa/board/domain/User.java
> +  private Long id;
Identity는 테이블 별로 auto_increase, sequence는 전체 기본키 번호가 auto_increase이기 때문에 h2로 실행했을 경우 다른 전략을 사용하게 되서 수정해야할 것 같습니다!

2021-10-20 09:27 UTC, Heejeong01110 commented on src/test/java/spring/jpa/board/repository/PostRepositoryTest.java
> +    assertThat(posts, hasSize(1));
저도 내용까지 확인하는게 더 좋은 것 같네요! 수정해야될 것 같습니다!

2021-10-24 02:22 UTC, Jo-GyuHyeon requested changes

2021-10-24 02:22 UTC, Jo-GyuHyeon commented on src/main/java/spring/jpa/board/controller/PostRestController.java
> +      throws NotFoundException {
idea 에서 자동 정렬 된것인가요?

2021-10-24 02:22 UTC, Jo-GyuHyeon commented on src/main/java/spring/jpa/board/controller/PostRestController.java
> +
앗... 자동정렬이 안된것 같네요

2021-10-24 02:22 UTC, Jo-GyuHyeon commented on src/main/java/spring/jpa/board/domain/BaseEntity.java
> +  private Long createdBy;
https://github.com/prgrms-be-devcourse/SpringBoot-Board/pull/7#discussion_r735049378

이미 코멘트를 남겨서 링크 공유 하겠습니다. :)

2021-10-24 02:22 UTC, Jo-GyuHyeon commented on src/main/java/spring/jpa/board/service/PostService.java
> +    if (savePost.getCreatedBy() == null) {
개행들이 필요해 보입니다.

2021-10-24 02:22 UTC, Jo-GyuHyeon commented on src/main/java/spring/jpa/board/service/PostService.java
> +    if (savePost.getCreatedBy() == null) {
이러한 로직은 validation 혹은 위에 코멘트 https://github.com/prgrms-be-devcourse/SpringBoot-Board/pull/7#discussion_r735049378 처럼 처리하는 것이 좋을 것 같습니다.

2021-10-24 02:22 UTC, Jo-GyuHyeon commented on src/main/java/spring/jpa/board/service/PostService.java
> +    return post.getId();
처음 부터 return 을 사용해서 체이닝으로만 이어지도록 변경해보세요

2021-10-24 02:22 UTC, Jo-GyuHyeon commented on src/main/java/spring/jpa/board/service/PostService.java
> +        .map((item) -> new PostFindRequest(item.getId(), item.getTitle(), item.getContent(),
개행이 필요해 보입니다. 
인자도 개행을 넣어보세요 더 깔끔하게 느껴질것입니다.

2021-10-24 02:22 UTC, Jo-GyuHyeon commented on src/test/java/spring/jpa/board/controller/PostRestControllerTest.java
> +@SpringBootTest
https://github.com/prgrms-be-devcourse/SpringBoot-Board/pull/7#discussion_r735049997

2021-10-24 02:22 UTC, Jo-GyuHyeon commented on src/test/java/spring/jpa/board/repository/PostRepositoryTest.java
> +    assertThat(posts, hasSize(2));
2라는 것은 눈으로 봤을때 확인이 가능한것 같습니다.
이방법이 나쁜건 아니지만 제안드리고 싶은 것도 있네요.

post list를 만드는 메서드를 따로 빼보는 것은 어떨까요? 
그리고 `assertThat(posts, hasSize(generatePosts.size()));` 이런건 어떨까요?

2022-03-16 09:22 UTC, closed without merging