[1기-C] 박수빈 - JPA 게시판 만들기
prgrms-be-devcourse/SpringBoot-Board pull request #37
Opened 2021-10-15 21:03 UTC by suebeen

## 📌 과제 설명 

Spring Boot JPA - Rest API를 강의를 듣고, 게시판 구현 미션을 수행합니다.

## 👩‍💻 요구 사항과 구현 내용 
### 요구사항
**1. SpringDataJPA 를 설정한다.**

- [x] datasource : `h2` or ~~mysql~~

**2. 엔티티를 구성한다**

- [x] 회원(User)
- [x] 게시글(Post)
- [ ] 회원과 게시글에 대한 연관관계를 설정한다.
  - [x] 회원과 게시글은 1:N 관계이다.
- [x] 게시글 Repository를 구현한다. (PostRepository)

**3. API를 구현한다.**

- [x] 게시글 조회
  - [x] 페이징 조회 (GET "/posts")
  - [x] 단건 조회 (GET "/posts/{id}")
- [x] 게시글 작성 (POST "/posts")
- [x] 게시글 수정 (POST "/posts/{id}")

4. REST-DOCS를 이용해서 문서화한다.
  

## ✅ PR 포인트 & 궁금한 점 
- [x] test코드를 작성하는데 시간을 가장 많이 쓴 것 같은데 아직도 고쳐지지 않는 오류가 있습니다... 이유를 모르겠네요 ㅠㅠ 그리고 테스트 코드를 잘 짜는 팁 같은게 있을까요?!

2021-10-16 18:54 UTC, sds1vrk reviewed
전체적으로 깔끔하게 잘 짜신것같아요! 참고해서 저도 보완하겠습니다! 👍

2021-10-16 18:54 UTC, sds1vrk commented on src/main/java/com/kdt/springbootboard/dto/UserDto.java
> +
validation 배우고 갑니다!

2021-10-17 07:41 UTC, Kwonkyu approved these changes
고생하셨습니다!! 근데 무슨 오류가 있으셨나요?

2021-10-17 07:41 UTC, Kwonkyu commented on src/main/java/com/kdt/springbootboard/controller/ApiResponse.java
> +        return new ApiResponse<>(200, data);
[HTTP 상태 코드](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/http/HttpStatus.html)를 정의해둔 enum도 있으니 나중에 상태 코드가 헷갈리시거나 할 때 사용하시면 좋을 것 같습니다!

2021-10-17 07:41 UTC, Kwonkyu commented on src/main/java/com/kdt/springbootboard/controller/PostController.java
> +    public ApiResponse<PostDto> getPost(@PathVariable Long id) throws PostNotFoundException {
`id` 필드는 필수적인 부분인 만큼 null을 허용하지 않도록 래퍼 클래스 대신 원시 타입을 사용하시는 것도 괜찮을 것 같습니다!

2021-10-17 07:41 UTC, Kwonkyu commented on src/main/java/com/kdt/springbootboard/controller/PostController.java
> +    @PostMapping("/posts/{id}")
업데이트는 Post 대신 Put 메서드를 사용하는 것도 좋을 것 같습니다. [링크](https://restfulapi.net/rest-put-vs-post/)

2021-10-17 07:41 UTC, Kwonkyu commented on src/main/java/com/kdt/springbootboard/converter/PostConverter.java
> +public class PostConverter {
컴포넌트로 주입받는 것보다 정적 메서드를 제공하는 유틸리티 클래스로 활용하는 것도 생각해 볼 수 있을 것 같습니다.

2021-10-17 07:41 UTC, Kwonkyu commented on src/main/java/com/kdt/springbootboard/dto/PostDto.java
> +    @NotNull(message = "Title is mandatory")
문자열이 비어있지 않도록 `@NotBlank` 어노테이션을 사용해보는 것도 좋을 것 같습니다. [null이 아닌 조건을 포함](https://javaee.github.io/javaee-spec/javadocs/javax/validation/constraints/NotBlank.html)하고 있고 비어있거나 공백으로만 구성된 문자열도 검증할 수 있습니다

2021-10-17 07:41 UTC, Kwonkyu commented on src/main/java/com/kdt/springbootboard/dto/UserDto.java
> +    @Range(min = 1, max = 100, message = "Age is between 0 and 100")
오 `@Range` 는 처음 알았네요!! 👍👍

2021-10-17 07:41 UTC, Kwonkyu commented on src/test/java/com/kdt/springbootboard/controller/PostControllerTest.java
> +                        .contentType(MediaType.APPLICATION_JSON))
get 요청엔 불필요한 컨텐츠 타입인 것 같습니다!

2021-10-17 07:41 UTC, Kwonkyu commented on src/test/java/com/kdt/springbootboard/controller/PostControllerTest.java
> +                        responseFields(
[`parameterWithName`](https://docs.spring.io/spring-restdocs/docs/current/api/org/springframework/restdocs/request/RequestDocumentation.html#parameterWithName-java.lang.String-) 을 활용해서 `id` 패스 파라미터에 대한 문서화도 적용하면 좋을 것 같습니다.

2021-10-17 07:41 UTC, Kwonkyu commented on src/test/java/com/kdt/springbootboard/service/PostServiceTest.java
> +                .content("정말 좋아요")
ㅋㅋㅋㅋㅋㅋㅋㅋㅋ

2021-10-17 07:41 UTC, Kwonkyu commented on src/test/java/com/kdt/springbootboard/service/PostServiceTest.java
> +    }
여러 게시물을 등록하고 작은 사이즈의 페이지를 이용해서 테스트해보는 것도 괜찮을 것 같습니다

2021-10-17 10:03 UTC, VictoryPark commented on src/main/java/com/kdt/springbootboard/controller/PostController.java
> +    }
Controller와 ExeptionHandler 의 관점 분리를 할 수 있는 ControllerAdvice 사용을 추천드립니당😋

2021-10-17 10:08 UTC, VictoryPark commented on src/main/java/com/kdt/springbootboard/converter/PostConverter.java
> +public class PostConverter {
Post, User 엔티티에서 해야할 기능과 
DTO 에서 할 수 있는 기능들을 분류해보면 아마도 PostConverter는 존재 이유가 없어질 수도 있습니다.
한번 고민해보셔요ㅎㅎ

2021-10-17 10:09 UTC, VictoryPark commented on src/main/java/com/kdt/springbootboard/domain/User.java
> +    }
각 엔티티는 생성자에서 validate 로직을 넣는 것을 추천합니당

2021-10-17 10:17 UTC, VictoryPark commented on src/main/java/com/kdt/springbootboard/controller/ApiResponse.java
> +public class ApiResponse<T> {
👏👍🏼

2021-10-17 10:39 UTC, VictoryPark requested changes
수빈님, 해결되지 않는 test 케이스가 있다고 하셔서 돌려보았는데요
PostServiceTest 에서 조회 부분에서 test가 실패로 뜨는 부분이 있었습니다.
hibernate 에서 보여주는 쿼리를 보니, post를 insert 할때 User 를 insert 하는 쿼리는 실행이 되지 않아서 조회시, user가 null로 나오는 현상이었습니다.
이를 어떻게 해결해야 할지, 어노테이션 속성 위주로 한번 찾아보세요.

그리고 위의 문제를 해결하면,
아마도 게시물 저장 test 케이스가 실패할 겁니다.
이 부분은 Builder 어노테이션의 사용과 GeneratedValue의 충돌때문입니다.

이 부분도 다시 고민하셔서 해결해보세요!
그리고 Builder는 어노테이션이 아닌, 직접 구현하는 것을 추천드립니다!!

2021-10-18 09:39 UTC, wooko5 approved these changes
기발한 어노테이션을 코드에 적용하셔서 코드가 간결하게 느껴졌습니다. 새벽까지 과제하시느라 고생하셨습니다! 😀

2021-10-18 09:39 UTC, wooko5 commented on src/main/java/com/kdt/springbootboard/domain/BaseEntity.java
> +@EntityListeners(AuditingEntityListener.class)
새로운 어노테이션을 알게 되었습니다. 감사합니다😀

2021-10-18 09:39 UTC, wooko5 commented on src/main/java/com/kdt/springbootboard/domain/User.java
> +    }
User 클래스에 @Builder를 작성하는 것과 어떤 차이가 있는지 궁금합니다!😀

2021-10-18 09:39 UTC, wooko5 commented on src/main/java/com/kdt/springbootboard/dto/UserDto.java
> +    @Pattern(regexp = "^[a-zA-Z]*$", message = "Hobby should be written by English")
영어 소/대문자만 받도록 정규표현식으로 작성할 수 있군요. 배워갑니다!😀

2022-03-16 09:22 UTC, closed without merging