[1기-C 김휘년] JPA 게시판 만들기
prgrms-be-devcourse/SpringBoot-Board pull request #42
Opened 2021-10-17 09:43 UTC by HwiNyeonKim

## 📌 과제 설명 

* Spring Data JPA를 사용하여 게시판을 구현한다.

## 👩‍💻 요구 사항과 구현 내용 

### 엔티티 구성

- [x] 회원(User)
  * id (PK, auto increment)
  * name
  * age
  * hobby
  * created_at
  * created_by
- [x] 게시글(Post)
  * id (PK, auto increment)
  * title
  * content
  * created_at
  * created_by
- [x] 회원과 게시글에 대한 연관관계를 설정한다. 
  * 회원과 게시글은 1:N 관계이다.
  * cascade, mapped by, orphanRemoval 설정
- [x] 게시글 Repository를 구현한다
![diagram](https://cln.sh/jv6cn0)

### API 구현
- [x] 게시글 조회
  * 페이징 조회 : GET "/posts"
  * 단건 조회 : GET "/posts/{id}"
- [x] 게시글 작성
  * POST "/posts"
- [x] 게시글 수정
  * POST "/posts/{id}"

### 문서화
- [x] REST Docs를 사용하여 문서화 하기

## ✅ PR 포인트 & 궁금한 점 

* 늦었습니다. 죄송합니다. 일단 기본적인 요구사항만 맞춰보았습니다.
* PostDto 관련 궁금증
  * 각 요청마다 dto를 통해 전달해야 하는 데이터에 약간의 차이가 있습니다. 현재는 하나의 dto를 사용하고 필요한 field만 사용하는 식으로 만들었습니다. 
  * 어떻게 바꿀 수 있을까 생각을 해 볼 때, 각 케이스마다 꼭 필요한 field만 가지는 dto를 여러 개를 만들어서 사용하는 것과 공통되는 field를 가지는 dto + 추가적으로 필요한 field를 별도로 보내는 것 중에 어떤 것이 더 나을지 고민중입니다. 혹시 의견 있으시면 의견 주시면 감사하겠습니다.
* cascade, orphanRemoval 관련
  * '회원이 제거되어도(탈퇴하여도) 게시글은 남아있게 하려면?' 이라는 생각으로 cascade, orphanRemoval을 별도로 걸어주지 않았습니다. 
* 연관관계 설정 관련 궁금증
  * 과제 요구사항에 있어서 일단 회원 - 게시글 간의 연관관계는 설정 해 주었습니다. 하지만 딱히 쓰이는 곳이 아직 없습니다.  
  * 원래는 회원 -> 작성한 게시글 리스트, 게시글 -> 작정사 회원 정보를 갖게 하고 싶었습니다만, createdBy 필드의 역할과 명확히 구분이 안 되어서 일단 현재 제출된 상태로만 두었습니다.
  * 궁금증
    * createdBy 필드가 없어져야 할 것 같은데 어떻게 생각하시나요? 제가 이처럼 생각한 이유는 아래와 같습니다.
      * User 클래스에서 createdBy 필드의 역할이 불분명해 보인다. 어떤 의미를 가지는지를 모르겠다. 
      * Post 클래스에서 createdBy 필드의 역할이 중복된다. 오히려 연관관계 설정에 이용된 user field가 이 역할에 적합 해 보인다.
    * 또, 각자 생각하신 createdBy의 역할이 궁금합니다.

2021-10-17 14:36 UTC, 0923kdh requested changes
고생하셨습니다!🎊⭐️📍🥺⛑

2021-10-17 14:36 UTC, 0923kdh commented on src/test/java/com/example/board/repository/PostRepositoryTest.java
> +		assertThat(foundPost).isEqualTo(post);
아! 이걸하려고 Equals, HashCode를 쓰셨군요! 저는 값을 하나씩 가져와서 비교하는 방식으로 했는데 각 방식에 따라서 어떤 장/단점이 있을지 궁금해지네요!

2021-10-17 14:36 UTC, 0923kdh commented on src/main/java/com/example/board/dto/PostDto.java
> +    }
어떤 의미를 가지고 있는 메서드인지 궁금합니다...!😮

2021-10-17 14:36 UTC, 0923kdh commented on src/test/java/com/example/board/service/PostServiceTest.java
> +        postService.save(postDto3);
중간 중간 개행을 넣어주면 가독성 측면에서 도움이 되지 않을까 생각합니다! 😆

2021-10-17 14:36 UTC, 0923kdh commented on src/main/java/com/example/board/ApiResponse.java
> +    }
응답을 ok, fail 로 내려주시는데 3xx 응답코드는 ok로 분류하는건가용?

2021-10-17 14:36 UTC, 0923kdh commented on src/main/java/com/example/board/controller/PostController.java
> +    }
controller 에서 ExceptionHandler를 처리한 이유가 궁금합니다!

2021-10-17 14:36 UTC, 0923kdh commented on src/main/java/com/example/board/controller/PostController.java
> +    public ApiResponse<Long> uploadPost(@RequestBody PostDto postDto) {
저 같은 경우에는 게시글 작성 메서드를 createPost로 하였는데요! createPost, savePost 와 같은 메서드명은 어떨까요 ?

2021-10-17 14:36 UTC, 0923kdh commented on src/main/java/com/example/board/domain/User.java
> +	private List<Post> posts = new ArrayList<>();
양방향으로 설정하신 이유가 궁금합니다~

2021-10-17 14:36 UTC, 0923kdh commented on src/main/java/com/example/board/controller/PostController.java
> +        postDto.setId(id);
setId 를 따로 해주신 이유가 있을까요 ? id 필드는 set으로 변경될 수 있는 여지를 주지않는게 안전하다고 생각합니다.

2021-10-17 17:18 UTC, sangmin7648 requested changes
> - PostDto 관련 궁금증
> 각 요청마다 dto를 통해 전달해야 하는 데이터에 약간의 차이가 있습니다. 현재는 하나의 dto를 사용하고 필요한 field만 사용하는 식으로 만들었습니다.
> 어떻게 바꿀 수 있을까 생각을 해 볼 때, 각 케이스마다 꼭 필요한 field만 가지는 dto를 여러 개를 만들어서 사용하는 것과 공통되는 field를 가지는 dto + 추가적으로 필요한 field를 별도로 보내는 것 중에 어떤 것이 더 나을지 고민중입니다. 혹시 의견 있으시면 의견 주시면 감사하겠습니다.

저도 동일한 고민했었습니다 ㅋㅋㅋ 🤣 저는 결국 dto들을 분리했는데요. "dto에 필드 몇개 들어가지도 않는데 굳이 분리해서 프로젝트 구조를 지저분하게 해야하나?"하고 생각하실 수 있을거같습니다. 태형님이 이를 해결할 방법중 하나를 공유해주셔서 여기에도 남깁니다 https://github.com/prgrms-be-devcourse/SpringBoot-Board/pull/19#discussion_r729918668

> - cascade, orphanRemoval 관련
> '회원이 제거되어도(탈퇴하여도) 게시글은 남아있게 하려면?' 이라는 생각으로 cascade, orphanRemoval을 별도로 걸어주지 않았습니다.

cascade와 orphanRemoval은 jpa와 관련이 있고 실제 db 데이터와는 상관이 없는 것으로 알고 있습니다. https://stackoverflow.com/questions/4329577/how-does-jpa-orphanremoval-true-differ-from-the-on-delete-cascade-dml-clause. 게시글이 남아있게하려면 fk 제약을 제거해줘야하지않나 싶어요(제가 잘못알고 있을 수도 있으니 찾아보신다면 제게도 알려주세요!!)

> - 연관관계 설정 관련 궁금증
> 과제 요구사항에 있어서 일단 회원 - 게시글 간의 연관관계는 설정 해 주었습니다. 하지만 딱히 쓰이는 곳이 아직 없습니다.
> 원래는 회원 -> 작성한 게시글 리스트, 게시글 -> 작정사 회원 정보를 갖게 하고 싶었습니다만, createdBy 필드의 역할과 명확히 구분이 안 되어서 일단 현재 제출된 상태로만 두었습니다.
> 궁금증
> createdBy 필드가 없어져야 할 것 같은데 어떻게 생각하시나요? 제가 이처럼 생각한 이유는 아래와 같습니다.
> User 클래스에서 createdBy 필드의 역할이 불분명해 보인다. 어떤 의미를 가지는지를 모르겠다.
> Post 클래스에서 createdBy 필드의 역할이 중복된다. 오히려 연관관계 설정에 이용된 user field가 이 역할에 적합 해 보인다.
> 또, 각자 생각하신 createdBy의 역할이 궁금합니다.

저도 현재 요구사항에서는 createdBy가 필요없다는 점에 동의합니다. user_id fk가 이를 대체할 수 있는가에 대해서는 저는 user_id와 createdBy가 둘다 있는게 의미가 있다고 생각합니다(이 경우 보다는 비정규화 관점에서요). user 연관관계를 통해서 유저명을 가져올 수 있지만 그렇게 되면 매번 join 연산을 해줘야겠죠. 이 경우에는 그 연산의 오버헤드가 크진 않아서 상관 없을 수도 있지만 게시글 작성자가 누구인지 반환하는 건 중요하다고 생각하는데 createdby 필드 없이는 post엔티티의 user 연관관계에 lazy fetch를 적용할 수 없을거 같아요

2021-10-17 17:18 UTC, sangmin7648 commented on src/main/java/com/example/board/controller/PostController.java
> +    public ApiResponse<Long> editPost(@PathVariable Long id, @RequestBody PostDto postDto) throws NotFoundException {
이런 찾을 수 없는 경우에서 rest api는 회복할 수 없기 때문에 RuntimeException을 상속한 커스텀 예외를 사용하는게 좋다고 생각하는데 휘년님은 Checked/Unchecked 예외를 어떤 기준으로 사용하시나요???

2021-10-17 17:18 UTC, sangmin7648 commented on src/main/java/com/example/board/converter/PostConverter.java
> +    public static Post convertFromDtoToPost(PostDto postDto) {
인자로도 무엇으로부터 변환하는지 유추가능해서 다음처럼 메소드명을 단축시켜볼 수 있을거 같아요 🤔🤔

```suggestion
    public static Post convertToPost(PostDto postDto) {
```

2021-10-17 17:18 UTC, sangmin7648 commented on src/main/java/com/example/board/converter/PostConverter.java
> +                .build();
엔티티는 setter를 사용하고 dto는 빌더를 사용하시는 이유가 있으신가요??

2021-10-17 17:18 UTC, sangmin7648 commented on src/main/java/com/example/board/domain/Post.java
> +	}
equals랑 hashCode가 필요할까요??  😗😗 https://thorben-janssen.com/ultimate-guide-to-implementing-equals-and-hashcode-with-hibernate/

2021-10-17 17:18 UTC, sangmin7648 commented on src/main/java/com/example/board/dto/PostDto.java
> +    }
public한 noargs 생성자가 이미 있는데 스태틱 팩토리를 만드신 이유가 궁금합니다!

2021-10-17 17:18 UTC, sangmin7648 commented on src/main/java/com/example/board/service/PostService.java
> +    }
저도 모든 서비스에 `@Transactional`을 붙였다가 태형님이랑 은서님께 혼났는데요 😅 어떤 상황에서 써야하는지 찾아보시면 좋을거 같습니다. 저도 아직 안찾아봤지만 일단 select 요청에는 필요없다고 하네요!

2021-10-17 17:18 UTC, sangmin7648 commented on src/main/java/com/example/board/domain/Post.java
> +@Setter
저도 그냥 setter를 사용했다가 태형님이랑 은서님께 혼났습니다 ㅋㅋㅋ 의미전달이 쉬운 이름을 가진 메소드를 작성해보는건 어떤가요?

2021-10-17 17:27 UTC, sangmin7648 commented on src/test/java/com/example/board/repository/PostRepositoryTest.java
> +		assertThat(foundPost).isEqualTo(post);
hamcrest의 매처이기는한데 저는 이런경우 `samePropertyValuesAs()` 매처를 사용했습니다. 분명 비슷한게 있을거 같아요!

2021-10-17 17:28 UTC, sangmin7648 commented on src/main/java/com/example/board/controller/PostController.java
> +        postDto.setId(id);
저도 dto는 불변이어야한다고 생각해서 다희님과 동의합니다

2021-10-19 16:27 UTC, HwiNyeonKim commented on src/test/java/com/example/board/repository/PostRepositoryTest.java
> +		assertThat(foundPost).isEqualTo(post);
오늘 이야기중에 나온 [링크(라흐의 DTO vs VO)](https://www.youtube.com/watch?v=J_Dr6R0Ov8E)를 참고 해 보니 제가 Entity를 VO처럼 사용하려고 했던 것 같습니다. 
다시 생각 해 보니 굳이 Entity에 equals()랑 hashCode()를 오버라이딩 해 줄 필요가 있나? 하는 생각이 들더라구요.
그래서 오버라이딩 해 준 부분을 제거하고, 이부분은 각 필드별로 비교를 하는 것으로 수정했습니다.

2021-10-19 16:46 UTC, HwiNyeonKim commented on src/main/java/com/example/board/ApiResponse.java
> +    }
아직 리다이렉션이 필요한 단계가 아니라고 생각하여 리다이렉션 부분까지 고려하여 작성하지는 않았습니다.
추후 필요할경우에 해당 메서드를 추가해 줄 것 같습니다.

2021-10-19 16:57 UTC, HwiNyeonKim commented on src/main/java/com/example/board/controller/PostController.java
> +    public ApiResponse<Long> uploadPost(@RequestBody PostDto postDto) {
createPost가 가장 직관적인 이름인 것 같습니다. 수정하였습니다.

2021-10-19 17:22 UTC, HwiNyeonKim commented on src/main/java/com/example/board/domain/User.java
> +	private List<Post> posts = new ArrayList<>();
DB에서는 항상 양방향이라, 연관관계 매핑을 위해서는 똑같은 관계(양방향)를 맺어줘야 한다고 강의 내용을 잘못 이해하고 있었습니다.
지금 상황에서는 Post 쪽에서 다대일 단방향 매핑을 해 주는 정도로 충분할 것 같습니다.

2021-10-19 18:16 UTC, HwiNyeonKim commented on src/main/java/com/example/board/converter/PostConverter.java
> +    public static Post convertFromDtoToPost(PostDto postDto) {
확실히 이정도로도 충분히 의미가 파악이 가능한 것 같습니다.
제안해 주신 대로 수정하였습니다!

2021-10-24 02:33 UTC, Jo-GyuHyeon requested changes

2021-10-24 02:33 UTC, Jo-GyuHyeon commented on src/main/java/com/example/board/ApiResponse.java
> +    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd HH:mm:ss", timezone = "Asia/Seoul")
서울이 아닌곳에서 데이터를 저장하면 어떻게 되나요? 프론트에선 어떻게 처리 해야 될까요? 
고민 해보시면 좋을 것 같습니다.

2021-10-24 02:33 UTC, Jo-GyuHyeon commented on src/main/java/com/example/board/controller/PostController.java
> +@RequestMapping("/api/v1/posts")
prefix 로 `/api` 를 붙이신 이유가 있을까요?

2021-10-24 02:33 UTC, Jo-GyuHyeon commented on src/main/java/com/example/board/controller/PostController.java
> +    @PostMapping("/{id}")
Put 이 아닌 Post로 하신 이유는 Get, Post 방식만 사용하기 위함인가요/

2021-10-24 02:33 UTC, Jo-GyuHyeon commented on src/main/java/com/example/board/service/PostService.java
> +    public PostResponse findById(Long id) {
👍

2021-10-24 02:33 UTC, Jo-GyuHyeon commented on src/main/java/com/example/board/service/PostService.java
> +        Post post = postRepository.findById(postId).orElseThrow(() -> new PostNotFoundException(
`findById()` 를 만들고 사용하지 않는 이유가 있을까요? 재사용할 수 있는 방법은 없을까요?

2022-03-16 09:22 UTC, closed without merging