[1기-C 신언주] JPA 게시판 만들기
prgrms-be-devcourse/SpringBoot-Board pull request #48
Opened 2021-10-18 15:18 UTC by GetMapping

## 📌 과제 설명 
요구사항에 주어진 url에 맞춰 조회, 작성, 수정 기능을 만들었습니다.
- 라이브러리 : JPA
- 빌드도구 : Gradle
- 데이터베이스 : MySQL 5.7
## 👩‍💻 요구 사항과 구현 내용 

### **SpringDataJPA 를 설정한다.**

- datasource : h2 or mysql

### **엔티티를 구성한다**

- 회원(User)
    - id (PK) (auto increment)
    - name
    - age
    - hobby
    - **created_at**
    - **created_by**
- 게시글(Post)
    - id (PK) (auto increment)
    - title
    - content
    - **created_at**
    - **created_by**
- 회원과 게시글에 대한 연관관계를 설정한다.
    - 회원과 게시글은 1:N 관계이다.
- 게시글 Repository를 구현한다. (PostRepository)

### **API를 구현한다.**

- 게시글 조회
    - 페이징 조회 (GET "/posts")
    - 단건 조회 (GET "/posts/{id}")
- 게시글 작성 (POST "/posts")
- 게시글 수정 (POST "/posts/{id}")

### **REST-DOCS를 이용해서 문서화한다.**

## ✅ PR 포인트 & 궁금한 점 
수정시 사용자 데이터를 받지 않고 수정하는 것도 가능할까요??

2021-11-09 10:34 UTC, ksy90101 requested changes
수정하고 다시 말씀해주세요~ 고생 많으셨습니다 :+1

2021-11-09 10:34 UTC, ksy90101 commented on build.gradle
> +    testImplementation group: 'org.springframework.restdocs', name: 'spring-restdocs-mockmvc'
```suggestion
    testImplementation 'org.springframework.restdocs:spring-restdocs-mockmvc'
```

2021-11-09 10:34 UTC, ksy90101 commented on build.gradle
> +    compileOnly {
```suggestion
}

configurations {
    compileOnly {
```

2021-11-09 10:34 UTC, ksy90101 commented on docker-compose.yml
> +    image: library/mysql:5.7
8버전으로 업데이트 해보세요.

2021-11-09 10:34 UTC, ksy90101 commented on src/main/java/com/kdt/bulletinboard/ApiResponse.java
> +        return new ApiResponse<>(200, data);
200을 매직넘버이니, 상수로 만들어 주세요.

2021-11-09 10:34 UTC, ksy90101 commented on src/main/java/com/kdt/bulletinboard/controller/PostController.java
> +    private PostService postService;
@Autowired vs 생성자 주입의 차이가 뭘까요? 어떤게 더 좋을까여?

2021-11-09 10:34 UTC, ksy90101 commented on src/main/java/com/kdt/bulletinboard/controller/PostController.java
> +public class PostController {
@RequestMapping으로 공통 url을 추출하면 어떨까요?

2021-11-09 10:34 UTC, ksy90101 commented on src/main/java/com/kdt/bulletinboard/controller/PostController.java
> +    public ApiResponse<Long> write(@RequestBody PostDto postDto) {
validation도 다 적용해보세요.

2021-11-09 10:34 UTC, ksy90101 commented on src/main/java/com/kdt/bulletinboard/controller/PostController.java
> +    }
ExceptionHandler룰 따로 뺴보면 어떨까요?

2021-11-09 10:34 UTC, ksy90101 commented on src/main/java/com/kdt/bulletinboard/converter/PostConverter.java
> +public class PostConverter {
PostConverter인데 User를 Convert하는것도 있는거 같네요.

2021-11-09 10:34 UTC, ksy90101 commented on src/main/java/com/kdt/bulletinboard/dto/PostDto.java
> +@Setter
제거 해주세요.

2021-11-09 10:34 UTC, ksy90101 commented on src/main/java/com/kdt/bulletinboard/dto/UserDto.java
> +@Setter
제거해주세요.

2021-11-09 10:34 UTC, ksy90101 commented on src/main/java/com/kdt/bulletinboard/dto/UserDto.java
> +public class UserDto {
과연 DTO는 어떻게 값들을 받아올까?
직렬화 역직렬화를 알아보세요.

2021-11-09 10:34 UTC, ksy90101 commented on src/main/java/com/kdt/bulletinboard/entity/BaseEntity.java
> +@Setter
여기도 setter 뺴주세요.

2021-11-09 10:34 UTC, ksy90101 commented on src/main/java/com/kdt/bulletinboard/entity/BaseEntity.java
> +    private LocalDateTime cratedAt;
```suggestion
    private LocalDateTime createdAt;
```

2021-11-09 10:34 UTC, ksy90101 commented on src/main/java/com/kdt/bulletinboard/entity/Post.java
> +    }
여기 순서를 좀 맞춰주세요.

하나의 클래스의 어떤 순서로 가져가는지 한번 찾아보세요.

2021-11-09 10:34 UTC, ksy90101 commented on src/main/java/com/kdt/bulletinboard/entity/User.java
> +        this.setCreatedBy(createBy);
여기두 순서 맞춰주세요.

2021-11-09 10:34 UTC, ksy90101 commented on src/main/java/com/kdt/bulletinboard/entity/User.java
> +    private List<Post> posts = new ArrayList<>();
왜 빈 List를 만들까요?

2021-11-09 10:34 UTC, ksy90101 commented on src/main/java/com/kdt/bulletinboard/service/PostService.java
> +        return saved.getId();
```suggestion
        Post post = postConverter.convertToPost(postDto);
        Post saved = postRepository.save(post);
        
        return saved.getId();
```

2021-11-09 10:34 UTC, ksy90101 commented on src/main/java/com/kdt/bulletinboard/service/PostService.java
> +    }
```suggestion
    public Long updatePost(Long id, PostDto postDto) throws NotFoundException {
        postRepository.findById(id)
                .map(foundPost -> {
                    foundPost.updatePost(postDto.getTitle(), postDto.getContent());
                    postRepository.save(foundPost);
                    return id;
                })
                .orElseThrow(() -> new NotFoundException("해당 포스트를 찾을 수 없습니다."));
                
        return id;
    }
```

2021-11-09 10:34 UTC, ksy90101 commented on src/main/java/com/kdt/bulletinboard/service/UserService.java
> +    }
readOnly를 걸어주세요.

2021-11-09 10:34 UTC, ksy90101 commented on src/test/java/com/kdt/bulletinboard/controller/PostControllerTest.java
> +    }
여기에 어떤 값이 response으로 나오는지 적어주세요.

2021-11-09 10:34 UTC, ksy90101 commented on src/test/java/com/kdt/bulletinboard/controller/PostControllerTest.java
> +    }
param도 적어주세요.

2021-11-09 10:34 UTC, ksy90101 commented on src/test/java/com/kdt/bulletinboard/controller/PostControllerTest.java
> +                ));
```suggestion
        PostDto newPostDto = PostDto.builder()
                .id(savedPostId)
                .title("updated Post")
                .content("This is updated Post")
                .userDto(userDto)
                .build();
                
        mockMvc.perform(put("/posts/{id}", newPostDto.getId())
                        .content(objectMapper.writeValueAsString(newPostDto))
                        .contentType(MediaType.APPLICATION_JSON)).andExpect(status().isOk())
                .andDo(print())
                .andDo(document("post-update"
                        , requestFields(
                                fieldWithPath("id").type(JsonFieldType.NUMBER).description("아이디")
                                , fieldWithPath("title").type(JsonFieldType.STRING).description("제목")
                                , fieldWithPath("content").type(JsonFieldType.STRING).description("내용")
                                , fieldWithPath("userDto").type(JsonFieldType.OBJECT).description("사용자")
                                , fieldWithPath("userDto.id").type(JsonFieldType.NULL).description("사용자 아이디")
                                , fieldWithPath("userDto.name").type(JsonFieldType.STRING).description("사용자 이름")
                                , fieldWithPath("userDto.hobby").type(JsonFieldType.STRING).description("사용자 취미")
                        )
                        , responseFields(
                                fieldWithPath("statusCode").type(JsonFieldType.NUMBER).description("상태코드"),
                                fieldWithPath("data").type(JsonFieldType.NUMBER).description("데이터"),
                                fieldWithPath("serverDatetime").type(JsonFieldType.STRING).description("응답시간")
                        )
                ));
```

2021-11-09 10:34 UTC, ksy90101 commented on src/test/java/com/kdt/bulletinboard/repository/PostRepositoryTest.java
> +    EntityManagerFactory entityManagerFactory;
접근제어자 붙여주세요.

2021-11-09 10:34 UTC, ksy90101 commented on src/test/java/com/kdt/bulletinboard/repository/PostRepositoryTest.java
> +@SpringBootTest
여기도 통합테스트를 할 필요가 있나요?

2021-11-09 10:34 UTC, ksy90101 commented on src/test/java/com/kdt/bulletinboard/controller/PostControllerTest.java
> +@SpringBootTest
여기도 통합테스트 인 이유가 있나요?

2021-11-16 02:09 UTC, GetMapping commented on src/main/java/com/kdt/bulletinboard/controller/PostController.java
> +    private PostService postService;
**생성자주입**
- 생성자 호출시점에 딱 1번만 호출되는 것이 보장됩니다.
- 생성자 주입은 객체를 생성할 때 딱 1번만 호출되므로 이후에 호출되는 일이 없습니다.
- 생성자 주입을 활용할 경우 값의 불변을 보장할 수 있으므로 final을 활용할 수 있습니다. 따라서 불변하게 설계할 수 있습니다.
- 의존성을 주입을 누락하는 것을 방지할 수 있습니다.


**필드주입**
- 코드가 간결하다는 장점이 있습니다.
- 외부에서 변경이 불가능해서 테스트 하기 힘들다는 치명적인 단점이 있습니다. 순수 자바로 테스트하기가 힘듭니다.

2021-11-22 05:58 UTC, GetMapping commented on src/main/java/com/kdt/bulletinboard/entity/User.java
> +    private List<Post> posts = new ArrayList<>();
포스트가 없더라도 유저는 생성되어야하기 때문에 null이 넘어가지 않도록 하기 위함인 것 같습니다.

2021-11-23 04:09 UTC, GetMapping commented on src/main/java/com/kdt/bulletinboard/dto/UserDto.java
> +public class UserDto {
객체 직렬화는 **객체의 상태를 바이트 스트림으로 변환하는데 사용되는 프로세스**이고, 역직렬화는 **바이트 스트림을 다시 객체형태로 변환하는 작업**입니다.
서버로 값이 전달될 때는 DTO가 객체로 정의되어 있는 경우 직렬화 로직을 지니고 있어 직렬화시켜 값을 변환합니다.

2021-11-23 06:12 UTC, ksy90101 requested changes
피드백 수정해주세요~

2021-11-23 06:12 UTC, ksy90101 commented on src/main/java/com/kdt/bulletinboard/ApiResponse.java
> +    private static final int STATUS_OK = 200;
HTTP_STUATS.OK 공통 상수가 이미 있어요. 이걸 사용하는게 더 좋아요.

2021-11-23 06:12 UTC, ksy90101 commented on src/main/java/com/kdt/bulletinboard/controller/MyExceptionHandler.java
> +    }
메서드명은 동사 쓰셔야 합니다  ㅎㅎㅎ

2021-11-23 06:12 UTC, ksy90101 commented on src/main/java/com/kdt/bulletinboard/dto/PostDto.java
> +    private UserDto userDto;
NotNull이 더 맞을거 같네요.

2021-11-23 06:12 UTC, ksy90101 commented on src/main/java/com/kdt/bulletinboard/dto/PostDto.java
> +public class PostDto {
응답과 요청을 분리해주세요.

2021-11-23 06:12 UTC, ksy90101 commented on src/main/java/com/kdt/bulletinboard/service/PostService.java
> +public class PostService {
상위에 @Transactional 붙이면 좋을거 같네요 ㅎㅎ

2021-11-23 06:12 UTC, ksy90101 commented on src/test/java/com/kdt/bulletinboard/controller/PostControllerTest.java
> +class PostControllerTest {
단위테스트로 변경하고 통합테스트를 따로 작성해주세요.

2022-03-16 09:22 UTC, closed without merging