[1기-P 심수현] JPA 게시판 만들기
prgrms-be-devcourse/SpringBoot-Board pull request #52
Opened 2021-10-19 09:37 UTC by suhyunsim

## 📌 과제 설명 
* 게시판 과제를 구현했습니다.

## 👩‍💻 요구 사항과 구현 내용 
### **요구 사항**

#### **SpringDataJPA 를 설정한다.**

- [x] datasource : h2 or mysql

#### **엔티티를 구성한다**

- [x] 회원(User)
    - id (PK) (auto increment)
    - name
    - age
    - hobby
    - **created_at**
    - **created_by**
- [x] 게시글(Post)
    - id (PK) (auto increment)
    - title
    - content
    - **created_at**
    - **created_by**
- [x] 회원과 게시글에 대한 연관관계를 설정한다.
    - 회원과 게시글은 1:N 관계이다.

- [x] 회원 Repository를 구현한다. (UserRepository)
- [x] 게시글 Repository를 구현한다. (PostRepository)

#### **API를 구현한다.**

- 게시글 조회
    - [x] 페이징 조회 (GET "/posts")
    - [x] 단건 조회 (GET "/posts/{id}")
- [x] 게시글 작성 (POST "/posts")
- [x] 게시글 수정 (POST "/posts/{id}")
- 회원 조회
    - [x] 회원 조회 (GET "/users")
    - [x] 단건 조회 (GET "/users/{id}")
- [x] 회원 작성 (POST "/users")
- [x] 회원 수정 (POST "/users/{id}")

#### **REST-DOCS를 이용해서 문서화한다.**
- [x] REST DOCS 작성

## ✅ PR 포인트 & 궁금한 점 
* Validation 체크를 위해 `Guava (Google Common Libraries) Base`를 사용했는데 `springframework util assert`와 비교해서 어떤 것을 사용하는게 더 좋을까요?
* setter 대신 정적 팩토리 메서드를 위주로 사용했는데 builder, 생성자, 정적팩토리 메서드 중 어떤걸 주로 사용해야 할 지 궁금합니다.
* DTO를 어떤 레이어에서 사용할지에 대해 고민이 많았습니다. [링크](https://tecoble.techcourse.co.kr/post/2021-04-25-dto-layer-scope/)를 참고해서 사실 service 단에서 사용하려고 했는데 구현하고 나니 테스트 코드를 작성하는데 어려움이 있어 다시 controller에서 사용하도록 변경했습니다. 어떤 방식으로 구현하는게 좋을지 궁금합니다.
* 현재 user와 post가 연관관계를 갖고 있는 상태인데 포스트의 api에 로그인 한 유저의 정보를 담고 싶어서 아직 해당 부분은 추가하지 않았습니다.
* rest한 응답을 주고 싶어서 Spring Hateoas를 적용해보려고 합니다.
* 응답과 예외처리에 대해 고민이 많은데 아직은 요청에 대한 성공 응답을 전부 ok로만 구현한 상태입니다.
* createdBy 필드에 대해 아직 어떤 방식으로 적용할 지 고민이 많습니다. BaseEntity를 BaseTimeEntity로 분리해서 User의 경우는 BaseTimeEntity의 필드만 사용하게 했고 Post의 경우 user와 createdBy를 어떤 식으로 구분해서 사용해야 할지 아직 잘 모르겠습니다. 현재 createdBy와 관련된 부분은 random한 uuid를 생성해서 배정하고 있습니다.
* 메세지와 관련된 부분을 좀 더 효율적으로 관리해보고 싶어서 MessageSourceAccessor를 사용했습니다.

2021-10-19 12:22 UTC, DevRunner21 reviewed
지나가다가 리뷰 남겨봅니다. ㅎ

2021-10-19 12:22 UTC, DevRunner21 commented on src/main/java/com/poogle/board/service/user/UserService.java
> +    }
커맨드성 메서드로보이는데,
여기에만 트랜젝션을 걸지 않으신 이유가 있나요?

2021-10-19 12:22 UTC, DevRunner21 commented on src/main/java/com/poogle/board/service/user/UserService.java
> +    @Transactional
readOnly 옵션을 주면 성능상 더 좋을 것 같습니다!

2021-10-19 12:22 UTC, DevRunner21 commented on src/main/java/com/poogle/board/model/post/Post.java
> +    }
writer값은 아직 사용하지 않고 있는것로 보이는데
어떤식으로 사용할 계획이신가요?

2021-10-19 12:22 UTC, DevRunner21 commented on src/main/java/com/poogle/board/converter/Converter.java
> +                .createdBy(post.getCreatedBy())
현재 Post에 CreatedBy로 작성자 ID를 넘겨주고 계신데,
PostEntity에 이 값이 과연 필요한 값인지 궁금합니다.
( 저도 이 값을 넣느냐 마느냐 고민이 되서.. ㅜㅜ )

User 조회 용도라면 이미 연관관계로 맺어진 User객체가 있기 때문에 
이 필드가 굳이 필요하다는 생각은 안드는데..

수현님의 의견은 어떠신가요??

2021-11-11 11:22 UTC, ksy90101 requested changes
다시 요청 주세요~

2021-11-11 11:22 UTC, ksy90101 commented on src/main/java/com/poogle/board/BoardApplication.java
> +    }
```suggestion
    @Bean
    public AuditorAware<String> auditorProvide() {
	    return () -> Optional.of(UUID.randomUUID().toString());
    }
```

2021-11-11 11:22 UTC, ksy90101 commented on src/main/java/com/poogle/board/controller/ApiError.java
> +    }
접근 제어자가 안붙어 있어요.

2021-11-11 11:22 UTC, ksy90101 commented on src/main/java/com/poogle/board/controller/ApiResult.java
> +    public static ApiResult<?> ERROR(String errorMessage, HttpStatus status) {
메서드명이 대문자네여.

?를 없앨수 있는 방법을 고민해보세요.

2021-11-11 11:22 UTC, ksy90101 commented on src/main/java/com/poogle/board/controller/ApiResult.java
> +    }
대문자네요.

2021-11-11 11:22 UTC, ksy90101 commented on src/main/java/com/poogle/board/controller/GeneralExceptionHandler.java
> +        if (e instanceof UnauthorizedException) return newResponse(e, HttpStatus.UNAUTHORIZED);
한줄코딩 안됩니다. if else로 하면 되지 않을까요?

2021-11-11 11:22 UTC, ksy90101 commented on src/main/java/com/poogle/board/controller/post/PostRequest.java
> +    private @NotEmpty String writer;
여기 수정 잘 해주세요.

2021-11-11 11:22 UTC, ksy90101 commented on src/main/java/com/poogle/board/controller/post/PostRequest.java
> +@Builder
https://velog.io/@lychee/%EC%9D%B4%ED%8E%99%ED%8B%B0%EB%B8%8C-%EC%9E%90%EB%B0%94-%EC%95%84%EC%9D%B4%ED%85%9C-2.-%EC%83%9D%EC%84%B1%EC%9E%90%EC%97%90-%EB%A7%A4%EA%B0%9C%EB%B3%80%EC%88%98%EA%B0%80-%EB%A7%8E%EB%8B%A4%EB%A9%B4-%EB%B9%8C%EB%8D%94%EB%A5%BC-%EA%B3%A0%EB%A0%A4%ED%95%98%EB%9D%BC

2021-11-11 11:22 UTC, ksy90101 commented on src/main/java/com/poogle/board/controller/user/UserController.java
> +    public ApiResult<UserResponse> user(@PathVariable Long id) {
user 명사. 메서드명은 동사입니다.

2021-11-11 11:22 UTC, ksy90101 commented on src/main/java/com/poogle/board/controller/user/UserRequest.java
> +    private @NotEmpty String hobby;
여기도 예쁘게 잘 해주세요.

2021-11-11 11:22 UTC, ksy90101 commented on src/main/java/com/poogle/board/error/NotFoundException.java
> +    static final String MESSAGE_DETAILS = "error.notfound.details";
접근제어자 붙여주세요.

2021-11-11 11:22 UTC, ksy90101 commented on src/main/java/com/poogle/board/service/post/PostService.java
> +    @Transactional
readOnly 해주세요.

2021-11-11 11:22 UTC, ksy90101 commented on src/main/java/com/poogle/board/service/post/PostService.java
> +    }
여긴 트랜잭션이 없네요.

2021-11-11 11:22 UTC, ksy90101 commented on src/main/java/com/poogle/board/service/user/UserService.java
> +    }
private 메서드는 맨 아래로 넣어주세요.

2021-11-11 11:22 UTC, ksy90101 commented on src/main/java/com/poogle/board/service/user/UserService.java
> +    @Transactional
readOnly 붙여주세요.

2021-11-11 11:22 UTC, ksy90101 commented on src/test/java/com/poogle/board/controller/post/PostControllerTest.java
> +    ObjectMapper objectMapper;
접근제어자 붙여주세요.

2021-11-11 11:22 UTC, ksy90101 commented on src/test/java/com/poogle/board/controller/user/UserControllerTest.java
> +    ObjectMapper objectMapper;
접근제어자 붙여주세요.

2021-11-11 11:22 UTC, ksy90101 commented on src/test/java/com/poogle/board/controller/user/UserControllerTest.java
> +        assertThat(user.getId()).isEqualTo(1L);
이거 필요 없습니다.

2021-11-11 11:22 UTC, ksy90101 commented on src/test/java/com/poogle/board/repository/post/PostRepositoryTest.java
> +    PostRepository postRepository;
접근제어자아아아아아

2021-11-11 11:22 UTC, ksy90101 commented on src/test/java/com/poogle/board/repository/post/PostRepositoryTest.java
> +        log.info("[*] modifiedAt: {}", post.getModifiedAt());
굳이 의미없는거 같아요.

2021-11-11 11:22 UTC, ksy90101 commented on src/test/java/com/poogle/board/repository/post/PostRepositoryTest.java
> +        log.info("[*] modifiedBy: {}", post.getModifiedBy());
의미없는거 같아요.

2021-11-11 11:22 UTC, ksy90101 commented on src/test/java/com/poogle/board/service/user/UserServiceTest.java
> +    private String hobby;
User user 를 하는게 더 좋지 않을까요?

2021-11-20 08:57 UTC, suhyunsim commented on src/main/java/com/poogle/board/service/user/UserService.java
> +    }
* `@Transactional(readOnly = true)`가 필요한 곳에는 메서드 단위로 적용하고 그 외에는 클래스 단위로 적용하도록 수정했습니다.

2021-11-20 10:05 UTC, ksy90101 requested changes
👍 테스트쪽 꼭 수정해보세요~

2022-03-16 09:22 UTC, closed without merging