[1기-C 최영권] JPA 게시판 만들기
prgrms-be-devcourse/SpringBoot-Board pull request #55
Opened 2021-10-20 18:41 UTC by choiyoungkwon12

## 📌 과제 설명 
Spring Boot , JPA 를 사용한 게시판 구현

## 👩‍💻 요구 사항과 구현 내용 
- 회원과 게시글에 대한 엔티티를 구성
- API 를 구현한다
- REST-DOCS 를 이용해서 문서화한다.

2021-11-09 11:10 UTC, ksy90101 requested changes
수정 하고 다시 요청주세요~
고생많으셨습니다 👍

2021-11-09 11:10 UTC, ksy90101 commented on src/main/java/com/misson/jpa_board/domain/Hobby.java
> +    }
메서드명을 의미있게 지워주세요.
0, 30은 매직넘버네요.

2021-11-09 11:10 UTC, ksy90101 commented on src/main/java/com/misson/jpa_board/domain/Hobby.java
> +    @Column(name = "user_hobby")
자체적으로 Column에 validation을 해보세요. length = 30 으로 적어주세여.

2021-11-09 11:10 UTC, ksy90101 commented on src/main/java/com/misson/jpa_board/domain/Post.java
> +    }
changePost 하나로 합치는게 더 좋을수 있습니다.

2021-11-09 11:10 UTC, ksy90101 commented on src/main/java/com/misson/jpa_board/domain/User.java
> +    private int age;
age가 음수일 경우가 없을거 같아요. valdiation 해주세요.

2021-11-09 11:10 UTC, ksy90101 commented on src/main/java/com/misson/jpa_board/domain/User.java
> +    }
위에 getter가 있는데 이거 왜 만드셨나요?

2021-11-09 11:10 UTC, ksy90101 commented on src/main/java/com/misson/jpa_board/dto/PostDto.java
> +@Builder
빌더가 난발하네요. 빌더를 쓰는 이유가 뭘까요?

2021-11-09 11:10 UTC, ksy90101 commented on src/main/java/com/misson/jpa_board/dto/PostDto.java
> +    }
Dto에 setter는 필요 없습니다.

DTO는 과연 어떻게 직렬화 역직렬화를 할까요!? 어떻게 구현을 해놔야 할까요?

2021-11-09 11:10 UTC, ksy90101 commented on src/main/java/com/misson/jpa_board/service/PostService.java
> +        Post post = postRepository.findById(id).orElseThrow(() -> new NoSuchElementException("아이디와 일치하는 게시물이 없습니다."));
```suggestion
        Post post = postRepository.findById(id)
        .orElseThrow(() -> new NoSuchElementException("아이디와 일치하는 게시물이 없습니다."));
```

2021-11-09 11:10 UTC, ksy90101 commented on src/test/java/com/misson/jpa_board/controller/PostRestControllerTest.java
> +                                fieldWithPath("data.userId").type(JsonFieldType.NUMBER).description("userId")
description 성의있게 작성해주세요.

2021-11-09 11:10 UTC, ksy90101 commented on src/test/java/com/misson/jpa_board/service/PostServiceTest.java
> +    UserService userService;
접근제어자를 적어주세요.

2021-11-09 11:10 UTC, ksy90101 commented on src/test/java/com/misson/jpa_board/service/PostServiceTest.java
> +    @Transactional
최 상위에서 Trasaction 걸어두는게 더 좋을거 같아요.

2021-11-10 10:08 UTC, choiyoungkwon12 commented on src/main/java/com/misson/jpa_board/domain/User.java
> +    private final List<Post> posts = new ArrayList<>();
1. NPE 방지

2. 하이버네이트가 엔티티를 영속화 할 때 내부에서 컬렉션이 있으면 하이버네이트가 특별하게 조작한 컬렉션으로 변경합니다.(하이버네이트에서 사용하는 래퍼 컬렉션)
그런데 개발자가 임의로 나중에 new ArrayList로 초기화를 하게 되면 이 부분이 하이버네이트가 관리하는 컬렉션에서 개발자가 직접 만든 컬렉션으로 변경될 수 있습니다. 그러면 하이버네이트가 정상 동작하지 않습니다. 
이런 문제를 방지하기 위해 필드에서 빠르게 컬렉션을 초기화 하고, 해당 컬렉션을 바꾸는 행위를 막도록 코드를 작성하는 것이 좋다 라고 합니다

2021-11-10 20:36 UTC, choiyoungkwon12 commented on src/main/java/com/misson/jpa_board/dto/PostDto.java
> +    }
DTO를 직렬화/역직렬화 할때는 jackson과 같은 라이브러리를 사용하고 역/직렬화를 하는 방법은 다양한데 jackson에서는 기본적으로 public 필드만 직렬화, 역직렬화가 가능하다고 합니다.
private 필드를 역/직렬화 하는 방법은 getter를 생성해주면 역/직렬화가 가능합니다.
그래서 역/직렬화를 하기 위해서는 private 필드에 대한 getter 메서드를 생성해주면 될 것 같습니다.
참고

2021-11-11 05:26 UTC, choiyoungkwon12 commented on src/main/java/com/misson/jpa_board/dto/PostDto.java
> +@Builder
생성자에 매개변수가 많아지게 될 때 고려할 사항이 빌더 패턴인데 이 경우 그냥 생성자를 사용해도 괜찮겠네요

2021-11-20 08:17 UTC, ksy90101 requested changes
고생하셨습니다 👍 
수정만 하시고 마지막 최종 점검 가시쥬!

2021-11-20 08:17 UTC, ksy90101 commented on src/main/java/com/misson/jpa_board/common/ControllerExceptionHandler.java
> +    public ResponseEntity<String> NoSuchElementException(NoSuchElementException e) {
메서드명은 동사이고 카멜케이스로 작성하셔야 합니다.

2021-11-20 08:17 UTC, ksy90101 commented on src/main/java/com/misson/jpa_board/controller/PostRestController.java
> +    public ResponseEntity<Long> save(@RequestBody @Validated PostCreateRequest PostCreateRequest) throws NoSuchElementException {
매개변수명도 카멜케이스로 해주세요~
```suggestion
    public ResponseEntity<Long> save(@RequestBody @Validated PostCreateRequest postCreateRequest) throws NoSuchElementException {
```

2021-11-20 08:17 UTC, ksy90101 commented on src/main/java/com/misson/jpa_board/domain/User.java
> +import java.math.BigDecimal;
이건 안쓰이네요!?

2021-11-20 08:17 UTC, ksy90101 commented on src/main/java/com/misson/jpa_board/controller/PostRestController.java
> +        log.info("게시글 작성");
로그는 삭제해주시면 좋을거 같아요.

2021-11-20 08:17 UTC, ksy90101 commented on src/main/java/com/misson/jpa_board/controller/PostRestController.java
> +        URI uri = URI.create("/posts");
created에 URI에는 id를 넣어서 단일 엔티티 get uri를 내려주는것입니다 :)

2021-11-20 08:17 UTC, ksy90101 commented on src/main/java/com/misson/jpa_board/controller/PostRestController.java
> +        return ResponseEntity.ok(postService.postFindById(id));
로그 다 지워주세요.

2021-11-20 08:17 UTC, ksy90101 commented on src/main/java/com/misson/jpa_board/controller/PostRestController.java
> +    public ResponseEntity<PostDto> postFindById(@PathVariable(value = "id") Long id) throws NotFoundException {
변수명과 위의 명명이 똑같다면 valude는 생략 가능합니다.

2022-03-16 09:22 UTC, closed without merging