[2기-C 남득윤] JPA 게시판 미션 - '엔티티 구성' 까지
prgrms-be-devcourse/SpringBoot-Board pull request #59
Opened 2022-05-11 09:02 UTC by ndy2

## 📌 과제 설명
회원과 게시글로 구성된 게시판 api구현 미션입니다.

## 👩‍💻 요구 사항과 구현 내용
과제 [링크](https://ancient-citron-06b.notion.site/SpringBoot-Part4-7-632dd10678164daca96a5ea185a02b60)입니다.

SpringDataJPA 를 설정한다. + 엔티티를 구성한다. 까지 진행하였습니다.
jpa를 아직은 전혀 활용하지 않았지만 일단 엔티티에서 필요하다고 생각되는 어노테이션들만 달아주었습니다.

테이블 생성 및 auditing 기능의 검증까지 진행해서 확인을 하려고 하니 리포지토리와 서비스 까지 내용이 조금 커질거 같아서 도메인 엔티티까지만 PR하였습니다.

현재 연관관계는 Post -> User 로 단방향으로만 설정하였고 이후 서비스 구현시 필요하다면 양방향을 고려하겠습니다.

## ✅ PR 포인트 & 궁금한 점 
`Post` 생성시 `user` (writer)의 id가 null이되는 경우 생성시 예외를 발생 시키고 싶은데

`User` 엔티티의 id 필드는 리포지토리를 한번 타고 와야 채워지기 때문에 현재 구현에서는 검증하지 못하였습니다.

그렇다고 도메인 엔티티의 테스트에 `@SpringBootTest` 를 달고 리포지토리를 주입받아 아이디가 채워진 `User`를 받아서 테스트를 하는것도 이상한거 같고 리플렉션을 사용하는것도 이상한것 같은데 좋은 방법이 있을까요?

2022-05-11 11:16 UTC, woogiekim requested changes
기능 하나하나씩 구현해 나갈때 도메인에 기능이 추가되려나 보군요 ㅎㅎㅎ
어떤 기능들이 들어갈까 궁금해지네요! 😄 

고생하셨고 코멘트 봐주시면 좋을거같습니다.

2022-05-11 11:16 UTC, woogiekim commented on src/main/java/com/study/board/domain/post/domain/Post.java
> +    private static final int POST_TITLE_MAX_LENGTH = 255;
255 로 제약 두시는거면, Column 에도 length 적용해두면 어떨까 싶어요

2022-05-11 11:16 UTC, woogiekim commented on src/main/java/com/study/board/domain/post/domain/Post.java
> +    @ManyToOne(fetch = LAZY)
디폴트가 LAZY 일텐데 명시한 이유가 있나요?

2022-05-11 11:16 UTC, woogiekim commented on src/main/java/com/study/board/domain/post/domain/Post.java
> +        return new Post(null, title, content, writer);
아이디를 왜 굳이 넣어주시나요?

2022-05-11 11:16 UTC, woogiekim commented on src/main/java/com/study/board/domain/support/auditing/BaseEntity.java
> +}
여기에 아이디도 같이 만들게 하는것은 어떨까 싶기도해요
pk 는 시퀀설하게 보통 하는 편이니 바꿔 사용할 일이 없어보입니다.

2022-05-11 11:16 UTC, woogiekim commented on src/main/java/com/study/board/domain/user/domain/User.java
> +    }
왜 옵셔널로 만들어서 리턴해주나요?

2022-05-11 11:16 UTC, woogiekim commented on src/main/java/com/study/board/domain/user/domain/User.java
> +    }
왜 옵셔널로 파라미터를 받으시나요?

2022-05-11 11:16 UTC, woogiekim commented on src/test/java/com/study/board/domain/post/domain/PostTest.java
> +    void 생성_성공_auditing_적용_x() {
개인적으로 audit 으로 날짜 자동 넣어주는걸 안좋아하는 이유 중에 하나가
이런식으로 도메인 테스트에 제약이 생겨버린다는 점입니다.
이 부분은 어떻게 보나요?
도메인에서 audit을 했는지 안했는지 알아야할 이유가 있을까? 이런 생각이 드네요

2022-05-11 11:16 UTC, woogiekim commented on src/test/java/com/study/board/domain/post/domain/PostTest.java
> +        String title = RandomString.make(255 + 1);
애초에 length 를 public 으로 풀고 상수로 하면

해당 상수로 할수있어서 길이 바꾼다고 테스트가 깨지거나 할 일이 없지 않을까?

라는 생각이 드네요

2022-05-11 11:16 UTC, woogiekim commented on src/test/java/com/study/board/domain/user/domain/UserTest.java
> +    }
이게 과연 필요한 테스트 일까요?

2022-05-11 11:16 UTC, woogiekim commented on src/test/java/com/study/board/domain/user/domain/UserTest.java
> +        String name = RandomString.make(50 + 1);
이 매직넘버도 위에 말씀드린것과 마찬가지인거같습니다.

2022-05-11 11:16 UTC, woogiekim commented on src/test/java/com/study/board/fixture/Fixture.java
> +    }
아무리 픽스쳐라고해도 method 이름이 user 인것은 조금 이상해요

aUser 혹은 createUser 혹은 prepareUser

이런 네이밍으로 해주는편이 좋아보입니다.

2022-05-11 11:24 UTC, hymn-fly commented
먼저 pr 날려주셔서 잘 보고갑니다 득윤님! 
setter를 사용하지 않고 constructor로도 JPA활용이 가능하군요ㅎㅎ 잘알아갑니다~~

2022-05-11 12:05 UTC, ndy2 commented on src/main/java/com/study/board/domain/post/domain/Post.java
> +    private static final int POST_TITLE_MAX_LENGTH = 255;
넵!

2022-05-11 12:06 UTC, ndy2 commented on src/main/java/com/study/board/domain/post/domain/Post.java
> +    @ManyToOne(fetch = LAZY)
엇 @ManyToOne에서 default가 Eager 인것 같습니다.

2022-05-11 12:07 UTC, ndy2 commented on src/main/java/com/study/board/domain/post/domain/Post.java
> +        return new Post(null, title, content, writer);
jdbc 하다가 와서 습관적으로 그만..
제거하겠습니다.

2022-05-11 12:15 UTC, ndy2 commented on src/test/java/com/study/board/domain/user/domain/UserTest.java
> +    }
뭔가 주문과 바우처의 관계를 떠올리고 Optional 로 잡았는데
회원과 취미의 경우 취미의 유무에 따라 서비스에서 로직이 달라질 일이 없기때문에 Optional을 사용할 필요가 없겠네요.

위 테스트도 필요없는것 같습니다.

2022-05-11 12:41 UTC, ndy2 commented on src/test/java/com/study/board/domain/post/domain/PostTest.java
> +    void 생성_성공_auditing_적용_x() {
음.. 맞는 의견 같습니다.
엔티티의 필드가 jpa에 의존해서 생기는 제약이 도메인 테스트에 영향을 주고 있다는 말씀이군요. 

근데 생각해보니 id 도 마찬가지 아닌가요?
제가 위에 궁금한 점에 id 에서  말씀하신 제약과 같은 테스트에서의 제약을 만나서 고민하다가 내용을 적어 놓았습니다.

id와 auditing은 의미상 차이가 있을까요??

2022-05-12 04:50 UTC, ndy2 commented on src/test/java/com/study/board/domain/post/domain/PostTest.java
> +    void 생성_성공_auditing_적용_x() {
아 엔티티 필드와 db의 column을 꼭 1-1 매핑 시킬 필요가 없다는 말씀 일까요?

만약 그렇다면 repository에서 데이터를 퍼올릴때 dto의 형태에 맞춰서 조회를 하는 딱딱함이 생길수도 있겠군요
엔티티의 순수함과 잘 저울질 해서 고민해야할 문제 같네요

2022-05-12 06:31 UTC, ndy2 commented
리뷰 바탕으로 고민해보고 개선해보았습니다.

도메인 쪽에서 여부가 관심없다는 의견에 대해서 고민해보았는데 맞는 말씀같습니다.
그래서 auditing 필드를 baseEntity에서 제거하였습니다.

근데 게시글의 경우 작성일시에 대해서 서비스나 컨트롤러 레이어에서 관심을 가질 수 있을거 같아서 writtenDateTime이라는 필드로 남기는 것이 적절하다고 생각되어서 객체 생성시에 수동으로 넣어주는 방식을 선택하였습니다.

확인 부탁드립니다!

2022-05-13 04:57 UTC, woogiekim commented on src/main/java/com/study/board/domain/post/domain/Post.java
> +    @ManyToOne(fetch = LAZY)
착각했네요 ㅎ ㅠ

2022-05-13 05:04 UTC, woogiekim approved these changes
코멘트 남겨주신부분 확인 해봐주시고

다음 단계로 넘어가시면 될거같습니다!

2022-05-13 05:04 UTC, woogiekim commented on src/main/java/com/study/board/domain/user/domain/User.java
> +        if (hobby != null) {
if문을 안쓰고 check 시리즈 하는 이유가 무엇이라고 생각하시나요?

2022-05-13 05:04 UTC, woogiekim commented on src/test/java/com/study/board/domain/user/domain/UserTest.java
> +    void 이름의_길이가_50_보다_크면_생성실패() {
테스트명이 구체적인 코드내용을 너무 많이 알고 있는것 같습니다

2022-05-13 05:04 UTC, woogiekim commented on src/main/java/com/study/board/domain/user/domain/User.java
> +    public static User create(String name, String hobby) {
이거랑 그냥 생성자로 만드는거랑 무슨 차이가 있나요?

2022-05-13 05:04 UTC, merged

2022-05-13 05:09 UTC, ndy2 commented on src/main/java/com/study/board/domain/user/domain/User.java
> +        if (hobby != null) {
아 null 체크 분기분을 판별식 안으로 넣으면 되는군요...
이럴수가...

2022-05-13 05:16 UTC, ndy2 commented on src/main/java/com/study/board/domain/user/domain/User.java
> +    public static User create(String name, String hobby) {
메서드 명으로 생성의 의도를 드러내기 위함이었는데 
현재 단계에서는 서비스에서 사용하는 부분이 안 드러나서 없어도 될것 같긴 하네요