[2기-C 황승한] JPA 게시판 미션 - 도메인 구성 & 테스트
prgrms-be-devcourse/SpringBoot-Board pull request #62
Opened 2022-05-12 16:10 UTC by seunghan0421

👩‍💻 구현 내용
JPA 게시판 미션 도메인 구성까지 구현하였습니다!

* 회원(User) , 게시글(Post) 엔터티 작성
* User, post 테스트 작성

감사합니다!

2022-05-14 05:34 UTC, woogiekim requested changes
질문드린 부분에 대해서 고민한번 해보시면 좋을거같습니다.

2022-05-14 05:34 UTC, woogiekim commented on src/main/java/org/prgms/board/domain/post/domain/Post.java
> +	@ManyToOne(fetch = FetchType.LAZY)
FetchType.LAZY 는 왜 하시는거에요?

2022-05-14 05:34 UTC, woogiekim commented on src/main/java/org/prgms/board/domain/post/domain/Post.java
> +	public void setUser(User user) {
관례로 사용하던 set 이라는 네이밍을 피해서

addWriter, withWriter

모 이런식은 어떨까 싶어요

2022-05-14 05:34 UTC, woogiekim commented on src/main/java/org/prgms/board/domain/post/domain/Post.java
> +		}
이건 뭘하는건가요?

2022-05-14 05:34 UTC, woogiekim commented on src/main/java/org/prgms/board/domain/post/domain/Post.java
> +	private User user;
writer 처럼 같은 명확한 의미를 줬으면 어떨까? 라는 생각도 듭니다.

2022-05-14 05:34 UTC, woogiekim commented on src/main/java/org/prgms/board/domain/post/domain/Post.java
> +public class Post {
Post 라는게 뭘하는 엔티티인지 설명이 없는게 아쉬운부분입니다.

2022-05-14 05:34 UTC, woogiekim commented on src/main/java/org/prgms/board/domain/post/domain/Post.java
> +	// 얀관관계 편의 메서드 START
좋은 주석 활용방법은 아닌거같습니다.
javadoc 에 대한 내용을 살펴보는 편이 좋겠습니다.

2022-05-14 05:34 UTC, woogiekim commented on src/test/java/org/prgms/board/domain/post/domain/PostTest.java
> +		assertThat(post.getContent()).isEqualTo(content);
title이랑 content만 검증하면 되는걸까요?

2022-05-14 05:34 UTC, woogiekim commented on src/test/java/org/prgms/board/domain/post/domain/PostTest.java
> +	}
이렇게 하나의 테스트에 실패하는 케이스를 다 넣는 이유는 무엇인가요?

2022-05-14 05:34 UTC, woogiekim commented on src/test/java/org/prgms/board/domain/post/domain/PostTest.java
> +	void setPost_test() {
뭘하겠다는 테스트인건지 모르겠어요

2022-05-14 05:34 UTC, woogiekim commented on src/test/java/org/prgms/board/domain/post/domain/PostTest.java
> +		assertThat(savedUser.getAge()).isEqualTo(age);
유저에 대한 검증을 언제까지 해야하는건가요?

도메인 > 리포지토리 > 서비스 > 컨트롤러

다 해줘야 안심이 되나요?

2022-05-14 05:34 UTC, woogiekim commented on src/main/java/org/prgms/board/domain/user/domain/User.java
> +	@OneToMany(mappedBy = "user", cascade = CascadeType.ALL, orphanRemoval = true)
이거는 왜 CascadeType.ALL 인가요?

2022-05-14 13:58 UTC, jk05018 commented on src/main/java/org/prgms/board/domain/post/domain/Post.java
> +	@ManyToOne(fetch = FetchType.LAZY)
@OneToOne, @ManyToOne 과 같은 경우 기본 전략은 FetchType.EAGER라고 설정되어 있습니다.
이 전략에 따른다면 user를 조회할 때 항상 post도 조회하는 쿼리가 나가게 됩니다. 그렇기에 post가 불필요한 상황에도 추가 쿼리가 나가게 되는 것으로 알고 있습니다.

제가 공부하기로는 @XXXToOne의 경우 FetchType을 LAZY로 설정해서 지연로딩의 기능을 사용하고 User를 조회할 시 항상 post가 필요 할 경우에는 JPQL의 fetch join 기능을 사용하여 메서드를 제공하는 것이 성능적으로 더 낫다고 공부했고, 저도 괜찮은 방법인 것 같아서 이 방법을 사용하려 합니다!

2022-05-14 14:00 UTC, jk05018 commented on src/main/java/org/prgms/board/domain/post/domain/Post.java
> +	public void setUser(User user) {
넵! 위의 writer도 그렇게 변수의 메서드의 네이밍에 대해서 많이 생각을 해보지 않은 것 같습니다! 다음부터 네이밍에 대해서도 고민해 보겠습니다.

2022-05-14 14:04 UTC, jk05018 commented on src/main/java/org/prgms/board/domain/user/domain/User.java
> +	@OneToMany(mappedBy = "user", cascade = CascadeType.ALL, orphanRemoval = true)
처음에 domain을 계획할 때 user에 post를 추가하면 자동으로 persist, remove 되도록 영속성 전이를 줄 생각이었었습니다. 
하지만 아직 제가 Cascade에 대해서 완벽하게 이해하고 적용할 수 있는지 확신할 수 없어 cascade 적용에 대해서는 조금 더 고민해 보도록 하겠습니다.

2022-05-14 14:26 UTC, jk05018 commented on src/test/java/org/prgms/board/domain/post/domain/PostTest.java
> +	void setPost_test() {
피드백 주신 대로 도메인을 재구성하고 삭제하였습니다!

2022-05-14 14:30 UTC, jk05018 commented on src/test/java/org/prgms/board/domain/post/domain/PostTest.java
> +	}
저번에도 동일한 피드백을 주신 것 같은데 제가 반영하지 못했습니다!
테스트 목적을 명확하게 하고, 목적마다 분리하겠습니다!

2022-05-14 14:39 UTC, jk05018 commented
우기님께 피드백을 받은 내용을 바탕으로 리팩터링을 진행했습니다.
- 변수명, 메서드면 직관적으로 변경 + 클래스 및 주요 변수에 대한 설명 추가
- 불필요한 메서드 제거
- 테스트 목적별로 분리
감사합니다!

2022-05-17 12:13 UTC, woogiekim approved these changes
리뷰드린내용 잘 반영해주신거 같습니다! 💯

몇가지 코멘트를 추가로 남겼으니 확인해보시면 좋겠습니다!

2022-05-17 12:13 UTC, woogiekim commented on src/test/java/org/prgms/board/domain/post/domain/PostTest.java
> +		assertThat(post.getWriter().getAge()).isEqualTo(25);
작성자의 상세정보까지 검증할 이유는 없다고 보긴합니다
작성자 테스트에서 잘 하고 있겠죠 아니면 해줘야하구요

2022-05-17 12:13 UTC, woogiekim commented on src/test/java/org/prgms/board/domain/post/domain/PostTest.java
> +	void create_post_fail_with_wrong_title() {
디스플레이네임으로 테스트명을 표현해주시는거면

메서드이름을 test01, test02 ...

이런식으로 해주는것도 방법인거같습니다

2022-05-17 12:13 UTC, woogiekim commented on src/test/java/org/prgms/board/domain/post/domain/PostTest.java
> +	@DisplayName("title이 1자 이상 255자 이하가 아닐 때 Post update 실패 테스트")
테스트명에서 구현에 대한 상세한 내용을 너무 구체적으로 알고 있는거같아요

길이가 100으로 바뀌면 어떤가요?

테스트명도 변경되야하지 않을까요?

2022-05-17 12:13 UTC, woogiekim commented on src/test/java/org/prgms/board/domain/user/domain/UserTest.java
> +		assertThat(user.getAge()).isEqualTo(age);
기대값을 하드코딩해주는것도 방법중에 하나인거같습니다

눈에 잘들어와서 테스트를 읽기 좋을거같긴합니다

2022-05-17 13:26 UTC, merged