[2기-C 길근오] PostRepository 구현 & 테스트, 피드백 반영
prgrms-be-devcourse/SpringBoot-Board pull request #63
Opened 2022-05-13 08:44 UTC by hymn-fly

## 👩‍💻 요구 사항과 구현 내용
 - PostRepository 구현
 - PostRepository 테스트코드

## ✅ 피드백 반영사항 
 - Fixture 이용
 - UuidUtils validation 로직을 User 도메인 안으로 이동
 - createdBy 부분 BasicEntity에서 제거, Post, User에서 따로 관리

## ✅ PR 포인트 & 궁금한 점
 - UUID validation 로직을 그냥 도메인(User) 안에 작성을 해도 괜찮을지요??

 - createdBy를 User에서는 그냥 아예 없앴고, Post에서는 연관관계로 매핑된 user를 createdBy의 대용으로 생각했습니다. 이렇게 하는게 조금더 객체지향에 가까운 것일까요??

2022-05-13 10:46 UTC, woogiekim requested changes
writer로 바꿔주신부분은 제가 생각하기에는 좋다고 봅니다.

테스트작성에 아쉬운 부분이 있는데
코멘트 확인해주시면 좋을거같습니다!

2022-05-13 10:46 UTC, woogiekim commented on springboot/src/main/java/org/spring/notice/domain/post/Post.java
> +    @ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.ALL)
케스케이드를 넣는 기준이 어떻게 되나요?

2022-05-13 10:46 UTC, woogiekim commented on springboot/src/main/java/org/spring/notice/domain/post/Post.java
>      private User user;
기왕 writer 라는 네이밍을 사용했으니 여기도 적용하는건 어떤가요? 일관성있게요

2022-05-13 10:46 UTC, woogiekim commented on springboot/src/main/java/org/spring/notice/domain/user/User.java
>      private String uuid;
이게 왜 필요한건지 사실 궁금하긴합니다

2022-05-13 10:46 UTC, woogiekim commented on springboot/src/main/java/org/spring/notice/domain/user/User.java
>      }
이건 좋은 선택은 아닌거같네요

제가 물어본 의도는

true false로 리턴해줘야 하는가? 입니다

유효하지않은 uuid 가 들어온거면 이거는 버그 아니면 공격 둘중하나 아닐까요?

2022-05-13 10:46 UTC, woogiekim commented on springboot/src/test/java/org/spring/notice/domain/post/PostRepositoryTest.java
> +        assertThat(posts).containsExactly(post1);
테스트가 빈약해요

이걸로 정말로 타이틀로 검색해서 포스팅을 가져왔다고 확신할수 있을까요?

2022-05-13 10:46 UTC, woogiekim commented on springboot/src/test/java/org/spring/notice/domain/post/PostRepositoryTest.java
> +    }
이거 할필요없이 테스트 클래스에 트랜잭셔널 붙이면 롤백이 됩니다.

2022-05-13 10:46 UTC, woogiekim commented on springboot/src/test/java/org/spring/notice/domain/post/PostRepositoryTest.java
> +    }
무엇을하고싶은건지 모르겠습니다

2022-05-13 10:46 UTC, woogiekim commented on springboot/src/test/java/org/spring/notice/domain/post/PostTest.java
> +        assertThat(post.getUser()).usingRecursiveComparison().isEqualTo(createUser());
using...

이 부분은 왜하는 건가요?

2022-05-13 10:46 UTC, woogiekim commented on springboot/src/test/java/org/spring/notice/domain/user/UserTest.java
> +        assertThat(user.getUuid()).isEqualTo(id);
이것만 확인해봐도 될까요?

2022-05-13 11:32 UTC, hymn-fly commented on springboot/src/main/java/org/spring/notice/domain/user/User.java
>      private String uuid;
아 uuid를 쓰면 나중에 db를 바꾸거나 옮길때 도움이 된다는 이야기를 어디서 들었어서 한번 써봤습니다..!
사실 Long으로 하는게 일반적이긴 하겠죠

2022-05-13 11:37 UTC, hymn-fly commented on springboot/src/main/java/org/spring/notice/domain/post/Post.java
> +    @ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.ALL)
아 이부분을 명시적으로 하지 못했네요 post를 만들 때 writer를 parameter로 넣어서 받으니, PERSIST와 
post 데이터를 새롭게 refresh 할 때 user도 refresh 하도록 두개의 CascadeType만 적용하도록 하겠습니다

2022-05-13 11:58 UTC, hymn-fly commented on springboot/src/test/java/org/spring/notice/domain/post/PostTest.java
> +        assertThat(post.getUser()).usingRecursiveComparison().isEqualTo(createUser());
동일성 비교 뿐 아니라 안에 있는 필드들까지 다 비교하기 위해서 사용하는 걸로 알고 사용했는데 사실 id가 같으면 같은거니 굳이 사용하지 않아도 될것같긴하네요

2022-05-13 12:02 UTC, hymn-fly commented on springboot/src/test/java/org/spring/notice/domain/post/PostRepositoryTest.java
> +    }
연관관계를 이용해서 post로부터 user를 가지고 오는것을 테스트하려고 했는데 생각해보니 당연한거라 테스트 안해도 될것같기도합니다. 아직은 테스트해야 할 기준이 명확하지가 않네요,,

2022-05-13 12:47 UTC, hymn-fly commented on springboot/src/main/java/org/spring/notice/domain/post/Post.java
>      private User user;
넵!

2022-05-20 11:27 UTC, woogiekim commented on springboot/src/main/java/org/spring/notice/domain/user/User.java
>      private String uuid;
이뤄지지않을 혹은 너무 먼 미래를 걱정한거 같습니다

해당 코드는 결국 기술부채가 될 가능성이 커보입니다

2022-05-20 11:38 UTC, woogiekim approved these changes
다음 진행을 위해서 어프로브 하겠습니다.

코멘트 확인해주시고 궁금한점은 DM주세요

2022-05-20 11:38 UTC, woogiekim commented on springboot/src/main/java/org/spring/notice/domain/user/User.java
> +        }
이거는 굳이라는 생각이 들어요

메시지 찍으려고 트라이 캐치로 잡아줘야하나?

uuid 만드는 주체는 서버인데...? 라는 생각이 들어오

2022-05-20 11:38 UTC, woogiekim commented on springboot/src/test/java/org/spring/notice/domain/post/PostRepositoryTest.java
> +        assertThat(test2_posts).containsExactlyInAnyOrder(post2, post5);
이거는 검색을 위한것인가여?

그렇다면 페이징이 필요하지않나라는 생각이 듭니다

2022-05-20 11:38 UTC, merged