[1기-P] 김은서- JPA 게시판 만들기
prgrms-be-devcourse/SpringBoot-Board pull request #7
Opened 2021-10-11 06:52 UTC by eunseo2

## 📌 과제 설명 
- SpringDataJPA를 활용한 게시판 구현
## 👩‍💻 요구 사항과 구현 내용 
### Entity
- [x] 회원(User)
- [x] 게시글(Post)
- [x] 회원과 게시글에 대한 연관관계를 설정한다.
    * [x] 회원과 게시글은 1:N 관계이다.

### REST API
- [x] 게시글 조회
    * [x] 페이징 조회 (GET "/posts")
    * [x] 단건 조회 (GET "/posts/{id}")
- [x] 게시글 작성 (POST "/posts")
- [x] 게시글 수정 (POST "/posts/{id}")
- [x] 게시글 삭제 (Delete "/posts/{id}")

### REST DOCS
* [x] REST-DOCS를 이용해서 문서화한다.
## ✅ 피드백 반영사항  
- 공통 Post Response 추가
- 불필요한 @transactional 제거
- 필드-> 생성자 의존성 주입으로 변경
## ✅ PR 포인트 & 궁금한 점 
- 예외처리 부분 
- Dto

2021-10-18 04:58 UTC, 0923kdh requested changes

2021-10-18 04:58 UTC, 0923kdh commented on springBoard/src/main/java/com/programmers/springboard/error/GlobalExceptionHandler.java
> +        log.error("handleDataException throw Exception : {}", ErrorCode.DUPLICATE_RESOURCE);
GlobalExceptionHandler에 log를 찍는것도 좋은 것 같습니다. 그런데 궁금한점은 모든 Exception에서 로그를 찍는게 유의미한 정보를 얻을 수 있을까? 라는 생각도 드네요! 은서님 생각은 어떠신가요?

2021-10-18 04:58 UTC, 0923kdh commented on springBoard/src/main/java/com/programmers/springboard/model/BaseEntity.java
> +    private LocalDateTime createdAt;
개행을 추가해주시는것도 가독성 측면에서 좋을 것 같습니다~!

2021-10-18 04:58 UTC, 0923kdh commented on springBoard/src/main/java/com/programmers/springboard/model/Post.java
> +        this.setCreatedAt(LocalDateTime.now());
update를 하는 로직에서 setCreatedAt을 해주는이유가 있을까요 ?

2021-10-18 04:58 UTC, 0923kdh commented on springBoard/src/main/java/com/programmers/springboard/dto/PostDto.java
> +public class PostDto {
bean validation을 이용해서 dto에 대한 검증을 해주면 더 좋지않을까 생각합니다!

2021-10-18 06:54 UTC, 0923kdh commented
고생하셨습니다!!🎊🎊🎊🎊🎊

2021-10-18 09:38 UTC, Heejeong01110 reviewed
안녕하세요 은서님!! 저번에 이어서 또 코드리뷰 하게 됐습니다ㅎㅎ
예외 처리하신 부분 코드 읽으면서 공부가 많이 된 것 같아요! 이외에 다른부분도 배워가는 부분이 많았습니다!!

2021-10-18 09:38 UTC, Heejeong01110 commented on springBoard/src/main/java/com/programmers/springboard/model/Post.java
> +        this.setCreatedAt(LocalDateTime.now());
이부분도 update할 때 createdAt 값을 넣는게 어색하네요!

2021-10-18 09:38 UTC, Heejeong01110 commented on springBoard/src/main/java/com/programmers/springboard/error/ErrorResponse.java
> +}
은서님 코드 보면서 custom error를 어떻게 작성해야 하는지 공부 많이 된거같아요!! 👍👍👍

2021-10-18 09:38 UTC, Heejeong01110 commented on springBoard/src/main/java/com/programmers/springboard/model/Post.java
> +public class Post extends BaseEntity {
`@AllArgsConstructor`, `@Builder`가 쓰이는 부분을 찾지 못했는데 사용하지 않으면 지우는게 좋을것 같네요!

2021-10-19 00:53 UTC, eunseo2 commented on springBoard/src/main/java/com/programmers/springboard/model/Post.java
> +        this.setCreatedAt(LocalDateTime.now());
앗.. 이건 저의 실수입니다..
updatedAt을 만들었어야 하는데 
createdAt만 있어서 헷갈렸던 것 같습니다..!
수정했습니다!

2021-10-19 00:54 UTC, eunseo2 commented on springBoard/src/main/java/com/programmers/springboard/dto/PostDto.java
> +public class PostDto {
아직 bean validation을 공부하지 않아서
추후 공부한 후 적용시켜보도록 하겠습니다 👍

2021-10-19 00:57 UTC, eunseo2 commented on springBoard/src/main/java/com/programmers/springboard/controller/PostController.java
> +@RequestMapping("/api")
음! 저는 @GetMapping만 쓰는 것을 선호하지 않아서 
@GetMapping("/posts/{id}") 를 쓰고 싶어서 /posts는 묶지 않았습니다!

2021-10-19 03:09 UTC, 0923kdh approved these changes

2021-10-24 01:56 UTC, Jo-GyuHyeon requested changes

2021-10-24 01:56 UTC, Jo-GyuHyeon commented on springBoard/src/main/java/com/programmers/springboard/controller/PostController.java
> +        Long id = postService.save(postDto);
return 전에 new line 을 하는것이 좋을 것 같습니다.
한줄 로 작성할 수 있는 로직은 한줄로 표현 하는 것은 어떨까요?

2021-10-24 01:56 UTC, Jo-GyuHyeon commented on springBoard/src/main/java/com/programmers/springboard/error/ErrorCode.java
> +    POSTS_NOT_FOUND(NOT_FOUND, "게시글을 찾을 수 없습니다."),
에러 메시지를 properties 로 관리 해보면 어떨까요?
혹은 default message 와 다른 필드를 추가하여 , target (id=id), reason, 들을 표현하면 더 자세히 표현될것 같습니다.

2021-10-24 01:56 UTC, Jo-GyuHyeon commented on springBoard/src/main/java/com/programmers/springboard/model/Post.java
> +        this.user = user;
update 로직을 수행한다면 this.updatedAt 필드도 설정해주면 좋을 것 같아요 ( 파라미터 x)

2021-10-24 01:56 UTC, Jo-GyuHyeon commented on springBoard/src/main/java/com/programmers/springboard/model/BaseEntity.java
> +    private LocalDateTime createdAt;
`createdBy`와 `createdAt` 은 타입은 다르지만 같은 값일 것 같습니다.
createdBy = createdAt 으로 해줘도 되지 않을까 싶습니다.

2021-10-24 01:56 UTC, Jo-GyuHyeon commented on springBoard/src/main/java/com/programmers/springboard/model/BaseEntity.java
> +    private LocalDateTime createdAt;
createAt 도 기본 값으로 지정해둬도 괜찮지 않을까요?

2021-10-24 01:56 UTC, Jo-GyuHyeon commented on springBoard/src/main/java/com/programmers/springboard/service/PostService.java
> +                .orElseThrow(() -> new PostNotFoundException(POSTS_NOT_FOUND));
`find` 가 없다면 무조건 예외 처리를 해야 될까? 라고 생각해보시면 좋을 것 같아요
지금의 경우에 find 는 예외처리가 발생하는 것이 더 적합하다고 생각하는데, findOne 메서드는 범용적으로 사용할 수 있다고도 생각합니다. 답이 정해져 있기보다는 고민? 생각을 해보면 좋겠다 싶어서 코멘트 달았습니다.

2021-10-24 01:56 UTC, Jo-GyuHyeon commented on springBoard/src/main/java/com/programmers/springboard/service/PostService.java
> +        Post post = postRepository.findById(id).orElseThrow(() -> new PostNotFoundException(POSTS_NOT_FOUND));
`getOne()` 을 만들어 두시고 안쓰신 이유가 있나요?

2021-10-24 01:56 UTC, Jo-GyuHyeon commented on springBoard/src/main/java/com/programmers/springboard/service/PostService.java
> +        post.update(dto.getTitle(), dto.getContent(), postConverter.convertUser(dto.getUserDto()));
만약 옵셔널을 사용해보신다면 체이닝으로만 로직을 작성해볼수도 있을 것 같습니다.
(꼭 그렇게 해야된다는것이 아닙니다.)

2021-10-24 01:56 UTC, Jo-GyuHyeon commented on springBoard/src/test/java/com/programmers/springboard/controller/PostControllerTest.java
> +class PostControllerTest {
Controller 테스트는 `@WebMvcTest` 에노테이션을 사용해보는 것은 어떨까요?

2021-10-24 01:56 UTC, Jo-GyuHyeon commented on springBoard/src/test/java/com/programmers/springboard/controller/PostControllerTest.java
> +                        .contentType(MediaType.APPLICATION_JSON))
개인적으로 인덴트를 맞추기 위해 `perform` 인자를 new line 으로 하는 것을 선호하는데, 그렇게 되면 `).` 형식으로, 체이닝이 이어지는 느낌을 받습니다.

2021-10-24 01:56 UTC, Jo-GyuHyeon commented on springBoard/src/test/java/com/programmers/springboard/service/PostServiceTest.java
> +        postService.update(postDto, 1L);
id를 변수로 빼는 것이 더 좋아 보입니다. ( 실수를 유발할수 있다고 생각합니다.)

2022-03-16 09:23 UTC, closed without merging