[2기-P] 박혜빈 JPA 게시판 구현 코드 리뷰 부탁드립니다 😊
prgrms-be-devcourse/SpringBoot-Board pull request #72
Opened 2022-05-16 19:42 UTC by HYEBPARK

### 🛠  작업 단위

- [x] h2 database 설정
- [x] 회원(User) entity 
    - id (PK) (auto increment)
    - name
    - age
    - hobby
    - **created_at**
    - **created_by**
- [x] 게시글(Post) entity
    - id (PK) (auto increment)
    - title
    - content
    - **created_at**
    - **created_by**
- [x] 회원과 게시글에 대한 연관관계 설정
    - 회원과 게시글은 1:N 관계
- [x] 게시글 Repository 구현 (PostRepository)
- API (Post)
    - [x] 페이징 조회 (GET "/api/v1/posts")
    - [x] 단건 조회 (GET "/api/v1/post/{id}")
    - [x] 게시글 작성 (POST "/api/v1/post")
    - [x] 게시글 수정 (POST "/api/v1/posts/{id}")
 - API(User, 요구사항 x ) 
    - [x] user 등록(POST "/api/v1/user") 
    - [x] user  페이징 조회 (GET "/api/v1/users")
- [ ] service test 코드 작성
- [ ] controller test 코드 작성 
- [ ] REST-DOCS를 이용해서 문서화

### ✅  PR 포인트
- GlobalExceptionHandler 에서 client에 어떤 정보를 넘겨줘야 할 지, 어떤 log를 남겨야 할 지 고민이 되었습니다. 현재는 아래의 사진과 같은 결과가 나오도록 코드를 작성했습니다. 
![image](https://user-images.githubusercontent.com/35947674/168656941-5ab621fa-fa7d-47a4-973c-f64b9cbb9398.png)
![image](https://user-images.githubusercontent.com/35947674/168656988-511a81bf-3888-414c-85eb-00a889a6f072.png)

- 테스트 코드는 수정 후 다음 pr 때 리뷰 받겠습니다 ! 😊  

### 🐣  요구사항
- [JPA 게시판 과제](https://ancient-citron-06b.notion.site/SpringBoot-Part4-7-632dd10678164daca96a5ea185a02b60)

2022-05-16 19:44 UTC, HYEBPARK commented on src/main/java/org/programmers/kdtboard/exception/GlobalExceptionHandler.java
> +		log.error("handleBindException -> {} \n {}", stringBuilder, e.getMessage());
bind 에러에 대해서 log 가 원래 찍히긴 하는데 더 편하게 보려고 stringBuilder 를 만들었습니다.
굳이 필요 없는 부분일까요?

2022-05-17 11:06 UTC, midasWorld reviewed
고민 하시면서 신경 많이 쓴 코드라는게 느껴지네요. 고생하셨습니다!! 👍

코드 리뷰 잘하고 싶은데.. 그냥 의문점들만 막 적었습니다.. 😓 

그리고 GlobalExceptionHandler에서 추가로 상정한 예외말고 그 외의 Exception도 처리 하는 메서드도 있으면 좋지 않을까? 싶네요.
```java
// 상정하지 못한 예외도 여기서 처리 될 수 있도록.
@ExceptionHandler({Exception.class, RuntimeException.class})
public final ResponseEntity<ApiResult<?>> handleAllException(Exception e) {
	log.error("Unexpected exception occurred: {}", e.getMessage(), e);
	//... 처리
}
```

2022-05-17 11:06 UTC, midasWorld commented on src/main/java/org/programmers/kdtboard/exception/GlobalExceptionHandler.java
> +	@ExceptionHandler
@ExceptionHandler에 값을 설정하지 않는 이유가 있을까요? 🤔
이렇게는 사용을 안해봐서 기능적으로는 잘 모르겠지만...
저는 개인적으로 코드 가독성면에서도 명시를 하는게 낫지 않을까? 라는 의견입니다.

2022-05-17 11:06 UTC, midasWorld commented on src/main/java/org/programmers/kdtboard/controller/response/ErrorResponse.java
> +}
Getter 메서드가 없네요?? 이거 Json 형태로 잘 반환 되나요? 😳

2022-05-17 11:06 UTC, midasWorld commented on src/main/java/org/programmers/kdtboard/domain/post/Post.java
> +	}
생성자 메서드 그대로 사용하는 것 같은데, 이렇게 사용하면 어떤 이점이 있나요?? 👀

2022-05-17 11:06 UTC, midasWorld commented on src/main/java/org/programmers/kdtboard/domain/user/User.java
> +		this.hobby = hobby;
매개변수가 몇개 안되서 상관없을 거 같기도 한데, 아래와 같이 쓸 수도 있슴다!
```java
this(null, name, age, hobby, null, null);
```
이렇게 사용하면 생성자가 여러개 생겨도 나름 코드량을 줄일 수 있어서 좋은것 같슴니다.

2022-05-17 11:06 UTC, midasWorld commented on src/main/java/org/programmers/kdtboard/controller/PostController.java
> +public class PostController {
클래스 네이밍을 PostRestController로 하는 건 어떨 까요? 🤔
한 0.1%의 확률로 View를 위한 Controller가 생길 수도 있지 않을까요?

2022-05-17 11:06 UTC, midasWorld commented on src/main/java/org/programmers/kdtboard/controller/response/ApiResponse.java
> +	private final HttpStatus httpStatus = HttpStatus.OK;
httpStatus는 사용 되지 않는 아이인가요?? 👀

2022-05-17 11:06 UTC, midasWorld commented on src/main/java/org/programmers/kdtboard/converter/Converter.java
> +	public PostResponse postConverter(Post post) {
메서드 네이밍이 명사처럼 보이는데, convertPost 같은 동사로 사용하는 건 어떨까요?

2022-05-17 11:06 UTC, midasWorld commented on src/main/java/org/programmers/kdtboard/domain/BaseEntity.java
> +	}
`@CreatedDate` 애노테이션을 사용하면 자동으로 들어가는 걸로 알고 있는데, 이게 필요한가요?? 🤔

2022-05-17 11:06 UTC, midasWorld commented on src/main/java/org/programmers/kdtboard/exception/EntityNotFoundException.java
> +public class EntityNotFoundException extends javax.persistence.EntityNotFoundException {
javax.persistence.EntityNotFoundException 얘를 상속하는 이유가 있을까요? 👀
그리고 상속을 했는데, 같은 클래스명을 써도 되나? 라는 의문이 드네요. 🤔

2022-05-17 11:06 UTC, midasWorld commented on src/main/java/org/programmers/kdtboard/controller/response/ErrorCodeMessage.java
> +	INVALID_REQUEST_VALUE(HttpStatus.BAD_REQUEST, "잘못된 입력입니다.");
오우.. 오류 메시지를 이렇게 관리 할 수도 있군요. 😳
배워 갑니다.. (줍줍.. ) 👍

2022-05-17 11:06 UTC, midasWorld commented on src/main/java/org/programmers/kdtboard/service/UserService.java
> +					ErrorCodeMessage.USER_ID_NOT_FOUND));
ErrorCodeMessage - enum 클래스에서 메시지를 포함하고 있는데, 
메시지와 ErrorCodeMessage가 중복으로 사용 되는 것 처럼 느껴지는 건 기분 탓일까요? 🤔

ErrorCodeMessage에서 매개변수를 받아서 메시지를 완성하는건 어떨까요?
다른 분들 의견도 들어보고 싶군요... 👀

2022-05-17 11:06 UTC, midasWorld commented on src/main/java/org/programmers/kdtboard/exception/GlobalExceptionHandler.java
> +		log.error("handleBindException -> {} \n {}", stringBuilder, e.getMessage());
본래 내용이 어떻게 나오는지 몰라서.... 허헣.. 그.. 그래도 저는 불필요하지 않을까? 라는 쪽으로 기우는것 같네요.
다른 분들 의견도 들어보고 싶군요. 👀

-------------------------------------
그리고 이건 다른 이야기 인데, BAD REQUEST 상태코드 인데, 로깅 레벨이 error가 적절할까요? 🤔
사용자가 잘못 입력할 경우가 많을 것 같은데, 그럼 error 레벨 로그로 가득차지 않을까? 라는 걱정이 드네요.

그리고 stack trace 까지 남길 수 있도록 아래와 같이 사용하는게 좋지 않을까요? 
```java
log.error("handleBindException -> {} \n {}", stringBuilder, e.getMessage(), e);
```

2022-05-17 11:08 UTC, HYEBPARK commented on src/main/java/org/programmers/kdtboard/exception/GlobalExceptionHandler.java
> +	@ExceptionHandler
설정하지 않은 이유 없습니다 ! 까먹었습니다 !! 
추가해야겠어요 감사합니다 ㅎㅎ

2022-05-17 11:12 UTC, HYEBPARK commented on src/main/java/org/programmers/kdtboard/controller/response/ErrorResponse.java
> +}
엇 현재 제 인텔리제이에는 getter가 있는데 제가 이 부분 커밋을 안 했나봅니다 😅
getter가 있어야 잘 반환됩니다 !!

2022-05-17 11:14 UTC, HYEBPARK commented on src/main/java/org/programmers/kdtboard/domain/user/User.java
> +		this.hobby = hobby;
배워갑니다 !! 👍

2022-05-17 11:15 UTC, HYEBPARK commented on src/main/java/org/programmers/kdtboard/controller/PostController.java
> +public class PostController {
0.1% 확률도 확률이니 좋은 것 같슴다 !
아니면 view가 생긴다면 그때 변경하는걸로 .. ㅎㅎ

2022-05-17 11:18 UTC, HYEBPARK commented on src/main/java/org/programmers/kdtboard/controller/response/ApiResponse.java
> +	private final HttpStatus httpStatus = HttpStatus.OK;
아뇨 ㅠㅠ 사용되는 아이입니다 
이부분도 수정 해야겠어요 😓

2022-05-17 11:19 UTC, HYEBPARK commented on src/main/java/org/programmers/kdtboard/domain/BaseEntity.java
> +	}
나중에 테스트 코드 작성할 때 사용하려고 남겨 뒀던 것 같슴다 !!

2022-05-17 11:21 UTC, HYEBPARK commented on src/main/java/org/programmers/kdtboard/exception/EntityNotFoundException.java
> +public class EntityNotFoundException extends javax.persistence.EntityNotFoundException {
원래 RuntimeException을 상속했었는데 .. 음 정확히 터지는 예외가 있으니 그 예외를 상속하는게 맞지 않을까 생각을 했고,
네이밍은 EntityNotFoundExceptiond이 너무 찰떡이라 ... 더 좋은 네이밍이 생각나지 않았어요
저도 찜찜하긴 합니다 😅 그냥 RuntimeException을 상속받는게 더 맞는 방법일까요?!

2022-05-17 11:27 UTC, HYEBPARK commented on src/main/java/org/programmers/kdtboard/service/UserService.java
> +					ErrorCodeMessage.USER_ID_NOT_FOUND));
음.. 앞에 format의 메시지는 log에 메시지를 주기 위해서 넣었고, 
ErrorCodeMessage는 client에 메시지를 넘겨주기 위해서 넣었어요 !
ErrorCodeMessage에서 두 가지가 다 가능한 방법이 있는지 한번 생각해보겠습니다 ㅎㅎ

2022-05-17 11:44 UTC, midasWorld commented on src/main/java/org/programmers/kdtboard/exception/EntityNotFoundException.java
> +public class EntityNotFoundException extends javax.persistence.EntityNotFoundException {
일단 Service단에서 사용 되는 커스텀 오류 이니까, EntityNotFoundExceptiond 이 녀석과는 다른 결이지 않을까? 라는 생각이 들구요.
그래서 저는 RuntimeException 이 더 맞지 않을까? 라는 의견인데, 이거는 다른 분들 의견도 들어보는게 좋을 것 같네요. ㅎㅎ..

그래도 일단 클래스 이름이라도 CustomizedEntityNotFoundException 라고 상속된 클래스명과 별개로 사용하는 것이 맞지 않을까 싶네요.

2022-05-17 11:49 UTC, midasWorld commented on src/main/java/org/programmers/kdtboard/service/UserService.java
> +					ErrorCodeMessage.USER_ID_NOT_FOUND));
저는 개인적으로 로그 메시지와 클라이언트에게 보여줄 메시지가 같은 내용이라는 생각이 드네요. 
흠.. 클라이언트에게 보여줄 메시지도 '{id} 얘는 없는 애야' 라고 보여주는게 이상 할까요...?🤔

2022-05-17 11:53 UTC, HYEBPARK commented on src/main/java/org/programmers/kdtboard/exception/EntityNotFoundException.java
> +public class EntityNotFoundException extends javax.persistence.EntityNotFoundException {
오호 ! customized를 붙이는 것도 좋은 생각 인 것 같습니다 !!

2022-05-18 03:01 UTC, HYEBPARK commented on src/main/java/org/programmers/kdtboard/exception/EntityNotFoundException.java
> +public class EntityNotFoundException extends javax.persistence.EntityNotFoundException {
동운님 제가 어제 남긴 코멘트가 제가 읽어도 이상하네요 정신이 좀 없어서 😓
jpa 관련 excpetion이 뭐가 있는지 찾아보다가 해당 예외를 알게 되었고, 파라미터를 다르게 넘겨 주고 싶어서 
EntityNotFoundException 을 커스텀 한 것 같습니다. 근데 지금 제가 생각해봐도 그냥 처음처럼 RuntimeException을 상속받는게 맞을 것 같네요. 처음 보는 예외라 또 써먹어 보고 싶었나봅니다.... ㅎㅎ 이 부분 수정하도록 하겠습니다😊

2022-05-18 06:07 UTC, HYEBPARK commented on src/main/java/org/programmers/kdtboard/domain/post/Post.java
> +	}
책에서 본 내용을 적용해보고 싶었습니다 하하

2022-05-18 06:11 UTC, HYEBPARK commented on src/main/java/org/programmers/kdtboard/exception/GlobalExceptionHandler.java
> +		log.error("handleBindException -> {} \n {}", stringBuilder, e.getMessage());
예외가 터지면 무지성 error 로 찍었는데 로깅 레벨에 대해서도 다시 생각해봐야겠습니다 !
stackTrace도 남기는게 좋은 것 같네요 ㅎㅎ

2022-05-18 09:53 UTC, HyoungUkJJang approved these changes
수고하셨습니다 혜빈님 ! 동운님께서 상세하게 잘 남겨주셔서 제가 도움이 될 부분이 많지 않겠지만 그래도 약간의 생각을 한번 남겨 봤습니다 🙂

코드 잘봤습니다 👍🏻👍🏻👍🏻

2022-05-18 09:53 UTC, HyoungUkJJang commented on src/main/java/org/programmers/kdtboard/domain/user/User.java
> +	public static User create(Long id, String name, int age, String hobby, LocalDateTime createdAt, String createdBy) {
BaseEntity의 CreatedDate덕분에 자동으로 들어가는 걸로 알고 있는데 여기서 따로 받으시는 이유가 있으신가요 !?

2022-05-18 09:53 UTC, HyoungUkJJang commented on src/test/java/org/programmers/kdtboard/domain/post/PostRepositoryTest.java
> +		var foundPost = postRepository.findById(post.getId());
BeforeEach를 사용하는건 어떻게 생각하시나요 !?

2022-05-18 09:53 UTC, HyoungUkJJang commented on src/main/java/org/programmers/kdtboard/exception/EntityNotFoundException.java
> +public class EntityNotFoundException extends javax.persistence.EntityNotFoundException {
음 저는 EntityNotFoundException도 좋은 것 같지만 어떤 엔티티가 존재하지 않는지 명확한 예외를 던져주는게 좋다고 생각이 드는 것 같아요! 저는 그래서 PostNotFoundException 이런 이름으로 사용을 해왔었는데 하나의 커스텀 Exception으로 만들어서 관리하시는 특별한 이유가 있으실까요 !?

2022-05-18 10:52 UTC, Onigiriiiiiiii requested changes
다른분들이 많이 잡아주셧군요! 나중에 있을 이슈에 대비하여 코멘트 남겨드렸습니다!
수고하셨습니 🥕  !

2022-05-18 10:52 UTC, Onigiriiiiiiii commented on src/main/java/org/programmers/kdtboard/SpringbootBoardJpaApplication.java
> +@EnableJpaAuditing
- @WebMvcTest같은 테스트 전용 어노테이션은 JPA 관련 bean 객체를 로딩하지 않아 @EnableJpaAuditing과 설정이 맞지 않는 문제가 발생할 수 있습니다.

2022-05-18 10:52 UTC, Onigiriiiiiiii commented on src/main/java/org/programmers/kdtboard/controller/PostController.java
> +	public ApiResponse<List<PostResponse>> findAll(Pageable pageable) {
페이징을 하는데 페이지에 관한 정보가 없어보입니다.

2022-05-18 10:52 UTC, Onigiriiiiiiii commented on src/main/java/org/programmers/kdtboard/controller/response/ApiResponse.java
> +public class ApiResponse<T> {
- 모든 반환 값을 해당 객체로 wrapping 한 이유가 어떻게 되시나요 ?

2022-05-18 10:52 UTC, Onigiriiiiiiii commented on src/main/java/org/programmers/kdtboard/domain/user/User.java
> +	@Column(nullable = false, length = 10)
- 도메인 제약 조건을 설정해 줬는데 생성자를 만들 때 검증하는 로직이 없어보여요 ! (못찾은 걸수도 ... 하하하) 만약 없는게 맞다면 따로 제약조건에 따른 초기 값을 검증도 하는 것이 좋아보여 🐉  그리고 DataIntegrityViolationException 도 미리 대비해서 글로벌 예외로 걸어놓으면 좋을 것 같습니 🥕

2022-05-18 10:52 UTC, Onigiriiiiiiii commented on src/main/java/org/programmers/kdtboard/dto/PostDto.java
> +public class PostDto {
dto inner strategy good ‼️

2022-05-18 10:52 UTC, Onigiriiiiiiii commented on src/main/java/org/programmers/kdtboard/dto/UserDto.java
> +	@Valid
여기에 valid가 위치한 이유가 어떻게 되시나 🐉  ?

2022-05-18 10:52 UTC, Onigiriiiiiiii commented on src/main/java/org/programmers/kdtboard/dto/UserDto.java
> +		@NotBlank @Size(max = 10)
validation (MethodArgumentNotValidException) 오류가 글로벌에도 없는데 어떻게 처리하시는 건가 🐉  ?

2022-05-18 10:52 UTC, Onigiriiiiiiii commented on src/main/java/org/programmers/kdtboard/service/PostService.java
> +@Transactional
해당 애노테이션을 기반으로 조회만 하는 서비스는 비효율적인 동작과정이 내포되어있습니다.
읽기만 하는 서비스는 해당 플러시를 호출할 필요도 없으며 스냅샷을 유지할 필요가 없습니당. 
그 상세한 부분는 꼭 한번 찾아보시면 좋겠습니 🥕  !
[refer](https://willseungh0.tistory.com/75)

2022-05-18 10:52 UTC, Onigiriiiiiiii commented on src/main/resources/application.yml
> +  mvc:
HiddenHttpMethodFilter는 <form> 태그에서 '_method'의 추가정보를 사용해서 GET/POST 방식만을 지원하는 브라우저에서 REST방식을 사용할 수 있도록 해주는 기능이군 🐉  ! 

🍯  TIP 감사합니 🥕  !

2022-05-18 10:52 UTC, Onigiriiiiiiii commented on src/test/java/org/programmers/kdtboard/domain/post/PostRepositoryTest.java
> +	void save() {
insert 쿼리가 날라가는지 궁금합니 🥕

2022-05-18 10:57 UTC, HYEBPARK commented on src/main/java/org/programmers/kdtboard/domain/user/User.java
> +	public static User create(Long id, String name, int age, String hobby, LocalDateTime createdAt, String createdBy) {
저는 post를 새로 만들 때 미리 생성되어있는 user의 id를 받아 해당 user를 찾아 setUser를 해줍니다
이때 해당 user를 userService에서 받으면 userResponseDto를 받기 때문에 
converter를 이용하여 User로 변경하는 과정이 필요합니다 ! 이 과정 때문에 만들었습니당 !

2022-05-18 11:04 UTC, HYEBPARK commented on src/main/java/org/programmers/kdtboard/service/PostService.java
> +@Transactional
class에 선언한거랑 메서드에 선언한거랑 뭐가 다른건지 잘 몰랐는데, 
제가 궁금했던 부분인데 딱 집어주셨어요 !! 감사합니다 병연님 👍😊

2022-05-18 11:05 UTC, HYEBPARK commented on src/main/java/org/programmers/kdtboard/SpringbootBoardJpaApplication.java
> +@EnableJpaAuditing
제가 이 부분에 대해서 잘 모르는데 더 알아봐야겠슴당 !!

2022-05-18 11:10 UTC, HYEBPARK commented on src/main/java/org/programmers/kdtboard/controller/response/ApiResponse.java
> +public class ApiResponse<T> {
홍구님 강의를 보고 알게된건데 ApiResponse를 이용해서 ok 메서드를 호출하는게
메서드가 성공했다는 의미가 더 잘 보이더라구요 ㅎ-ㅎ 상태 코드도 같이 넘겨 줄 수 있는 점이 좋아 보였습니다 ! 
controller에서 어떤 걸 return해줘야 할지 고민이 많았어서 강의에서 새로 알게 된 걸 사용해보고 싶은 이유가 더 큰 것 같아요 !

2022-05-18 11:12 UTC, HYEBPARK commented on src/main/java/org/programmers/kdtboard/domain/user/User.java
> +	@Column(nullable = false, length = 10)
저는 controller에서 valid를 사용하여 검증을 해주었기 때문에 생성자에서 검증을 해주지 않아도 된다고 생각을 했는데
따로 필요한 부분일까요?!

2022-05-18 11:22 UTC, HYEBPARK commented on src/main/java/org/programmers/kdtboard/dto/UserDto.java
> +		@NotBlank @Size(max = 10)
저는 BindException을 처리하고 있어서 MethodArgumentNotValidException는 BindException을 상속받고 있는
예외라 처리가능합니당 !

2022-05-18 11:26 UTC, HYEBPARK commented on src/main/java/org/programmers/kdtboard/exception/EntityNotFoundException.java
> +public class EntityNotFoundException extends javax.persistence.EntityNotFoundException {
저도 처음에는 post랑 user를 나눠서 exception을 가져갔었는데
만약 entity가 늘어날 때마다 exception이 늘어날텐데 이게 맞나? 라는 생각이 들었고 , 중복되는 것 같아서 이걸 합쳤습니당 !

2022-05-18 11:30 UTC, HYEBPARK commented on src/main/java/org/programmers/kdtboard/controller/PostController.java
> +	public ApiResponse<List<PostResponse>> findAll(Pageable pageable) {
page에 관한 정보가 size와 page라면 그건 url 호출할 때 넘겨주는 것 아닌가욤?
아니면 다른 정보가 더 있는건가욤!? 🤔

2022-05-18 11:33 UTC, HYEBPARK commented on src/test/java/org/programmers/kdtboard/domain/post/PostRepositoryTest.java
> +	void save() {
날아갑니당 !

2022-05-18 12:52 UTC, whyWhale commented on src/main/java/org/programmers/kdtboard/controller/PostController.java
> +	public ApiResponse<List<PostResponse>> findAll(Pageable pageable) {
프론트에서 몇페이지까지 번호를 만들어야 하는지 조립할수 없어보입니당근!

2022-05-18 16:43 UTC, pjh612 commented on src/test/java/org/programmers/kdtboard/domain/post/PostRepositoryTest.java
> +		assertThat(foundPost).isNotEmpty();
정말 사소한거지만 isNotEmpty()와 같이 비어있지 "않다" 라는 not이 들어가는 조건문 보다는
isPresent()같이 즉각적으로 인지할 수 있는 조건문이 더 좋다고 생각이 들어서 저는 isPresent()를 선호하는 편이긴 합니다.

더 극단적인 예로  if(!isNotEmpty()) 보다 if(isEmpty())가 더 낫다는 말이었슴다!

2022-05-18 17:22 UTC, pjh612 reviewed
고생 하셨습니다~ 노오오오오오오력을 많이 하신 것 같군요!

2022-05-18 17:22 UTC, pjh612 commented on src/test/java/org/programmers/kdtboard/domain/post/PostRepositoryTest.java
> +		assertThat(foundPost).isNotEmpty();
정말 사소한거지만 isNotEmpty()와 같이 비어있지 "않다" 라는 not이 들어가는 조건문 보다는
isPresent()같이 즉각적으로 인지할 수 있는 조건문이 더 좋다고 생각이 들어서 저는 isPresent()를 선호하는 편이긴 합니다.

더 극단적인 예로 if(!isNotEmpty()) 보다 if(isEmpty())가 더 낫다는 말이었슴다!

2022-05-18 17:22 UTC, pjh612 commented on src/test/java/org/programmers/kdtboard/domain/post/PostRepositoryTest.java
> +		log.info("found Post content : {}", content);
테스트는 로그같은 것에 의존되지 않아야 합니다. 테스터가 로그를 직접 읽어서 이 테스트가 성공했는지 실패했는지의 여부를 확인해야 된다면 잘못 짠 테스트라고 볼 수 있다고 생각합니다.

그냥 테스트 과정에서 눈으로 직접 보고 싶은 내용이 있다거나, n + 1 문제와 같은 쿼리가 나가는 것을 눈으로 확인해야 되는 경우는 어느 정도 허용 된다고 생각함다

근데 그냥 테스트 하면서 확인 차 사용하신 것 같긴하네요 ㅎ

2022-05-18 17:22 UTC, pjh612 commented on src/test/java/org/programmers/kdtboard/domain/post/PostRepositoryTest.java
> +		var foundPost = postRepository.findById(post.getId());
어떤 것은 findById를 then절에 넣고 어떤 것은 findById를 when절에 넣고 있으신데 특별한 이유가 있으신가요?

2022-05-18 17:22 UTC, pjh612 commented on src/main/java/org/programmers/kdtboard/domain/post/Post.java
> +	public void update(String title, String content) {
또 다른 방법으로는
```java
public void update(Post post) {
		this.title = post.title;
                this.content = post.content;
	}
```
로 할 수 있을 것 같습니다. 변경되어야할 매개변수가 많아진다면 제가 말씀드린 방법을 사용할 수 있을 것 같아요!

2022-05-18 17:22 UTC, pjh612 commented on src/main/java/org/programmers/kdtboard/converter/Converter.java
> +public class Converter {
어떤 컨버터인지에 대한 정보가 부족한 네이밍인듯합니다. 이러한 네이밍은 오히려 최상위 추상클래스, 인터페이스에 어울리는 네이밍이 아닐까 싶은 생각이 들어요!

2022-05-18 17:22 UTC, pjh612 commented on src/main/java/org/programmers/kdtboard/converter/Converter.java
> +	public static PostResponse postConverter(Post post) {
매개 변수가 6개로 좀 많아 보이네요 빌더 패턴을 적용하는게 유리해 보입니다!

2022-05-18 17:22 UTC, pjh612 commented on src/main/java/org/programmers/kdtboard/controller/PostController.java
> +	@PostMapping("/api/v1/post")
/api/v1 은 모든 엔드 포인트에 대해 공통된 경로인듯 합니다. 그렇다면 클래스레벨에 RequestMapping을 걸고
메소드 단위에서는 그 하위의 url정보만 담는 것이 어떨까요?
접두사 느낌이라고 생각하시면 될 것 같습니다.

2022-05-18 17:22 UTC, pjh612 commented on src/main/java/org/programmers/kdtboard/controller/PostController.java
> +	public ApiResponse<List<PostResponse>> findAll(Pageable pageable) {
페이저블로 페이징을 하고자 했지만 리스트로 받고 있슴다 페이징이 어떤 용도로 쓰이는지 페이징에 대해서 조금 더 알아보시면 좋을 것 같습니다!

2022-05-18 17:22 UTC, pjh612 commented on src/main/java/org/programmers/kdtboard/controller/PostController.java
> +	public ApiResponse<PostResponse> update(@PathVariable Long id, @RequestBody PostUpdateRequest postUpdateRequest) {
PostUpdateRequest를 사용하시는데 PostUpdateRequest가 안보입니다. ㅜ 제가 못찾는 건가요?....

그게 아니라면 꼭 포함해서 커밋하시는게 좋을 것 같습니다..!

2022-05-18 17:29 UTC, Onigiriiiiiiii commented on src/main/java/org/programmers/kdtboard/dto/UserDto.java
> +		@NotBlank @Size(max = 10)
에외를 구체적으로 분리해서 원인을 파악하는데 시간적인 비용을 줄일 수 있을 것 같은데 어떻게 생각하시나요?

2022-05-18 17:29 UTC, Onigiriiiiiiii commented on src/test/java/org/programmers/kdtboard/domain/post/PostRepositoryTest.java
> +	void save() {
IDENTITY stratgy king jung.

2022-05-18 23:47 UTC, HYEBPARK commented on src/test/java/org/programmers/kdtboard/domain/post/PostRepositoryTest.java
> +		var foundPost = postRepository.findById(post.getId());
아뇹 없습니다 ! 이 부분도 일관성을 가져야겠군요 !!

2022-05-19 00:41 UTC, HYEBPARK commented on src/main/java/org/programmers/kdtboard/controller/PostController.java
> +	public ApiResponse<PostResponse> update(@PathVariable Long id, @RequestBody PostUpdateRequest postUpdateRequest) {
dto 이너 클래스로 만들어져있습니당 !

2022-05-19 00:42 UTC, HYEBPARK commented on src/main/java/org/programmers/kdtboard/domain/post/Post.java
> +	public void update(String title, String content) {
오 매개변수를 줄일 수 있어 좋은 것 같습니당 👍

2022-05-19 03:48 UTC, pjh612 commented on src/main/java/org/programmers/kdtboard/controller/PostController.java
> +	public ApiResponse<PostResponse> update(@PathVariable Long id, @RequestBody PostUpdateRequest postUpdateRequest) {
아 ㅋㅋ 정신없었나봅니다 ㅎ 죄송함도

2022-05-19 09:35 UTC, closed without merging