[2기-P] 김병연 JPA 게시판 구현
prgrms-be-devcourse/SpringBoot-Board pull request #73
Opened 2022-05-17 01:28 UTC by whyWhale

## 📌작업 단위
- [ ] : 게시판 추가
- [ ] : 게시판 추가 기능 테스트 작성 (jpa, service 단위 테스트) 
- [ ] : 게시판 읽기
- [ ] : 게시판 읽기 기능 테스트 작성 (jpa, service 단위 테스트)
- [ ] : 게시판 삭제 (softDelete)
- [ ] : 게시판 삭제 기능 테스트 작성 (jpa, service 단위 테스트)
- [ ] : 게시판 단건 조회
- [ ] : 게시판 단건 기능 테스트 작성 (jpa, service 단위 테스트) [mock test issue]
- [ ] : 게시판 다건 조회 + paging 
- [ ] : 게시판 다선 기능 테스트 작성 (jpa)

## ✅ PR 포인트 & 궁금한 점 
- Mockito BDD를 사용하고 있는데 테스트 코드 중에 잦은 이슈를 맞고 있습니다.. 중간중간에 간혹 테스트 코드에 맞추기 위해 로직을 조금 변경하는데 이게 맞는지 의문이 들고 있습니다.
- mock 테스트 관련한 이슈들을 정리했는데 원인이 무엇인지 파악이 안되고 있습니다!
- 관련내용은 여기 있습니당 [mockito_issue](https://absorbed-cheek-029.notion.site/JPA-mission-issue-13bcbf1c50c4455ea80ad66670637929)

## 👩‍💻 요구 사항
[요구사항](https://absorbed-cheek-029.notion.site/JPA-mission-issue-13bcbf1c50c4455ea80ad66670637929)

2022-05-18 00:17 UTC, midasWorld reviewed
고생하셨습니다!! 👍
혜빈님 바로 위에 있어서 들렀습니다.. ㅎㅎ

테스트 코드를 정말 꼼꼼하게 작성하셔서 오..! 를 연발하며 보았습니다. 👍
그 외에도 여러가지 덕분에 많이 배워갑니다. 👍

2022-05-18 00:17 UTC, midasWorld commented on board/src/main/java/com/programmers/board/exception/GlobalHandling.java
> +	}
같은 상태 값에 같은 메시지를 반환하는 거라면 하나의 메서드로 묶는 건 어떨까요? 🤔
로깅만 다르게 주는 거라면 Exception으로 받아서, if 문에 `instanceof`를 활용하면 좀더 관리가 용이하지 않을까? 라는 생각을 해보았습니다.. ㅎㅎ

---
추가로 stack trace도 넘겨주면 어떨까요?
```java
log.warn("잘못된 인자를 넘겼습니다. {} ", e.getMessage(), e);
```

2022-05-18 00:17 UTC, midasWorld commented on board/src/main/java/com/programmers/board/domain/Post.java
> +		}
update 할때 제목과 내용에 저런 제약사항이 있다면, 생성자에도 추가하는건 어떨까요? 🤔

2022-05-18 00:17 UTC, midasWorld commented on board/src/main/java/com/programmers/board/domain/Post.java
> +		}
update 할때 제목과 내용에 저런 제약사항이 있다면, 생성자에도 추가하는건 어떨까요? 🤔

2022-05-18 00:17 UTC, midasWorld commented on board/src/test/java/com/programmers/board/repository/PostRepositoryTest.java
> +	@Order(10)
Order를 10 단위로 주신 게 따로 의미가 있나요?? 👀

2022-05-18 00:17 UTC, midasWorld commented on board/src/test/java/com/programmers/board/repository/PostRepositoryTest.java
> +	@Order(10)
Order를 10 단위로 주신 게 따로 의미가 있나요?? 👀

2022-05-18 00:17 UTC, midasWorld commented on board/src/main/java/com/programmers/board/domain/Post.java
> +	}
오우.. soft delete.. 배워 갑니다. 👍

2022-05-18 00:17 UTC, midasWorld commented on board/src/main/java/com/programmers/board/domain/Post.java
> +	}
오우.. soft delete.. 배워 갑니다. 👍

2022-05-18 00:17 UTC, midasWorld commented on board/src/main/java/com/programmers/board/domain/Post.java
> +	@ToString.Exclude
오.. 이런게 있었군요? 😳.. 배워 갑니다.. 👍

2022-05-18 00:17 UTC, midasWorld commented on board/src/main/java/com/programmers/board/domain/Post.java
> +	@ToString.Exclude
오.. 이런게 있었군요? 😳.. 배워 갑니다.. 👍

2022-05-31 16:12 UTC, Jo-GyuHyeon requested changes

2022-05-31 16:12 UTC, Jo-GyuHyeon commented on board/src/main/java/com/programmers/board/Service/PostService.java
> +		return converter.toResponse(foundPost);
Optional 의 특징일 더 살려서 코드를 작성 하실 수 있을것 같습니다.
stream 처럼 체이닝 방식을 사용해보세요.

2022-05-31 16:12 UTC, Jo-GyuHyeon commented on board/src/main/java/com/programmers/board/Service/PostService.java
> +	}
위와 동일한 리뷰 내용입니다.

2022-05-31 16:12 UTC, Jo-GyuHyeon commented on board/src/main/java/com/programmers/board/controller/PostDto.java
> +	public record Save(
Java 14의 record 를 사용해보셨군요? 😄 
Java 17의 seald 와 같이 사용해보는 것을 추천 드립니다. 👍 

[관련 링크 첨부 보시면 좋을 것 같습니다.](https://sendilkumarn.com/blog/java-17/#:~:text=Record%20classes%20%26%20Sealed%20Interfaces%20Best%20Friends%20Forever)

2022-05-31 16:12 UTC, Jo-GyuHyeon commented on board/src/main/java/com/programmers/board/controller/PostRestController.java
> +@RequestMapping("/post")
restful 에서 리소스는 대부분 복수형을 기본으로 생각하시면 좋을 것 같습니다.

2022-05-31 16:12 UTC, Jo-GyuHyeon commented on board/src/main/java/com/programmers/board/controller/PostRestController.java
> +	@PostMapping("")
빈 mapping 인 경우 ("") 는 생략 가능 합니다. 😄

2022-05-31 16:12 UTC, Jo-GyuHyeon commented on board/src/main/java/com/programmers/board/controller/PostRestController.java
> +	public PostDto.Response create(@Valid PostDto.Save postDto) {
@RequestBody 로 받지 않는 이유는 따로 있을까요?

2022-05-31 16:12 UTC, Jo-GyuHyeon commented on board/src/main/java/com/programmers/board/controller/PostRestController.java
> +	public PostDto.Response update(@Valid PostDto.Update updateDto) {
post_id 애 대한 PathVariable 를 사용하지 않고 있습니다. 확인 부탁 드립니다.

2022-05-31 16:12 UTC, Jo-GyuHyeon commented on board/src/main/java/com/programmers/board/controller/PostRestController.java
> +	public PostDto.Response findOne(@PathVariable("post_id") Long postId) {
`post_id` 의 경우 java 컨벤션과 동일 하게 한다면 @PathVariable 에서 따로 매핑을 지어주지 않아도 됩니다.
개인적으로 resource 의 id 가 1가지라면 `id` 로만 표기해도 충분히 표현이 된다고 생각합니다.
id 구분이 필요한 경우에만 자세히 표기하는 편입니다. 😄

2022-12-08 03:01 UTC, merged