[2기-P 정윤오] JPA 게시판 구현
prgrms-be-devcourse/SpringBoot-Board pull request #96
Opened 2022-05-19 19:23 UTC by jungyoonoh

## 📌 과제 설명 
JPA 게시판 과제 구현입니다.

## 👩‍💻 요구 사항과 구현 내용 
### **SpringDataJPA 를 설정한다.**

- [x] SpringDataJpa를 설정한다.
- datasource : h2 

- [x] **엔티티를 구성한다**

- 회원(User)
    - id (PK) (auto increment)
    - name
    - age
    - hobby
    - **created_at**
    - **created_by**
- 게시글(Post)
    - id (PK) (auto increment)
    - title
    - content
    - **created_at**
    - **created_by**
- 회원과 게시글에 대한 연관관계를 설정한다.
    - 회원과 게시글은 1:N 관계이다.
- 게시글 Repository를 구현한다. (PostRepository)

- [x] **API를 구현한다.**

- 게시글 조회
    - 페이징 조회 (GET "/posts")
    - 단건 조회 (GET "/posts/{id}")
- 게시글 작성 (POST "/posts")
- 게시글 수정 (PATCH "/posts/{id}")

- [x] **REST-DOCS를 이용해서 문서화한다.**

## ✅ PR 포인트 & 궁금한 점 
- Controller가 primitive의 Wrapper class를 return 하려 하면 REST DOCS에서 아래와 같은 에러를 일으킵니다. 구글링 해보니 단일 Number Type의 Response를 지원하지 않는 것 같습니다. 일반적으로 API에서 primitive type의 Wrapper class를 Response로 사용하지 않는 편인지가 궁금합니다. 
아래는 에러 메시지입니다.
> AsciiDoc Error java.lang.Integer cannot be cast to java.util.List
- controller와 service의 method 명의 구분을 어떤식으로 주어야 할지를 잘 모르겠습니다 😢
- validation을 언제 어떤 부분에서 해야할지가 감이 안오는 것 같습니다 ㅠㅠ 어느 시점부터 데이터를 믿어야할지를 잘 모르겠습니다. API Request로 넘어오는 데이터가 사전에 검증될 수도 있다고 생각하다보니 헷갈리는 것 같습니다.

항상 리뷰 감사합니다! 🙇‍♂️

2022-05-21 13:20 UTC, mentor-hoon requested changes
윤오님 수고 많으셨습니다.
몇 가지 코멘트 남겼고, 확인 부탁드립니다. ~

2022-05-21 13:21 UTC, mentor-hoon commented on src/main/java/com/example/board/domain/BaseEntity.java
> +public abstract class BaseEntity {
업데이트 시간도 같이 있으면 좋을 것 같습니다. ~

2022-05-21 13:22 UTC, mentor-hoon commented on src/main/java/com/example/board/domain/BaseEntity.java
> +public abstract class BaseEntity {
Setter 가 필요한 이유가 있을까요 ??

create 시간을 수정할 위험이 있을 것 같습니다.

2022-05-21 13:22 UTC, mentor-hoon commented on src/main/java/com/example/board/domain/BaseEntity.java
> +    private LocalDateTime createdAt;
업데이트 시간도 같이 있으면 좋을 것 같습니다.

2022-05-21 13:23 UTC, mentor-hoon commented on src/main/java/com/example/board/domain/User.java
> +    private String hobby;
DDL 조건이 좀 더 있으면 좋을 것 같습니다. ~

2022-05-21 13:24 UTC, mentor-hoon commented on src/main/java/com/example/board/dto/PostDto.java
> +public class PostDto {
자바 17 이상을 사용하시면 , record 클래스를 사용해도 좋을 것 같아요

2022-05-21 13:25 UTC, mentor-hoon commented on src/main/java/com/example/board/service/PostService.java
> +                .orElseThrow(() -> new NotFoundException("찾는 게시글이 없습니다."));
예외를 던졌을 때, 혹시 HTTP status 코드가 50x 인가요 ?

2022-05-21 13:25 UTC, mentor-hoon commented on src/main/java/com/example/board/service/PostService.java
> +                .orElseThrow(() -> new NotFoundException("찾는 게시글이 없습니다."));
예외를 던졌을 때, 혹시 HTTP status 코드가 50x 인가요 ?

2022-05-21 13:26 UTC, mentor-hoon commented on src/main/java/com/example/board/service/PostService.java
> +    public Page<PostDto> getAllPostByPage(Pageable pageable) {
SELECT 작업을 하는 쿼리는 Transaction 을 read only 로 하는 것이 좋습니다. ~

2022-05-21 13:26 UTC, mentor-hoon commented on src/main/resources/application.yml
> +    open-in-view: false
해당 옵션을 false 처리한 이유를 설명해주실 수 있을까요 ??

2022-05-21 13:29 UTC, mentor-hoon commented on src/test/java/com/example/board/controller/PostControllerTest.java
> +        userId = user.getId();
테스트 후에 데이터를 clear 하는 로직이 존재하나요 ??

2022-05-23 06:11 UTC, jungyoonoh commented on src/main/java/com/example/board/domain/BaseEntity.java
> +public abstract class BaseEntity {
헉 그러네요. 수정하도록 하겠습니다

2022-05-23 06:11 UTC, jungyoonoh commented on src/main/java/com/example/board/domain/BaseEntity.java
> +    private LocalDateTime createdAt;
추가하도록 하겠습니다!

2022-05-23 06:12 UTC, jungyoonoh commented on src/main/java/com/example/board/domain/User.java
> +    private String hobby;
디테일한 부분 추가하도록 하겠습니다!

2022-05-23 06:12 UTC, jungyoonoh commented on src/main/java/com/example/board/dto/PostDto.java
> +public class PostDto {
record 클래스로 변경하겠습니다!

2022-05-23 06:23 UTC, jungyoonoh commented on src/test/java/com/example/board/controller/PostControllerTest.java
> +        userId = user.getId();
전체 클래스 테스트를 안해보고 모듈단위로만 수행했던 것 같습니다. 수정하겠습니다!

2022-05-23 06:24 UTC, jungyoonoh commented on src/main/resources/application.yml
> +    open-in-view: false
게시판 제작 이전에 연습 과정에서 테스트를 하던 중, OneToMany 관계에서 One측 데이터가 DB에 존재하지 않아 LazyInitializationException이 발생하는 이슈를 해결하기 위해서 여러 시도를 하며 설정해두었던 값을 그대로 가져와서 사용했던 것 같습니다. 수정하겠습니다!

2022-05-23 06:51 UTC, YHLEE9753 commented on src/main/java/com/example/board/dto/PostDto.java
> +}
update 나 save 등 상황에 따라 dto 가 존재하면 어떨까요?? 이번 팀 면담때 이야기한 계층별 DTO 에 대해서도 고민해보시면 좋을거 같습니다!!

2022-05-23 06:54 UTC, YHLEE9753 commented on src/main/java/com/example/board/dto/PostDto.java
> +
Request 와 Response 때 이용되는 Dto 에 대해서는 validation 에 대해 고민해보셔도 좋을거같습니다!! 저같은 경우 @RequestBody 에 @Valid 를 적은 후 DTO 에 @NotNull 과 같은 설정을 해보라는 피드백을 훈님께 받았습니다!!

2022-05-23 07:03 UTC, jungyoonoh commented on src/main/java/com/example/board/service/PostService.java
> +    public Page<PostDto> getAllPostByPage(Pageable pageable) {
넵! 적용하겠습니다

2022-05-23 07:03 UTC, YHLEE9753 commented on src/main/java/com/example/board/service/PostService.java
> +                .orElseThrow(() -> new NotFoundException("찾는 게시글이 없습니다."));
rest api exception 처리에 대해서도 고민해 보시면 좋을거 같습니다!! @RestControllerAdvice 와 같이 이미 좋은 어노테이션과 기능들이 있어서 시간이 되시면 적용해 보셔도 좋을거 같습니다!!

2022-05-23 07:04 UTC, YHLEE9753 approved these changes
윤오님 바로 해드려야되는데 많이 리뷰가 늦었습니다 죄송합니다 ㅠㅠ 전체적으로 깔끔한 코드인거 같습니다!! 부족하지만 리뷰 남깁니다~ 오늘도 화이팅 입니다!~

2022-05-23 07:24 UTC, jungyoonoh commented on src/main/java/com/example/board/dto/PostDto.java
> +public class PostDto {
멘토님 수정을 하면서 다시 보니 ID값이 generated 옵션이 적용되어 있어 ID 값을 가지고 있지 않은 상태가 있기도 한데, 이때 record class는 값을 반드시 가져야해서, class를 그대로 이용하거나 아래 용훈님이 피드백 주신 layer 별 record class를 고민해보겠습니다!

2022-05-23 07:25 UTC, jungyoonoh commented on src/main/java/com/example/board/dto/PostDto.java
> +}
Dto를 Record class로 변경하는 과정에서 이 부분의 필요성을 느꼈습니다! 고민해보고 적용해보도록 하겠습니다! 😄

2022-05-23 07:26 UTC, jungyoonoh commented on src/main/java/com/example/board/service/PostService.java
> +                .orElseThrow(() -> new NotFoundException("찾는 게시글이 없습니다."));
확실히 예외처리 부분이 아직 약한 것 같습니다. 공부해서 추가하겠습니다!

2022-05-23 07:27 UTC, jungyoonoh commented on src/main/java/com/example/board/dto/PostDto.java
> +
Response의 경우 DB로부터 값을 가져온 상태일 것 같은데 어떤 부분의 validation을 수행하면 좋을까요?
requeset의 경우 공감하는 부분이 많습니다! 분리해보도록 하겠습니다.

2022-05-23 07:52 UTC, jungyoonoh commented on src/main/java/com/example/board/service/PostService.java
> +                .orElseThrow(() -> new NotFoundException("찾는 게시글이 없습니다."));
아닌 것 같습니다. 이에 대한 예외처리 로직을 추가하도록 하겠습니다!

2022-05-23 08:44 UTC, jungyoonoh commented on src/main/resources/application.yml
> +    open-in-view: false
과제 리팩토링을 하면서 돌아보니 Controller에서 Lazy Loading을 시도하는 객체가 별도로 없어 false로 그대로 두어도 될 것 같습니다.

2022-05-23 09:11 UTC, jungyoonoh commented
멘토님 주신 피드백 반영해서 수정 완료했습니다! 한 가지 궁금한 부분이 있어 질문 드립니다.

멘토님과 용훈님 피드백 내용을 보고 Dto를 request와 response로 분리하고, 이를 record class로 변경하였습니다.
상황상 post를 생성, 수정 등의 작업을 수행하는 것은 user 정보가 반드시 있다(id 값을 알고 있다) 라고 생각하여 작업을 하였는데요, requestDto들은 id값을 가지고 있지 않습니다. (Auto Increment 적용으로 인해) 이럴 경우 현재는 로직상의 오류가 없기 위해서 UserResponseDto를 PostRequestDto가 들고 있는 형태가 되는데요, 이런 경우는 어떤식으로 더 분리가 가능할까요?

항상 리뷰 감사합니다! 추가적으로 더 수정할 부분 있으시면 말씀 부탁드립니다! 😄

2022-05-26 15:02 UTC, mentor-hoon reviewed
코드 잘 수정해주셨네요, 몇 가지 코멘트하고 답변 드리곘습니다. ~

### 질문 
> 상황상 post를 생성, 수정 등의 작업을 수행하는 것은 user 정보가 반드시 있다(id 값을 알고 있다) 라고 생각하여 작업을 하였는데요, requestDto들은 id값을 가지고 있지 않습니다. (Auto Increment 적용으로 인해) 이럴 경우 현재는 로직상의 오류가 없기 위해서 UserResponseDto를 PostRequestDto가 들고 있는 형태가 되는데요, 이런 경우는 어떤식으로 더 분리가 가능할까요?

- 흠 굳이 객체를 참조할 필요가 있는지 의문이네요
- 이건 상황을 좀 더 들어봐야될 것 같습니다. DM 주세요 ~

### 추가 코멘트
- 테스트 코드를 보면 통합 테스트 코드만 존재하는 것 같습니다.
- 목킹 라이브러리를 사용하여 계층 별로 격리 시킨 단위 테스트를 작성해보는 것도 도움이 많이 될 것 같습니다.
- 저는 현업에서 모든 레이어에 통합테스트를 사용하지 않아요, 매번 배포할 때 테스트 코드 돌리는 시간이 너무 늘어나게 되어서 최대한 지양하고 있습니다.

2022-05-26 15:02 UTC, hoon-space commented on src/main/java/com/example/board/domain/BaseEntity.java
> +    private LocalDateTime modifiedAt;
`@Column` 애노테이션에 nullable, updatable 등 옵션을 설정해보세요 ~

2022-05-26 15:02 UTC, hoon-space commented on src/main/java/com/example/board/global/GlobalExceptionHandler.java
> +        return e;
아래 블로그 보고 좀 더 고도화 해봐도 좋을 것 같습니다. 
https://cheese10yun.github.io/spring-guide-exception/

2022-05-31 07:21 UTC, jungyoonoh commented
멘토님 주신 피드백 반영해서 수정 완료했습니다!
final 객체 (record class)의 경우 아래 모듈로 변경하니 테스트 가능했습니다!

```xml
        <dependency>
            <groupId>org.mockito</groupId>
            <artifactId>mockito-inline</artifactId>
            <scope>test</scope>
        </dependency>

추가적으로 더 수정할 부분 있으시면 말씀 부탁드립니다! 😄

2022-05-31 13:53 UTC, mentor-hoon reviewed
전체적으로 잘 수정해주셨네요 ㅎㅎ

몇 가지 코멘트 남겼고, 한 번 반영해보셔도 좋을 것 같습니다. ㅎㅎ
신규 플젝에 적용해보셔도 좋고, 해당 플젝 수정 후 다시 PR 올리셔도 될 것 같아요

일단, 해당 PR 은 머지하겠습니다. ~~

2022-05-31 13:53 UTC, hoon-space commented on src/main/java/com/example/board/domain/BaseEntity.java
> +    private LocalDateTime modifiedAt;
createdAt 과 modifiedAt 도 `@Column` 이 필요하지 않을까요 ??

2022-05-31 13:53 UTC, hoon-space commented on src/main/java/com/example/board/dto/PostRequestDto.java
> +        String content,
`@NotNull` 보다는 `@NotBlank` 가 상황에 좀 더 맞을 것 같습니다.

2022-05-31 13:53 UTC, mentor-hoon commented on src/main/java/com/example/board/global/ErrorCode.java
> +    POST_NOT_FOUND(404, "P001", "Post Not Founded"),
HTTPStatus 코드는 하드코딩하는 것 보다는 스프링에서 이미 정의 된 HTTPStatus enum 을 사용하는 것이 더 좋을 것 같습니다.

2022-05-31 13:53 UTC, mentor-hoon commented on src/main/java/com/example/board/global/ErrorCode.java
> +    private final String errorMessage;
아래 처럼 이름이 변경되는게 좀 더 명확할 것 같아요
code -> statusCode
uniqueMessage -> errorCode
errorMessage -> message

2022-05-31 13:53 UTC, mentor-hoon commented on src/main/java/com/example/board/global/ErrorResponse.java
> +@AllArgsConstructor(access = AccessLevel.PROTECTED)
protected 로 생성해야할 이유가 있을까요 ??

2022-05-31 13:53 UTC, mentor-hoon approved these changes
.

2022-05-31 13:54 UTC, merged